- src/core/data/constants.js
- src/css/colors.styl
- src/css/history.styl
- src/modules/client/components/planning/EventCreationModal.vue
- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/components/planning/EventHistory.vue
- src/modules/client/components/planning/EventHistoryFeed.vue
- src/modules/client/components/planning/Planning.vue
- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/pages/ni/pay/Absences.vue
- src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
- src/modules/client/pages/ni/planning/CustomerPlanning.vue
- Périmetre interface : Admin
- Cas d'usage : Sur le planning, je vois les historiques dans la modal d'edition
+ refonte de planning beneficiaire / auxiliaires
pour le moment il n'est pas encore sur l'agenda auxiliaire - je ferai une deuxieme PR :)
> [A fusionner apres la MES] - Com 2075

- src/core/components/courses/ProfileAdmin.vue
- src/core/components/courses/ProfileOrganization.vue
- src/core/mixins/courseMixin.js
- Périmetre roles : coach/ rof
- Cas d'usage : essayer de telecharger convocation/feuilles d'emargement/attestation de fin de formation sur des formation intra et inter
> fix download on inter b2b courses for coach

- src/core/api/Courses.js
- src/core/components/courses/CourseInfoLink.vue
- src/core/components/courses/ProfileAdmin.vue
- src/core/components/courses/ProfileOrganization.vue
- src/core/mixins/courseMixin.js
- src/modules/client/components/customers/billing/CustomerBillingTable.vue
- src/modules/client/components/customers/billing/ProfileBilling.vue
> MES intermediaire 2705 (puppeteer)

- src/core/components/table/CoachList.vue
- Cas d'usage : Ajout d'un coach a une structure avec erp et sans erp
> COM-2098 - refacto coach email

- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/mixins/planningActionMixin.js
Lorsqu'un évenement est horodaté (pour sa date de fin), je ne peux plus modifier :
- son auxiliaire
- son secteur
- sa date
- je ne peux plus annuler l'évenement
> COM-2091: can't update a timestamped end date

- src/modules/client/components/customers/CustomerProfileHeader.vue
- Cas d'usage : bouton "arrêter le bénéficiaire" masqué en attendant COM-2094
> hide-stop-button: hide button

- package-lock.json
- package.json
- src/core/components/form/DatetimeRange.vue
- src/core/components/table/CoachList.vue
- src/core/data/constants.js
- src/core/helpers/date.js
- src/core/mixins/learnerDirectoryMixin.js
- src/css/colors.styl
- src/css/history.styl
- src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
- src/modules/client/components/customers/CustomerProfileHeader.vue
- src/modules/client/components/customers/infos/StopSupportModal.vue
- src/modules/client/components/planning/DeleteEventsModal.vue
- src/modules/client/components/planning/EventCreationModal.vue
- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/components/planning/EventHistory.vue
- src/modules/client/components/planning/EventHistoryFeed.vue
- src/modules/client/components/planning/Planning.vue
- src/modules/client/components/planning/PlanningModalHeader.vue
- src/modules/client/mixins/customerMixin.js
- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/mixins/planningModalMixin.js
- src/modules/client/pages/ni/customers/CustomersDirectory.vue
- src/modules/client/pages/ni/pay/Absences.vue
- src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
- src/modules/client/pages/ni/planning/CustomerPlanning.vue
> Mes fix 0706

- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/components/planning/Planning.vue
- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/pages/ni/pay/Absences.vue
- src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
- src/modules/client/pages/ni/planning/CustomerPlanning.vue
> MES intermédiaire 09/06

- src/core/data/constants.js
- Périmetre roles : admin/coach/aux
- Cas d'usage : changement de la constante des raisons pour arrêter un bénéficiaire
> COM-2094: change constant

- src/modules/client/components/planning/DeleteEventsModal.vue
- src/modules/client/components/planning/Planning.vue
- Cas d'usage : ajout d'un loader sur la modale de suppression (+ j'ai retiré loading dans planning car j'ai l'impression qu'il n'était utilisé nul part, vous confirmez ?)
> COM-2139: add loader

- src/core/api/Events.js
- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/pages/ni/pay/Absences.vue
- Périmetre roles : auxiliaire/coach
- Cas d'usage : Lorsque j'ouvre une modale d'edition d'evnement : 
- Je peux voir l'historique de l'evenement
- Si la date de debut est horodate, elle est grisée
- Si la date de fin est horodate, elle est grisée
> Com 2075 histories

- src/modules/client/components/planning/Planning.vue
- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
- src/modules/client/pages/ni/planning/CustomerPlanning.vue
- Périmetre roles : auxiliaire / coach
- Cas d'usage : sur le planning auxiliaire et bénéficiaire, j'ai accès au évènements plus rapidement
> COM-2075 - refacto events

- src/modules/client/components/customers/CustomerProfileHeader.vue
Après tant de semaines passées dans l'ombre, il voit de nouveau la lumière
> COM-2094 - Show button

- src/modules/client/components/customers/infos/FundingCreationModal.vue
- src/modules/client/components/customers/infos/FundingEditionModal.vue
- src/modules/client/components/customers/infos/ProfileInfo.vue
- Cas d'usage : pour les tiers payeurs qui ont un id de teletransmission, je peux ajouter un id de financement à la création et à l'édition d'un plan de financement
> COM-2143: add teletransmission field to funding modals

- src/modules/client/components/customers/infos/ProfileInfo.vue
- ajouter plan de financement forfaitaire et horaire : s'assurer que Prix unitaire TTC > 0, Nb. heures prises en charge > 0, 0 <= Taux de participation du bénéficiaire < 100, Montant forfaitaire TTC > 0
- éditer les plans et s'assurer que les mêmes validations fonctionnent
- créé un plan forfaitaire en remplissant ses champs puis switcher sur un plan horaire avant de valider et s'assurer qu'en base on a que les champs associé à la nature du plan (si hourly 'unitTTCRate', 'careHours', 'customerParticipationRate' et si fixed 'amountTTC')
- faire l'inverse
> COM-2186: fix bugs

- src/modules/client/pages/ni/billing/CreditNotes.vue
- Cas d'usage : fix du bouton sur la page des avoirs.
> COM-2192 fix creditNote button

- src/modules/client/components/customers/infos/FundingDetailsModal.vue
- src/modules/client/mixins/fundingMixin.js
- Cas d'usage : si ID de plan de financement, je le vois dans la modale de détails
> COM-2143: add fundingplanId to details modal

- src/css/drawer.styl
> COM-2192 - fix menu on helper side

- src/modules/client/components/table/CustomerNoteCell.vue
- src/modules/client/components/table/CustomerNotesContainer.vue
- Périmetre roles : admin/aux/coach
- Cas d'usage : alignement contenu note avec icone header + passage de div à template
> COM-2175: minor fix

- src/core/api/CustomerNotes.js
- src/core/components/form/Input.vue
- src/core/components/modal/Modal.vue
- src/modules/client/components/customers/ProfileFollowUp.vue
- src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
- src/modules/client/components/table/CustomerNoteCell.vue
- src/modules/client/components/table/CustomerNotesContainer.vue
- Périmetre roles : aux/coach/admin
- Cas d'usage : je peux éditer une note de suivi
> COM-2176: edition modal

- src/core/components/form/MultipleFilesUploader.vue
- src/modules/client/components/auxiliary/ProfileInfo.vue
- src/modules/client/components/customers/ProfileFollowUp.vue
- src/modules/client/components/customers/infos/ProfileInfo.vue
- src/modules/client/mixins/customerMixin.js
- src/modules/client/pages/customers/Subscriptions.vue
- Périmetre roles : helper
- Cas d'usage : je peux télécharger le QR code de mon bénéficiaire dans la section abonnement
> COM-2174: add qrcode button to helper

- src/modules/client/pages/ni/config/CustomersConfig.vue
- Cas d'usage : sur la page "configuration bénéficiaire", je peux ajouter un modèle de conditions générales de services
- Cas de tests : 
- Verifier que le telechargement se passe bien
- Verifier que l’on peut telecharger le document
- Verifier que l’on peut supprimer le document
> COM-2210 create a file-uploader to upload general terms of services

- src/core/components/form/Input.vue
- src/core/data/constants.js
- src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
- src/modules/client/components/customers/infos/CustomerNoteHistory.vue
- src/modules/client/components/customers/infos/CustomerNoteHistoryContainer.vue
- src/modules/client/components/table/CustomerNoteCell.vue
- Périmetre roles : aux/coach/admin
- Cas d'usage : je peux voir la dernière modification sur une note de suivi et voir l'historique complet d'une note de suivi sur la modale d'édition
> COM-2206: lashistory on cell

- src/core/components/courses/ProfileTraineeFollowUp.vue
- Périmetre roles : coach / client admin
- Cas d'usage : sur l'interface client, dans une fomation mixte, dans l'onglet 'suivi des stagiaires' : je ne vois pas la section 'reponses aux questionnaires'
> COM-2120 disable questionnaire answer in client interface

- src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
- src/modules/client/components/table/CustomerNoteCell.vue
- Périmetre roles : aux/coach/admin
- Cas d'usage : retour de Romain sur la couleur du message d'historique grey-800 => copper-grey-500
> COM-2206: change message color

- src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
- Cas d'usage : sur la fiche structure partenaire, le nombre de beneficiaire prescrit par chaque partenaire apparait et le détail aussi (nom du beneficiaire et date de creation du beneficiaire).
> COM-2071 add empty state

- src/modules/client/pages/customers/Subscriptions.vue
Fix du bug où le fichier chargeait à l'infini sans s'afficher
> COM-2211 - Fix bug

- src/modules/client/components/customers/infos/CustomerNoteHistory.vue
- Périmetre interface :  client
- Cas d'usage : lorsque l'on modifie le titre d'une note, l'historique est créé
> COM-2208 displays title history

- src/core/data/constants.js
- src/modules/client/components/planning/EventHistory.vue
- ~~J'ai ajouté une variable d'environnement : ~~
- Périmetre roles : auxiliaire
Dans la modale d'édition d'un évènement, je vois l'historique de l'horodatage via qr code
Dans l'export des interventions, je vois aussi l'horodatage via qr code
Lorsqu'un événement est horodaté via qr code, l'heure est bien mise à jour sur le planning
> COM-2189 - handle qr code time stamping in event history

- src/core/mixins/courseMixin.js
- Cas d'usage : Sur la page admin d'une formation mixte, tant que le telephone du contact n'est pas correct je ne peux pas cliquer sur les actions utiles
> COM-2232: doesn't access to useful actions if phone number incorrect

- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/components/table/AttendanceTable.vue
- Périmetre interface : formation
- Cas d'usage : fix : dans le tableau des feuilles d'emargement. Les noms des stagiaires, pour qui on a ajouté un feuille puis qu'on a désinscrit du cours, sont visible.
De plus j'ai ajouté, comme dans le tableau de presence, un petit 'Pas inscrit' en bas du nom
> COM-2235 fixed name of unregistered trainee

- src/modules/client/pages/ni/courses/LearnerProfile.vue
- src/store/userProfile.js
si depuis le répertoire apprenant côté coach, j'essaie d'accéder à un apprenant qui n'est pas de ma strucuture ou qui n'a pas de structure je reçois une 404.
TEST : 
accéder à un apprenant depuis le côté vendeur => ça fonctionne
accéder à un apprenant de ma structure côté client => ça fonctionne
accéder à un apprenant d'une autre structure côté client => 404
accéder à un apprenant sans structure côté client => 404
se connecter à l'app de formation et faire une activité avec son compte => ça fonctionne
se connecter à l'app de formation et faire une activité avec un compte rattaché à aucune structure => ça fonctionne
> COM-2203: return 404 for forbidden user

- src/core/components/form/Input.vue
- src/css/input.styl
- Périmetre interface : tous
- Périmetre roles : admin/coach/rof
- Cas d'usage : ajout de la bordure autour de l'input d'upload de fichier dans les modales
> COM-2227: add border on file upload

- src/core/components/courses/TraineeTable.vue
- src/modules/client/mixins/helperMixin.js
- src/modules/client/pages/ni/courses/LearnersDirectory.vue
- Périmetre roles : coach/admin_client/rof/vendor_admin
- Cas d'usage : quand j'ajoute un utilisateur d'une autre structure dans les cas suivants je n'ai plus qu'un seul appel (users/exists) et je ne reçois plus d'erreur : 
- ajout d'un apprenant dans une formation intra
- ajout d'un coach
- ajout d'un aidant
- ajout d'un apprenant au répertoire des apprenants
pour les tests côté client faire les tests avec un compte admin seul (pas son propre compte donc vu qu'on a aussi le statut vendeur)
> COM-2230: block request if user from other company

- src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
- Périmetre interface : outil
- Périmetre roles : coach admin
- Cas d'usage : fix de l'edition d'un partenaire
> COM-2257 remove partnerorga from payload

- src/css/colors.styl
- src/modules/client/components/table/FundingGridTable.vue
- src/modules/client/pages/customers/Subscriptions.vue
- Cas d'usage : Sur l'interface aidant, quand mon bénéficiaire a un financement, je vois les colonnes Tiers payeur / numero de dossier / date de debut / Montant TTC / Jours de prise en charge si mon financement est forfaitaire et Tiers payeur / numero de dossier / date de debut / montant unitaire / nombre d'heures / taux de participation / Jours de prise en charge si le financement est horaire
> Com 2205 helper

- src/modules/client/components/customers/infos/HelperEditionModal.vue
- src/modules/client/mixins/helperMixin.js
- Cas d'usage : quelques occurences restantes de "aidant"
> COM-2109: forgotten words

- src/modules/client/pages/ni/auxiliaries/Dashboard.vue
> MES 30.08.2021 | COM-2312-staging

- src/core/components/courses/ConnectedDot.vue
- src/core/components/popup/notify.js
- src/css/colors.styl
- src/css/icon.styl
- src/css/quasar.variables.styl
- src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
- src/modules/client/components/auxiliary/ProfileInfo.vue
- src/modules/client/components/contracts/ContractsCell.vue
- src/modules/client/components/customers/CustomerProfileHeader.vue
- src/modules/client/pages/ni/auxiliaries/Dashboard.vue
- src/modules/vendor/components/programs/ProfileContent.vue
- Cas d'usage : passage du green-800 au green-600
> COM-2305: change green

- src/core/api/Companies.js
- Cas d'usage : retrait du params inutilisé. S'assurer que les pages suivantes fonctionnent : 
- tableau des apprenants sur une formation
- l'ajout d'un règle d'accès sur une formation
- la publication d'un sous-programme 100% elearning
- le répertoire des formations
- le répertoire des structures
> COM-2306: remove useless params

- src/core/components/courses/QuestionnaireCell.vue
- Cas d'usage : refonte UI cellule questionnaire : changement couleur => copper-grey-200 / ajout du nombre de réponses au questionnaire
> COM-2304: refacto UI questionnaire cell

- src/core/api/CompanyLinkRequests.js
- src/core/components/CompanyLinkRequestCell.vue
- src/css/colors.styl
- src/css/quasar.variables.styl
- src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
- src/modules/client/components/planning/ChipCustomerIndicator.vue
- src/modules/client/pages/ni/auxiliaries/Dashboard.vue
- src/modules/client/pages/ni/courses/Dashboard.vue
- Cas d'usage : je peux accepter les demandes de rattachement à ma structure
> COM-2307: accept link request

- src/modules/client/components/planning/EventHistoryFeed.vue
- src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
- Périmetre roles : Auxiliaire / Coach
- Cas d'usage : Sur le flux du planning, je ne recupere du back que ceux que j'affiche (plus les horodatage du coup)
> COM-2327 - filter event histories in back

- src/modules/client/components/customers/infos/ProfileInfo.vue
- src/modules/client/pages/auxiliaries/administrative/Documents.vue
- Périmetre roles : Coach / Auxilaire
Quand je télécharge les fichiers suivants, j'appelle la route du back : Page document sur le profil auxiliaire + Mandat et devis sur la page bénéfiicaire coté coach
> Com 2322 2

- src/core/components/form/FileUploader.vue
- src/core/components/form/MultipleFilesUploader.vue
- src/modules/client/components/auxiliary/ProfileInfo.vue
- src/modules/client/components/customers/infos/ProfileInfo.vue
- src/modules/client/components/planning/EventCreationModal.vue
- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/pages/customers/Subscriptions.vue
- src/modules/client/pages/ni/config/CustomersConfig.vue
- src/modules/client/pages/ni/config/RhConfig.vue
- src/modules/vendor/components/programs/ProfileInfo.vue
- src/modules/vendor/components/programs/cards/templates/TextMedia.vue
- src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
- Périmetre roles : Coach / Auxiliaire / Aidant
Onglet info de l'auxilaire : CNI / Passeport / Titre de séjour / Attestation / Telephone / Mutuelle / Diplômes / transport / Visite Médicale
Onglet info du Beneficiaire : Justificatif de financement
Page souscription cote aidant : Justificatif de financement
Modal de creation / edition d'une absence 
Config Beneficiaire : modele devis / mandat / CGS
Config RH : modele contrat et avenant
> COM-2319 - update file uploader

- src/core/components/courses/QuestionAnswerChart.vue
- src/core/components/courses/SurveyChart.vue
- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
- Cas d'usage : je peux afficher les réponses aux questionnaires pour un.e formateur.rice spécifique
> COM-2302: add trainer selector for questionnaire answers

- src/core/api/CompanyLinkRequests.js
- src/core/components/CompanyLinkRequestCell.vue
- src/modules/client/pages/ni/courses/Dashboard.vue
- Cas d'usage : je peux supprimer les demandes de rattachement à ma structure
> COM-2308 : remove link request

- src/modules/client/pages/ni/courses/Dashboard.vue
- Cas d'usage : appels dans un Promise.all pour afficher les demandes de rattachement plus vite
> COM-2308: created calls in a promise.all

- src/core/components/courses/TraineeAdditionModal.vue
- src/core/components/courses/TraineeTable.vue
- src/core/components/form/Select.vue
- Périmetre roles : rof, admin
- Cas d'usage : Lors de l'ajout d'un.e stagiaire a une formation, quand je clique sur le select, je vois une liste d'apprenant.es avec photo, nom, email et structure.
> Com 2301 select

- src/modules/client/mixins/planningActionMixin.js
- Cas d'usage : Pour un évènement relié a une intervention : 
si je modifie la note ou le champ `transport specifique`, ca ne retire pas l'intervention de la repetition
si je modifie ensuite cette evenement en cochant `Appliquer a la repetition` la note et le transport specifique ne sont pas supprimés
> COM-2294 - handle repetitions

- src/core/api/GoogleDrive.js
- src/core/components/form/FileUploader.vue
- src/core/components/form/MultipleFilesUploader.vue
- src/core/helpers/file.js
- src/modules/client/components/auxiliary/ProfileInfo.vue
- src/modules/client/components/auxiliary/ProfilePay.vue
- src/modules/client/components/contracts/ContractsCell.vue
- src/modules/client/components/customers/billing/CustomerBillingTable.vue
- src/modules/client/components/customers/billing/ProfileBilling.vue
- src/modules/client/components/customers/infos/ProfileInfo.vue
- src/modules/client/components/planning/EventCreationModal.vue
- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/pages/auxiliaries/administrative/Documents.vue
- src/modules/client/pages/customers/Subscriptions.vue
- src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
- src/modules/client/pages/ni/config/CustomersConfig.vue
- src/modules/client/pages/ni/config/RhConfig.vue
- src/modules/client/pages/ni/pay/Absences.vue
- src/modules/vendor/components/programs/ProfileInfo.vue
- src/modules/vendor/components/programs/cards/templates/TextMedia.vue
- src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
- Cas d'usage : Quand je télécharge les documents suivants, ça passe par le back
Role coach : 
-- Sur la fiche auxiliaire : 
-- Carte d'identité recto
-- Carte d'identité verso
-- Passport
-- Titre de sjeour recto
-- Titre de séjour verso
-- Attestation de secu
-- Telephone
-- Diplome
-- Mutuelle
-- Abonnement transport
-- Certificat medical
-- Contrat
-- Archive
-- Fiche de paie
-- Registre unique du personnel : Titre de sejour recto / verso
-- Planning : Modal de creation et d'edition d'une absence
-- Fiche bénéficiaire : 
-- Justificatif de financements
-- Devis signé
-- Mandat signé
-- Facture / Avoir / Attestation fiscale qui sont sur le drive
-- Configuration RH
-- Modèle de …
> Com 2319 staging

- src/modules/client/components/contracts/ContractsCell.vue
- src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
A Tester :
Pour tester facilement : commenter les lignes 38 à 42 sur removeRessources de script puis lance un dump-restore de staging vers local. Sur l'auxiliaire "Exemple Auxiliaire", le contrat est "En attente de signature" côté coach et coté auxiliaire pour les deux premiers avenants. 
pour se connecter côté auxiliaire : 'romain+aux@compani.fr + 123456'.
Il faut vérifier que sur cette branche, on peut alors télécharger les deux premiers avenants.
Puis faire les tests suivants :
-- si pas de signature en ligne et pas de doc drive je vois le + pour charger un fichier
--- etq auxilaire, je ne vois rien
-- si signature en ligne et je n'ai pas signé : je vois …
> Com 2319 contract

- src/modules/client/components/contracts/ContractsCell.vue
- src/modules/client/pages/ni/auxiliaries/StaffRegister.vue
Sur le profile Auxiliaire, onglet contrat
-- si pas de signature en ligne et pas de doc drive je vois le + pour charger un fichier
--- etq auxilaire, je ne vois rien
-- si signature en ligne et je n'ai pas signé : je vois le bouton signer
--- si le contrat est fini je ne vois rien
-- si signature en ligne, j'ai signé mais pas l'autre partie, je vois "en attente de signature"
-- Si les 2 ont signé en ligne, je vois le bouton pour telecharger le doc signé
Sur le registre unique du personnel :
Pour tester : aller sur une nouvelle auxiliaire, charger une CNI, la supprimer, charger un titre de séjour et essayé de le télécharger depuis le registre unique du personnel.
je peux telecharger les document que ce soit CNI ou titre de sejour
> Com 2319 staging contract

- src/modules/vendor/pages/ni/management/QuestionnaireAnswersProfile.vue
- ~J'ai ajouté une variable d'environnement :~
- [] J'ai verifié la fonctionnalite sur mobile
- Périmetre interface : formation
- Périmetre roles : rof, vendeur admin
- Cas d'usage : correction du bug de l'affichage d'un questionnaire depuis la page formation
> COM-2302-fix fix questionnaireAnswerProfile

- src/core/components/BiColorButton.vue
- src/core/components/form/DatetimeRange.vue
- src/core/components/form/Input.vue
- src/css/input.styl
- src/modules/client/components/customers/billing/ManualBillCreationModal.vue
- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/pages/ni/billing/ManualBills.vue
Quand je crée une facture manuelle, je peux y ajouter plusieurs article
Quand je sélectionne un article, le prix par défaut de cet article est mis en prix unitaire TTC
Je peux modifier le prix TTC et la volume
Je peux supprimer un article
> Com 2298 billing article

- src/modules/client/pages/ni/billing/DebitsArchive.vue
- Cas d'usage : etq qu'admin, je peux telecharger des archives de prelevement (depuis la page du meme nom) 
- a tester : la requete passe par l'api.
> COM-2320 go throw API

- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/mixins/planningActionMixin.js
- Périmetre roles : aux, coach
- Cas d'usage : etq aux, je peux ajouter un trajet que j'ai parcouru avec le/la bénef pdt l'intervention.
> COM-2293 add kmDuringEvent in modal

- src/modules/client/pages/ni/config/CustomersConfig.vue
Fix d'un bug où la liste des articles de facturation ne contient que les articles de type 'par intervention'
> COM-2346 - Fix billingItem list bug

- src/core/api/Bills.js
- src/modules/client/pages/ni/billing/ManualBills.vue
- Périmetre interface : client outils
- Cas d'usage : je vois les factures manuelles sur la page du meme nom
> Com 2298 get

- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
- Cas d'usage : je peux filter les questionnaires en fct de la structure du stagiaire qui a repondu
> COM-2333 company filter

- src/core/api/Programs.js
- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
- Cas d'usage : je peux filtrer les réponses aux questionnaires par le nom du programme
> COM-2334: filter by program

- src/modules/client/components/table/ToBillRow.vue
Sur la page 'A Facturer', je vois les articles de facturation lorsqu'une intervention est liée à un article de facturation.
Pour tester : 
- ajouter 2 - 3 articles de facturation par intervention
- lier ces facturations avec des services (penser à varier les dates d'effet, pour vérifier qu'elles sont bien prises en compte)
- ajouter des interventions à un bénéficiaire en variant : le service, la date, ...
- Regarder sur la page 'A facturer' que vous voyez bien les articles liés aux interventions avec le bon prix pour chaque intervention
> COM-2328 - Handle billingItems in draft pay

- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
- Cas d'usage : je peux réinitialiser les filtres sur les réponses aux questionnaires
> COM-2335: reset filters

- package-lock.json
- package.json
Fix du pb des appels infinis a api-adress.data.gouv avec un downgrade de axios a 0.21.1
> COM-2355-downgrade downgrade axios to 0.21.1

- package-lock.json
- package.json
- src/core/helpers/vuelidateCustomVal.js
- Cas d'usage : lorsque je touche le champ address (onglet Info d'un.e auxiliaire/bénéficiaire ou modales tel que modale de création d'une heure interne), je n'ai pas une boucle infini d'appel à l'API
- j'ai remis la MAJ d'Axios
- je ne saurais pas vraiment expliquer pourquoi l'intercepteur empêche la boucle infinie, surtout qu'il ne fait rien de spécial. Dans le changelog de la MAJ d'Axios ils ont touchés aux intercepteurs mais je ne vois pas trop comment leurs changements ont pu provoquer ce bug
https://github.com/axios/axios/blob/master/CHANGELOG.md
> COM-2355: infinite loop

- src/modules/client/pages/ni/config/CustomersConfig.vue
- Cas d'usage : arrondir la TVA au dixième et non à l'entier le plus proche
> COM-2359: display good VAT

- src/modules/client/components/config/ServiceEditionModal.vue
- src/modules/client/pages/ni/config/CustomersConfig.vue
- Cas d'usage : je ne peux pas créer une version du service à la même date ou à une date antérieure à la version précédente
> COM-2354: can't have two versions with same date

- src/core/components/Button.vue
- src/modules/client/components/table/ToBillRow.vue
- src/modules/client/pages/ni/billing/ToBill.vue
- Cas d'usage : Quand je change la date de début sur le une ligne du tableau a facturer, la ligne se met bien a jour
> COM-2384 - fix startDate on toBill

- src/core/helpers/vuelidateCustomVal.js
- src/modules/client/components/config/BillingItemCreationModal.vue
- src/modules/client/mixins/configMixin.js
- src/modules/client/pages/ni/config/CustomersConfig.vue
- Cas d'usage : pour le prix d'un service / article de facturation / ttp je ne peux pas mettre 3 chiffres apres la virgules
> COM-2332 - max 2 fractions in  numbers

- src/modules/client/mixins/payMixin.js
- [] J'ai verifié la fonctionnalite sur mobile
- Cas d'usage : Quand je valide la paie, les kilomètres parcourus et les kilomètres payés sont enregistrés en base de donnée
> COM-2396 - add paidkm

- src/core/components/form/DateInput.vue
- src/modules/client/components/customers/infos/ProfileInfo.vue
Cas pour reproduire
1. Créer un financement avec une participation du bénéficiaire a 0
2. Editer ce financement sans changer les champs : ouvrir la modal d’édition puis directement cliquer sur editer
3. La nouvelle version du financement n’a pas de customerParticipationRate
> COM-2399 - fix funding edition

- src/modules/client/pages/ni/billing/CreditNotes.vue
- Cas d'usage : cf les etapes du ticket, c'est super bien expliqué :) https://compani.atlassian.net/browse/COM-2400
> COM-2400 - reset selected events on toggle

- src/core/data/constants.js
- src/modules/vendor/components/programs/ProfileContent.vue
- Périmetre interface : vendeur formation
- Cas d'usage : Je peux créer une étape "distanciel" dans un sous-programme
> COM-2372 add remote step type

- src/core/components/courses/ProfileAdmin.vue
- Périmetre roles : rof/admin/formateur
- Cas d'usage : si aucun des stagiaires de la formation n'a de numéro de téléphone, je ne peux pas leur envoyer de SMS
> COM-2385: disable SMS if no phone numbers

- src/modules/client/mixins/configMixin.js
- src/modules/client/pages/ni/config/CustomersConfig.vue
Je peux ajouter un pied de page dans la configuration bénéficiaire qui apparaitra (pas fait dans cette PR) dans les factures.
Le champ est enregistré dans company.customerConfig.billFooter
> COM-2392 - Add billFooter input

- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/pages/ni/planning/CustomerPlanning.vue
- je ne peux pas archiver un beneficiaire avant sa date d'arret
- une fois le beneficiaire archivé, je ne peux ni creer de nouvel evenement ni editer d'evenement
> COM-2366 - can't create or update events when customer is archived

- src/core/components/courses/SlotContainer.vue
- src/core/components/courses/SlotCreationModal.vue
- src/core/components/courses/SlotEditionModal.vue
- src/core/data/constants.js
- src/core/helpers/utils.js
- src/modules/vendor/components/programs/ProfileContent.vue
- src/modules/vendor/components/programs/StepCreationModal.vue
- Périmetre roles : vendeur_admin/rof/trainer/coach/client_admin
- Cas d'usage : je peux ajouter un créneau sur une étape distancielle
> COM-2373: add remote course slot to course

- src/modules/client/pages/ni/billing/ToBill.vue
MES
Je peux valider le tableau de facturation même avec beaucoup de tiers payeurs et d'article de facturation
> MES - 12/10

- src/core/data/constants.js
- src/modules/client/components/planning/DeleteEventsModal.vue
- Périmetre roles : auxiliaire/ coach/ admin
- Cas d'usage : Je peux créer une absence bénéficiaire.
> COM-2473 - create customerAbsence

- src/modules/client/mixins/planningActionMixin.js
- ~~[ ] J'ai verifié la fonctionnalite sur mobile~~
- Périmetre roles : admin / auxi
Ne pas autoriser la création / l'édition d'évènement si le bénéficiaire est absent à cette date
> COM-2474 - Prevent event creation and update if customer is absent

- src/core/components/courses/SlotContainer.vue
- Cas d'usage : je ne peux pas ajouter ou éditer de créneau sur une formation archivée
> COM-2480: block slot addition and edition

- src/core/components/DirectoryHeader.vue
- src/core/components/courses/BlendedCourseProfileHeader.vue
- src/core/components/courses/CourseCell.vue
- src/core/mixins/courseFiltersMixin.js
- src/core/mixins/courseMixin.js
- src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
- Périmetre roles : rof/formateur/coach/admin-vendeur/client
- Cas d'usage : je peux n'afficher que les formations archivées sur le kanban. 
A tester côté vendeur en tant que ROF et formateur
A tester côté client en tant que coach/admin-client
> COM-2479: add togle on kanban

- src/core/components/courses/ElearningFollowUpTable.vue
- src/core/components/courses/ProfileFollowUp.vue
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/mixins/traineeFollowUpTableMixin.js
- Périmetre roles : coach/rof/formateur/admin-vendeur-client
- Cas d'usage : dans le suivi d'une formation, le tableau de progression ne prend en compte que la progression elearning. Ce tableau est également utilisé dans l'onglet formation eLearning côté client et vendeur
> COM-2486: refacto progress

- src/core/components/courses/ProfileAdmin.vue
- src/core/components/courses/ProfileOrganization.vue
- src/core/mixins/courseMixin.js
- Périmetre roles : rof/admin/formateur
- Cas d'usage : je ne peux pas éditer les champs suivants dans une formation archivée : 
Organisation : informations complémentaires, référent Compani, intervenant
Admin : Prénom Nom, Téléphone, email
> COM-2484: block infos edition

- src/core/components/table/AttendanceTable.vue
- Périmetre interface : formation / vendeur et client
- Périmetre roles : etq coach ou rof
- Cas d'usage : je ne peux pas cocher/decocher les presences. Je ne peux pas ajouter un.e participant.e
> COM-2485 disable attendance when course is archived

- src/core/components/table/AttendanceTable.vue
- Périmetre interface : vendeur et client
- Périmetre roles : rof, coach
- Cas d'usage : la creation/suppression de feuille d'emargement est bbloqué si la formation est archivée
> COM-2482 block attendanceSheet creation/delection if archived

- src/core/components/courses/ProfileAdmin.vue
- Cas d'usage : refacto de la banniere au dessus du bouton pour envoyer les sms.
> COM-2483 refacto sms icon, notify and banner

- src/core/components/table/AttendanceTable.vue
- src/modules/client/components/customers/billing/DeliveryDownloadModal.vue
- src/modules/client/pages/ni/billing/ToBill.vue
- Cas d'usage : Quand je telecharge le fichier de delivery, je peux séléctionner plusieurs tiers payeur
> COM-2507 - multiple tpps

- src/core/components/courses/ProfileAdmin.vue
- Périmetre roles : formaterur
- Cas d'usage : comme l'etat "terminée" d'une fomation "est compris dans" l'etat "archivé". Pas besoinde preciser que la formation est archivée. le fait qu'elle soit terminée est suffisant au blocage des sms
-
> COM-2483-fix remove archive error msg

- src/modules/client/components/planning/Agenda.vue
- src/modules/client/pages/customers/CustomerAgenda.vue
- Périmetre interface : client 
- Périmetre roles : Aidant
- Cas d'usage : Je vois l'absence du beneficiaire sur l'agenda
> COM-2495 - helper can see customer absences on his planning

- src/core/components/courses/TraineeTable.vue
- src/core/components/form/Select.vue
- Périmetre roles : admin/coach/rof/formateur
- Cas d'usage : dans une formation, je peux ajouter un stagiaire avec son email
> COM-2517: can add trainee with email

- src/modules/client/components/config/ServiceCreationModal.vue
- src/modules/client/pages/ni/config/CustomersConfig.vue
- Cas d'usage : dans la page "configuration bénéficiaire", a la création du service, je peux ajouter un article de facturation
> COM-2476 - add billingItems in serviceCreationModal

- src/modules/vendor/components/companies/CompanyLinkModal.vue
- src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
- Cas d'usage : je peux rattacher un apprenant à une structure depuis sa fiche apprenant
> COM-2518: allow link to company

- src/core/components/courses/LearnerCreationModal.vue
- src/core/components/courses/TraineeAdditionModal.vue
- src/core/components/courses/TraineeTable.vue
- src/core/components/form/Select.vue
- src/core/mixins/learnerCreationMixin.js
- src/core/mixins/learnerDirectoryMixin.js
- src/modules/client/pages/ni/courses/LearnersDirectory.vue
- src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
- Périmetre roles : admin/coach/rof/trainer
- Cas d'usage : je peux créer un apprenant depuis une formation s'il n'existe pas déjà
TEST : 
en tant que ROF/coach/formateur
je peux ajouter un apprenant existant (inter/intra)
je peux ajouter un apprenant existant sans structure (inter/intra)
je peux ajouter un apprenant qui n'existe pas (inter/intra)
je ne peux pas ajouter un aidant comme apprenant (intra)
je peux ajouter un aidant comme apprenant (inter)
je ne peux pas ajouter un apprenant d'une autre structure (intra)
les répertoires apprenants fonctionnent correctement (client/vendeur)
les modifications d'utilisateur fonctionnent correctement (mobile/webapp)
> COM-2520: create user to add to course

- src/core/components/courses/SlotContainer.vue
- src/core/components/courses/SlotCreationModal.vue
- src/core/components/courses/SlotEditionModal.vue
- Périmetre roles : rof/admin/formateur/coach
- Cas d'usage : quand j'ajoute une adresse et que je modifie les autres champs de la modale d'édition ou de création de créneau, je n'ai pas de mutliples appels à l'api des adresses dès que je touche un champ
> COM-2461: stop multiple api call when edit or create slot with address

- src/modules/client/mixins/planningModalMixin.js
- Périmetre roles : admin/coach/planning_referent
- Cas d'usage : je ne peux pas supprimé un événement ou une liste d'événement d'un bénéficiaire archivé
> COM-2442: don't show archived customer in delete event modal

- src/core/components/courses/ProfileAdmin.vue
- Cas d'usage : fix : enlever les doublons dans les options du champ "contact".
> COM-2556-fix remove duplicates

- src/core/components/courses/ProfileAdmin.vue
- Cas d'usage : dans une formation intra, je peux choisir un coach comme contact.
- COmment tester : bien verifier que le coach ajouté n'a pas de role vendeur
> COM-2556-fix-2 add coachs

- src/modules/vendor/components/programs/ProfileContent.vue
- Cas d'usage : quand j'arrive sur l'onglet sous-programmes d'un programme depuis le catalogue, je n'ai pas d'erreur en console. 
Test : 
- un programme avec un (des) sous-programme(s) contenant des étapes
- un programme avec un (des) sous-programme(s) sans étapes
- un programme sans sous-programmes
> COM-2574: error in console on locked steps

- src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
- Périmetre interface : client 
- Cas d'usage : quand je créé un nouvel auxiliaire je n'ai pas des appels à l'api d'adresse à chaque modification d'un champ
> COM-2462: block multiple api calls

- src/modules/client/components/auxiliary/AuxiliaryCreationModal.vue
- src/modules/client/pages/ni/auxiliaries/Directory.vue
- Cas d'usage : quand je créé un nouvel auxiliaire je n'ai pas des appels à l'api d'adresse à chaque modification d'un champ (mise à jour de l'objet dans le parent)
> COM-2462: pass set in parent

- src/core/components/courses/SlotContainer.vue
- src/modules/client/components/config/ThirdPartyPayerCreationModal.vue
- src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
- src/modules/client/pages/ni/config/CustomersConfig.vue
- Cas d'usage : Sur les modale de création et d'édition de tiers payeur. Je modifie l'adresse, je valide. Je modifie un autre champ => je n'ai plus d'appel a l'api adresse.data.gouv
> COM-2563 block address validation calls

- src/modules/client/components/config/EstablishmentCreationModal.vue
- src/modules/client/components/config/EstablishmentEditionModal.vue
- src/modules/client/pages/ni/config/CompanyConfig.vue
- Cas d'usage : modale d'edition et de creation d'un etablissement. fix des appels a chaque modification de la modale, une fois l'addresse remplie
> COM-2564 refacto update

- package-lock.json
- package.json
- src/core/components/BiColorButton.vue
- src/core/components/Button.vue
- src/core/components/courses/AttendanceSheetAdditionModal.vue
- src/core/components/courses/LearnerCreationModal.vue
- src/core/components/courses/SlotCreationModal.vue
- src/core/components/courses/SlotEditionModal.vue
- src/core/components/courses/SmsSendingModal.vue
- src/core/components/courses/TraineeAdditionModal.vue
- src/core/components/courses/TraineeEditionModal.vue
- src/core/components/table/CoachCreationModal.vue
- src/core/components/table/CoachEditionModal.vue
- src/core/components/table/TraineeAttendanceCreationModal.vue
- src/core/pages/404.vue
- src/core/pages/signin/403.vue
- Cas d'usage : Quand je clique sur un bouton, je ne suis plus redirigé vers la page d'accueil
Le bug venait de la props href qu'on passait en `''` au composant `q-btn`
J'en ai profité pour refacto quelques boutons (il y en a encore beucoup mais ce n'est pas le but de la PR)
> COM-2583 - fix redirct to homepage on click

- src/core/helpers/vuelidateCustomVal.js
- src/modules/vendor/components/programs/ProfileContent.vue
- src/modules/vendor/mixins/templateMixin.js
Dans l'onglet "Sous programmes" d'une page programme, quand il y a 2 sous programmes, si j'enleve un des 2 titres, je n'ai l'erreur que sur un sous-programme
Sur la page d'édition d'une activité, pour une carte QCU/QCM/Texte a trou/QuestionReponse/Mettre dans l'ordre,
_ quand je crée la carte, je n'ai pas d'erreur
_ quand je remplis une des réponses, je vois "Champs requis" sous les autres champs
_ quand je vide une réponse requise, je vois l'erreur
> Com 2583 validations

- src/core/components/Button.vue
- src/core/components/table/CoachList.vue
- src/core/components/table/ExpandingTable.vue
- src/core/components/table/ResponsiveTable.vue
- src/core/components/table/SimpleTable.vue
- src/modules/client/components/customers/CustomerProfileHeader.vue
- src/modules/client/components/customers/ProfileFollowUp.vue
- src/modules/client/components/customers/infos/FundingCreationModal.vue
- src/modules/client/components/customers/infos/FundingEditionModal.vue
- src/modules/client/components/customers/infos/ProfileInfo.vue
- src/modules/client/components/planning/DeleteEventsModal.vue
- src/modules/client/mixins/planningModalMixin.js
- src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
- Périmetre interface : Venduer et client
- Périmetre roles : coach et rof
Sur le tableau des coachs, coté vendeur et coté client, je peux créer un coach :
_ pour une structure avec erp
_ pour une structure sans erp
_ le tableau des coachs est mis a jour a la fin - meme pour une structure avec plus de 15 coachs
> Com 2583 bugs

- src/modules/client/pages/ni/auxiliaries/AuxiliaryProfile.vue
- src/modules/client/pages/ni/customers/CustomerProfile.vue
- src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
- src/modules/vendor/pages/ni/pedagogy/ProgramProfile.vue
- src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue
- Périmetre interface : Vendeur / client
- Périmetre roles : Coach / Rof
Sur le profil d'un bénéficiaire, je n'ai plus le message d'alerte des onglets sur la reactivité + je peux changer d'onglet + quand je change le nom ou le prenom, le titre de la page est mis a jour
Sur le profil d'un programme, je n'ai plus le message d'alerte des onglets sur la reactivité + je peux changer d'onglet + quand je change le nom, le titre de la page est mis a jour
Sur le profil d'un questionnaire, je n'ai plus le message d'alerte des onglets sur la reactivité + je peux changer d'onglet + quand je change le nom, le titre de la page est mis a jour
Sur le profil d'un formation eLearning, je n'ai plus le message d'alerte des onglets sur la …
> Com 2583 reactivity 2

- src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
- Cas d'usage : sur la page d'une structure je n'ai plus de warning. 
Pour l'instant je n'ai fait que la page structure car je n'arrive pas a reproduire le warning sur la page des formations + la page des formations utilise "courseMixin" qui est utilisé à pas mal d'endroit et donc la refacto risque d'etre un peu grosse et donc pourrait etre fait dans une autre pr.
> COM-2641 migrate CompanyProfile to composition API

- src/core/components/courses/ProfileTraineeFollowUp.vue
Périmètre interfaces / rôles : vendeur - formateur/admin
Cas d'usage : modification du design
Comment tester ? : Verifier que le design convient + que la suppression de step n'a pas d'impact
> Com 2613 fix css

- src/core/data/constants.js
- Périmetre roles : rof/admin_vendeur
- Cas d'usage : je peux exporter les créneaux sur une période donnée
-Comment tester ? :
faire un export des créneaux et s'assurer pour 2-3 d'entres eux que les informations correspondent avec celles de la webapp.
+ boyscout pour Romain : dans les exports de formations ajout de l'avancement (nombre de créneaux passés sur nombre de créneaux total)
> COM-2619: add constants

- src/core/components/courses/ProfileTraineeFollowUp.vue
- Périmetre roles : admin-vendeur/rof/formateur
- Cas d'usage : déplacement de la section attestation de fin de formations pour être raccord au figma
> COM-2612: move attendances section

- src/modules/client/components/customers/infos/ProfileInfo.vue
- src/modules/client/components/customers/infos/SubscriptionCreationModal.vue
- src/modules/client/components/customers/infos/SubscriptionEditionModal.vue
- Périmetre roles : coach/admin_client
- Cas d'usage : je peux modifier le service quand je créé une souscription pour un bénéficiaire
> COM-2639: fix bug on select in susbcription creation modal

- src/core/components/courses/ElearningFollowUpTable.vue
- src/core/components/courses/ProfileFollowUp.vue
- src/core/components/learners/ProfileCourses.vue
- src/core/mixins/traineeFollowUpTableMixin.js
- Périmètre interfaces / rôles : vendeur/client admin_client/admin_vendeur/coach/rof/formateur
- Cas d'usage : la progression s'affiche correctement
pull dev et comparer qu'on a bien la même progression sur l'appli dev et sur cette branche : 
- progression eLearning sur une formation (côté vendeur et client)
- fiche formation : vue global et progression eLearning (côté vendeur)
> COM-2614: refacto progress

- src/modules/vendor/components/companies/ProfileInfo.vue
- Périmètre interfaces / rôles : vendeur / admin_vendeur/rof
- Cas d'usage : je peux voir et modifier l'adresse d'une structure
- Comment tester ? : modifier l'adresse d'une structure et s'assurer que le changement est aussi pris en compte côté client
> COM-2644: add address on company profile

- src/core/api/CourseFundingOrganisations.js
- src/core/helpers/rbac.js
- src/modules/vendor/mixins/menuItemsMixin.js
- src/modules/vendor/pages/ni/billing/BillingConfig.vue
- src/modules/vendor/router/routes.js
- Périmètre interfaces / rôles : interface vendeur / ROF
- ajout de la page Facturation > Configuration
- ajout d'un tableau des financeurs
-  remplir le tableau avec Postman (voir https://github.com/sophiemoustard/compani-api/pull/1800)
- verifier l'affichage
> COM-2645-1 add config page

- src/core/components/courses/SlotCreationModal.vue
- src/core/components/courses/SlotEditionModal.vue
- src/core/composables/learners.js
- src/modules/vendor/components/billing/CourseFundingOrganisationCreationModal.vue
- src/modules/vendor/pages/ni/billing/BillingConfig.vue
- Périmètre interfaces / rôles : vendeur / rof
- Cas d'usage : je peux ajouter un financeur sur la page de configuration de la factu (cote vendeur)
- Comment tester ? : ajouter un financeur
> Com 2645 2

- src/modules/client/composables/balance.js
- Périmètre interfaces / rôles : Client -> Admin / Aidant
- Cas d'usage : ETQ Admin ou aidant, quand je suis sur le page facturation de mon bénéficiaire je vois le bon montant pour la balance de début
_ Choisir un bénéficiaire
_ Regarder sa date de premiere intervention
_ Aller sur son onglet facturation
_ Choisir une date de debut de facturation avant la premiere intervention
_ Le montant initial doit etre 0
_ Regarder la date de la premiere facture
_ Changer la date du selecteur a date de la facture + 1 jour
_ Le montant initial doit etre egale au montant de la facture
Faire de meme coté aidant
> COM-2671 - fix customer balance

- src/core/api/CourseBillingItems.js
- src/modules/vendor/components/billing/CourseBillingItemCreationModal.vue
- src/modules/vendor/pages/ni/billing/BillingConfig.vue
- Périmètre interfaces / rôles : vendeur admin/rof
- Cas d'usage : je peux ajouter un article de facturation
- ajouter un article de facturation
- essayer de le réajouter => 409
> COM-2665: add billing item

- src/modules/client/components/customers/infos/ProfileInfo.vue
- Périmètre interfaces / rôles : coach
- Cas d'usage : lorsque je change l'iban/bic d'un beneficiaire, je peux telecharger le nouveau mandat
- Comment tester ? : Aller sur la page d'un beneficiaire. S'il n'a pas deja de bic/iban, les renseigner. Puis les modifier, cela doit generer un nouveau mandat et c'est celui-ci qui doit etre telechargeable (verifier une fois telecharger qu'il y a le bon bic/iban mais surtout le bon RUM) 
NB : j'ai essaye en meme temps de resoudre le bug de la date de signature, mais comme je n'ai pas trouve de solutions faciles et que je suis peu dispo en fin de semaine j'ai prefere ne pas y passer plus de temps. 
> COM-2678 condition on createdAt instead of index

- src/modules/client/pages/ni/config/CustomersConfig.vue
Correction d'un bug : 
Je ne peux plus ajouter / enlever / modifier les articles de facturations dans la création / l'édition des services. Le bug est présent en prod.
cf la description du ticket pour comprendre la solution
> COM-2687 - Fix bug for billing items in service creation and edition

- src/core/api/CourseBills.js
- src/core/components/courses/CourseBilling.vue
- src/modules/vendor/components/billing/CourseBillCreationModal.vue
- src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
- Cas d'usage : sur les formations intra : j'ai un onglet facturation dans lequel je peux ajouter une facture (prix + payeur)
- Comment tester ? : créer une facture dans une formation intra (avec financeur (= payeur autre que structure) et sans (= payeur = structure)
> COM-2696: add facturation tab

- src/core/components/table/ExpandingTable.vue
- Périmètre interfaces / rôles : ROF / Coach
- Cas d'usage : Si un apprenant est inscrit a plus de 15 formations, je les vois toutes sur sa fiche
- Comment tester ? : aller voir sur la fiche de 6194ab9790d8d50016b1aa58 ou inscrire un apprenant a 16 formations et valider qu'on les voit toutes sur sa fiche
> COM-2712 - add pagination to ExpandingTable component

- src/core/api/CourseBills.js
- src/core/components/courses/CourseBilling.vue
- src/modules/vendor/components/billing/FunderEditionModal.vue
- Cas d'usage : je peux éditer le payeur d'une facture
- Comment tester ? : éditer le payeur d'une facture : 
- avec un financeur (champ courseFundingOrganisation créé/modifié en base)
- avec la structure de la formation (champ courseFundingOrganisation supprimé en base)
> COM-2697: edit funder

- src/modules/client/components/config/BillingItemCreationModal.vue
- src/modules/client/components/config/ThirdPartyPayerCreationModal.vue
- src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
- src/modules/client/pages/ni/config/CustomersConfig.vue
- src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue
- src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue
- src/modules/vendor/components/billing/CourseBillingItemCreationModal.vue
- src/modules/vendor/components/billing/CourseFundingOrganisationCreationModal.vue
- src/modules/vendor/components/companies/ProfileInfo.vue
- Périmètre interfaces / rôles : compani-outils et formation / coach et rof
- la verification de la création de doublon est insensisble a la casse pour
- coté client : les articles de factu client, les tiers payeurs, les organisations partenaires
- cote vendeur : les structures, les Organisme de financement, les articles de factu formations
-  def : j'appelle "noms semblables" des noms identiques si on est insensible a la casse ex: "Test", "TEST" et "Têst" sont semblables
- article de factu client
- je ne peux pas créer un article de factu client avec un nom semblable a un autre existant dans ma structure
- je peux créer un article de factu client avec un nom semblable a un autre existant dans une autre structure
- il n'y a pas d'espace avant et apres …
> COM-2701 .trim

- src/core/components/courses/CourseBilling.vue
- Cas d'usage : j'ai un chevron qui m'indique que je peux déplier la facture
- Comment tester ? : lorsque je clique sur l'entête de la facture et qu'il se déplie, le chevron se retourne et inversement
> COM-2704: add chevron

- src/core/components/courses/CourseBilling.vue
- src/modules/vendor/components/billing/CourseBillValidationModal.vue
- Cas d'usage : je peux valider une facture
- créer une facture
- la valider : 
- la mention "à facturer" est remplacer par le n° de la facture
- le bouton pour facturer disparait
- la date de la facture apparait
- faire la même chose avec une seconde facture : 
- le n° de facture est incrémenté par rapport à la première
- exporter les formations : j'ai bien l'info comme quoi les factures ont été facturées  
> COM-2730: validate bill

- src/core/api/CourseBills.js
- src/core/components/courses/CourseBilling.vue
- src/modules/vendor/components/billing/BillingPurchaseAdditionModal.vue
- src/modules/vendor/components/billing/CourseFeeAdditionModal.vue
- Cas d'usage : renommage de billingitemList => billingPurchase et conséquences
- créer une facture avec des articles et la valider : tout marche 
> COM-2738: refacto to change item in purchase

- src/modules/client/pages/ni/exports/HistoryExports.vue
- Périmètre interfaces / rôles : client / admin - coach
Dans l'export d'interventions (et autres export d'historique), je peux exporter sur une durée de 1an et pas 1an - 1jour
Faire du 1er janvier au 31 décembre -> sur dev erreur, sur ma branche pas d'erreur
> COM-2740 - mini fix for exports

- src/core/api/CourseBills.js
- src/core/components/courses/CourseBilling.vue
- Cas d'usage : je peux télécharger une facture une fois validée
- valider une facture avec des articles de facturation
- la télécharger et s'assurer  qu'elle s'affiche et qu'elle contient les bonnes infos
- faire de même avec une facture sans articles de facturation
> COM-2732: add download button

- src/modules/client/mixins/subscriptionMixin.js
- Périmètre interfaces / rôles : coach
- Cas d'usage : les articles de facturation sont pris en compte dans les montants figurant dans les devis.
- Dans configuration beneficiaire: ajouter le nouveau devis
- Sur la fiche d'un beneficiaire:
- creer plusieurs souscriptions : horaire, forfaitaire, horaire avec articles de facturation, avec des samedis, des dimanches et des soirées
- generer un devis
- le télécharger et verifier que les informations sont bonnes 
> COM-2742 - add billingItems rate in weeklyRate calculation

- src/core/api/VendorCompanies.js
- src/core/composables/validations.js
- src/modules/vendor/pages/ni/billing/BillingConfig.vue
- Cas d'usage : je peux mettre à jour les infos de factu de Compani
- Comment tester ? : changer nom, adresse et siret de company, tester les validations
> COM-2760: can update vendor company

- src/core/components/courses/CourseBilling.vue
- src/core/data/constants.js
- src/modules/vendor/components/companies/ProfileBilling.vue
- src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
- Cas d'usage : je peux visualiser et télécharger les factures depuis la fiche d'une structure
- facturer une formation à une structure : s'assurer qu'elle s'affiche bien sur le profil de la formation (qu'on a pas cassé la route préexistante
- se rendre sur le profil d'une structure et s'assurer qu'on a bien la facture (si elle est validée) et qu'on peut la télécharger 
> COM-2754: display bills on company profile

- src/modules/client/pages/ni/config/CompanyConfig.vue
- src/modules/vendor/components/companies/CompanyCreationModal.vue
- src/modules/vendor/components/companies/ProfileInfo.vue
- src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
- Cas d'usage : quand je crée une structure, je n'ai pas besoin de préciser si c'est une entreprise ou une association
- créer une structure => je n'ai pas à préciser son type
- se rendre sur le profil de la structure => elle n'a pas de type
- lui ajouter un type => le changement est pris en compte
- je peux rechanger son type
> COM-2756: move type definition for companies

- src/core/components/courses/CourseBilling.vue
- Périmètre interfaces / rôles : vendeur / rof
- Cas d'usage : ouvrir la facture dans une nouvelle tab
- Comment tester ? : verifier
> COM-2753-2 open in new tab

- src/modules/vendor/components/companies/ProfileBilling.vue
- Cas d'usage : changement de la couleur du programme dans le tableau de l'onglet facturation sur le profil structure
- Comment tester ? : ⬆️ 
> COM-2754: change program name color

- src/core/api/CoursePayments.js
- src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
- Cas d'usage : je peux ajouter des règlements à une facture
- sur une facture sur la fiche d'une structure ajouter un paiement et un remboursement
- dérouler le détail de la facture avec les différents règlements affichés
> COM-2755: can add payment

- src/core/api/CourseCreditNotes.js
- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
- src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
- Périmètre interfaces / rôles : formation / rof
- je peux annuler une facture par avoir
- une fois la facture annulée: je ne peux pas re-créer d'avoir, le titre de la carte facture indique l'annulation, je peux créer d'autre facture
-  ajouter un avoir
- verifier que la deuxieme partie du titre (en orange) apparait
- je peux créer une nouvelle facture
-  en modifiant le code, rendre visible le bouton "faire un avoir"
- tester de créer un autre avoir => 403
- tester de créer un avoir sur un brouillon de facture -=> 403
> COM-2772 add credit notes

- src/core/api/CoursePayments.js
- src/modules/vendor/components/billing/CoursePaymentEditionModal.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
- Cas d'usage : je peux éditer un règlement sur une facture
- Comment tester ? : éditer un règlement existant sur une facture
> COM-2771: can edit payment

- src/modules/vendor/components/companies/ProfileBilling.vue
- src/modules/vendor/router/routes.js
- Cas d'usage : je peux accéder à l'onglet facturation d'une formation en cliquant sur le nom de cette formation depuis l'onglet facturation d'une structure
- Comment tester ? : dans l'onglet facturation d'une structure cliquer sur le nom d'une formation dans le tableau des factures => je suis redirigé verse la fiche de cette formation, onglet facturation
> COM-2791: redirect to course profile (billing) when click on course name

- src/core/pages/signin/Authenticate.vue
- src/core/pages/signin/ForgotPassword.vue
- Périmètre interfaces / rôles : tous
- Cas d'usage : quand je rentre un espace en trop dans mon mail à l'authentification / mdp oublié celui-ci n'est pas pris en compte
- Comment tester ? : se connecter / mdp oublié en rentrant un espace en trop dans son mail
> COM-2786: add trim to authenticate and forgot password

- package-lock.json
- package.json
- src/core/helpers/numbers.js
- src/core/helpers/utils.js
- src/modules/client/components/table/ToBillRow.vue
- src/modules/client/pages/ni/billing/ToBill.vue
- Périmètre interfaces / rôles : Admin client
- Cas d'usage : sur la page a facturer, les montants affichés sont bons. 
- On peut faire le test suivant: 
- créer un bénéficiaire avec une souscription a 25.45 euros TTC (utiliser un service avec un article de facturation / intervention de 2 euros TTC)
- Lui créer 4 interventions :
- 16h04 - 17h54
- 15h38 - 17h17
- 13h33 - 15h01
- 9h50 - 11h11
- Aller sur la page a facturer
- Cas de test:
- si la PR COM-2805 est fusionnée, se placer sur la branche `features-big-number-bills` en back
- verifier que le montant total affiché est 168,34 (c'est le meme que si on se place sur la branche `features-big-number-bills` en front )
- ajouter des remises et verifier que les montants affichés sont encore corrects
- sinon se placer sur …
> COM-2808 - uses cents to calculate

- src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
- Cas d'usage : ajout de "(visible pour les clients)" dans la modale de création d'avoir (côté formation)
- Comment tester ? : créer un avoir
> COM-2772: change caption

- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/billing/CourseBillCreationModal.vue
- Cas d'usage : renommage du champ prix dans la modale de création d'une facture + déroulement des détails de la facture nouvellement créé
- Comment tester ? : créer une nouvelle facture => elle se déplie 
> COM-2790: change caption and show last bill details

- src/core/components/courses/BlendedCourseProfileHeader.vue
- src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
- Périmètre interfaces / rôles : ROF
- Cas d'usage : Je ne peux pas supprimer une formation qui a été facturée
Créer une formation, la facturer, la supprimer -> erreur
Créer une formation, créer une facture mais ne pas la valider, la supprimer => c'est ok et la facture est supprimée
> COM-2835 - Specific 403 message

- src/core/components/courses/SlotContainer.vue
- src/core/components/courses/SlotEditionModal.vue
- Périmètre interfaces / rôles : client/vendeur coach/rof/formateur
- Cas d'usage : je peux éditer les créneaux dans une étape
- je peux mettre à jour les horaires/adresse/lien des créneaux présentiels et distanciels
- je ne peux plus modifier l'étape d'un créneau (postman) 
> COM-2825: remove select to update step

- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/billing/CourseBillCreationModal.vue
- src/modules/vendor/components/billing/PayerEditionModal.vue
- Cas d'usage : je peux facturer et exporter les formations normalement
- créer un organisme de financement sur la branche dev
- faire tourner le script
- s'assurer que les factures existantes s'affichent et se téléchargent bien 
- créer une facture avec la structure comme payeur
- éditer le payeur
- valider la facture et la télécharger => le payeur s'affiche correctement
- faire un avoir sur la facture et le télécharger => le payeur s'affiche correctement
- créer une facture avec un organisme de financement comme payeur
- éditer le payeur
- valider la facture et la télécharger => le payeur s'affiche correctement
- exporter les formations => le payeur s'affiche correctement
- afficher la liste des factures d'une …
> COM-2853: refacto payer

- src/modules/vendor/components/companies/ProfileBilling.vue
- Cas d'usage : sur l'onglet facturation sur le profil d'une structure les formations sont classées par payeur
- Comment tester ?
- facturer une formation d'une structure A à la structure A (1)
- facturer une formation d'une structure A à la structure B (2)
- facturer un formation d'une structure B à la structure A (3)
- sur l'onglet factu de la structure A on a 2 tableaux : 
- les factures payées par A (1 et 3)
- les facutres payées par B (2)
> COM-2813: display bills by payer

- src/modules/client/pages/ni/config/RhConfig.vue
- Périmètre interfaces / rôles : client admin
- Cas d'usage : je peux paramétrer la comptabilité des jours fériés dans les heures travaillées. Nouveau design suite au retour de Romain: `Juste petite remarque niveau design : je ne reconnais pas quelque chose existant ailleurs sur la webapp, peux-tu utiliser le même design que “validation en ligne des souscription” dans l’onglet “info” d’une fiche bénéficiaire ?`
- vérifier que la checkbox fonctionne:
- si cochée en bdd `shouldPayHolidays` vaut true
- si décochée en bdd `shouldPayHolidays` vaut false
> COM-2861 - fix Romain's reviews

- src/modules/vendor/components/billing/CourseFundingOrganisationCreationModal.vue
- src/modules/vendor/pages/ni/billing/BillingConfig.vue
- Périmètre interfaces / rôles : vendeur/ rof/admin
- Cas d'usage : l'adresse des financeurs est désormais une chaîne de caractères
- s'assurer qu'on a déjà un financeur A sur la branche dev et qu'il est utilisé dans une facture validée + avoir
- faire tourner le script et se mettre sur cette branche
-  dans l'onglet facturation le financeur A s'affiche correctement
- créer un financeur B et l'utiliser comme payeur d'une facture qu'on valide + avoir
- je peux télécharger une facture payée par une structure/ payée par le financeur A/ payer par le financeur B
> COM-2844: refacto address

- test/cypress/integration/customer/subscription.spec.js
- Cas d'usage : les tests end2end passent tous
- Comment tester ? : lancer les tests end2end
> COM-2889 - fix tests

- src/core/components/courses/InterlocutorCell.vue
- src/core/components/courses/InterlocutorModal.vue
- src/core/components/courses/ProfileOrganization.vue
- src/core/helpers/ability.js
- Périmètre interfaces / rôles : client/vendeur rof/admin/coach
- Cas d'usage : refacto design du référent Compani sur une formation
- sur une formation j'ai le nouveau design du référent compani
- je peux l'éditer soit via son nom soit via son mail (dans la modale)
- je ne peux l'éditer que depuis le côté vendeur 
> COM-2847: refacto sales representative

- src/core/data/constants.js
- Cas d'usage : je peux exporter les factures et les avoirs côté formation
- créer des factures :
-  non validées
- validées sans paiements
- validées avec paiements
- validées avec avoir
- s'assurer qu'elles apparaissent bien sur l'export (les factures non validées ne doivent pas apparaitre)
- s'assurer que le temps de téléchargement est ok
> COM-2842: add constant

- src/core/components/courses/InterlocutorCell.vue
- src/core/components/courses/InterlocutorModal.vue
- src/core/components/courses/ProfileOrganization.vue
- Périmètre interfaces / rôles : vendeur/client rof/admin/coach
- Cas d'usage : refacto de la section intervenant sur le profil d'une formation
- ETQ ROF : je peux ajouter un formateur à une formation et je peux l'éditer si la formation n'est pas archivée
- ETQ  coach : je peux visualiser le formateur sur le profil de la formation
> COM-2815: display trainer infos

- src/core/data/constants.js
- src/core/helpers/date.js
- src/modules/client/components/planning/EventCancellationModal.vue
- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/mixins/planningActionMixin.js
- Périmètre interfaces / rôles : client coach/aux/admin
- Cas d'usage : je peux rétablir une intervention annulée
- annuler une intervention
- changer les conditions d'annulation / personne à l'initiative
- restaurer l'intervention 
> COM-2821: can restore event

- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/router/routes.js
- Cas d'usage : depuis l'onglet factu d'une formation je peux accéder à l'onglet factu d'une structure
- depuis l'onglet factu d'une formation aller sur l'onglet factu de la structure puis faire retour arrière => je reviens sur l'onglet factu de la formation 
> COM-2845: redirection to company profile

- src/core/components/courses/InterlocutorCell.vue
- src/core/components/courses/InterlocutorModal.vue
- src/core/components/courses/ProfileOrganization.vue
- src/store/course.js
- Périmètre interfaces / rôles : client/vendeur rof/admin/coach
- Cas d'usage : je peux ajouter et éditer un représentant structure + boyscout : vérification dans le prehandler que le formateur et le representant compani existent et ont bien le bon rôle + vérification que j'ai le droit de les éditer
- sur une formation intra je peux ajouter et éditer un représentant structure côté client et vendeur
- sur une formation inter je ne peux pas ajouter de représentant structure
> COM-2916: i can add company representative to course

- src/modules/client/components/planning/RepetitionCell.vue
- src/modules/client/components/planning/RepetitionDeletionConfirmationModal.vue
- src/modules/client/components/planning/RepetitionDeletionModal.vue
- src/modules/client/pages/ni/planning/RepetitionsPlanning.vue
- Périmètre interfaces / rôles :  ETQ client admin, coach ou planning referenet 
- Cas d'usage : Les conflits sont visibles sur la page répétition
- Comment tester ? : afficher les repetitions de plusieurs auxiliaires et verifier que les conflits s'affichent correctement 
> COM-2909 - display conflicts

- src/core/data/constants.js
- Périmètre interfaces / rôles : vendeur rof 
- Cas d'usage : Je peux telecharger un export paiement et remboursement 
- Comment tester ? : cf cas d'usage 
> COM-2954 add course payment export

- src/modules/client/pages/ni/billing/Bills.vue
- Périmètre interfaces / rôles : ETQ administrateur
- Cas d'usage : Je peux voir la liste des factures.  Vérifier que l'on peut trier les colonnes et que l'on est redirigé vers la fiche bénéficiaire. (nouveau design)
- afficher les factures sur une période
- verifier que le tri fonctionne sur toutes les colonnnes
- verifier que la navigation vers la fiche beneficiaire fonctionne 
- verifier que le téléchargement des factures fonctionne 
> Com 2896 fix

- src/modules/client/pages/ni/billing/Bills.vue
- Périmètre interfaces / rôles : client admin
- Cas d'usage : Je peux trier la premiere colonne sur la page liste des factures
- Comment tester ? : cf cas d'usage
> COM-2896 add sort

- package-lock.json
- package.json
- src/core/components/table/EditableTd.vue
- src/core/helpers/numbers.js
- src/core/helpers/utils.js
- src/core/helpers/vuelidateCustomVal.js
- src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
- src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
- src/modules/client/components/customers/billing/ManualBillCreationModal.vue
- src/modules/client/components/table/ToBillRow.vue
- src/modules/client/mixins/configMixin.js
- src/modules/client/pages/ni/billing/CreditNotes.vue
- src/modules/client/pages/ni/billing/ManualBills.vue
- src/modules/client/pages/ni/billing/ToBill.vue
- src/modules/client/pages/ni/billing/TppBillSlips.vue
- src/modules/client/pages/ni/config/CustomersConfig.vue
> MES - BN - 28/07/2022

- src/core/components/courses/CourseCell.vue
- src/core/components/courses/ElearningFollowUpTable.vue
- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TraineeTable.vue
- src/core/composables/courses.js
- src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
- src/modules/vendor/components/programs/StepAdditionModal.vue
- src/modules/vendor/components/programs/TesterTable.vue
- src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
- Périmètre interfaces / rôles : client / vendeur rof/coach/admin
- Cas d'usage : je peux accéder au profil d'une formation mixte + je peux ajouter des testeurs
- Comment tester ? : côté vendeur et côté client : toutes les fonctionnalités de l'onglet Organisation d'une formation fonctionnent + je peux naviguer entre les 3 onglets + sur le catalogue des programmes je peux ajouter des testeurs au programme
> Com 2927 2

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TraineeTable.vue
- Périmètre interfaces / rôles : vendeur/client rof/coach/admin
- Cas d'usage : côté vendeur je peux modifier le nombre max de stagiaires, côté client je peux le visualiser
- Comment tester ? : sur une formation intra modifier le nombre de stagiaires : 
- sup ou égal au nombre d'inscrits ✔️ 
- inf au nombre d'inscrits 🚫 
- si je ne mets pas un entier positif => validation
- je peux le visualiser côté client
> COM-2982: can edit max trainees

- src/core/api/Courses.js
- src/core/data/constants.js
- Périmètre interfaces / rôles : etq vendor_admin, coach et formateur.ice
- refacto de la route appelé pour recuperer la liste des formations `GET /course`
- verifier toutes les anciennes utilisations de cette route
- le trello blended pour admin
- la liste elearning pour admin
- le trello blended pour coach 
- la liste elearning pour coach
- le trello pour formateur.ice 
> COM-2975 add params

- src/core/helpers/utils.js
- Périmètre interfaces / rôles : coach/admin
- Cas d'usage : lorsque je modifie un iban d'une auxiliaire puis que je crée une nouvelle auxiliaire, l'IBAN de celle-ci est bien vierge
- Comment tester ? : modifier l'iBAN d'une auxiliaire puis en créer une nouvelle => elle n'a pas d'IBAN
> COM-3005: edit copy rather than original model

- src/core/helpers/dates/luxon.js
- [] J'ai vérifié la fonctionnalité sur mobile -np
- Périmètre interfaces / rôles : vendeur/client trainer/rof/admin/coach
- Cas d'usage : suppression de la timezone luxon
- faire tourner les tests end2end en local 
- Tester que les endroits ou on utilise luxon en webapp fonctionne bien 
- affichage du bouton d'archivage seulement si tous les creneaux sont passés dans une formation mixte
- Verifier des dateRange (ex : exports)
- Verifier des dateInput (ex : televersement des fiches de paie)
- Verifier des dateTimeRange (ex : planning)
> Com 3006 2

- src/core/api/Courses.js
- Périmètre interfaces / rôles : etq admin / etq coach / etq formateur
- je peux toujours consulter la page d'une fomation
- verifier que tous s'affiche bien
- sur les trois onglets : les stagiaires, les crenaux, les factures, les emargements
- avec les trois roles : admin, coach, formateur 
> COM-2977 add origin: WEBAPP to request GET /courses/{id}

- .github/pull_request_template.md
- src/core/components/form/DatetimeRange.vue
- src/modules/client/mixins/planningActionMixin.js
> COM-3229 set second and millis to 0

- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-3239 - replace company by companies

- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/components/learners/ProfileCourses.vue
- src/core/data/constants.js
- src/core/helpers/date.js
- src/core/helpers/dates/companiDates.js
- src/core/helpers/dates/companiDurations.js
- src/core/helpers/dates/luxon.js
- src/core/helpers/dates/utils.js
> COM-3237: replace getTotalDuration with luxon

- src/core/components/courses/AttendanceSheetAdditionModal.vue
- src/core/components/courses/CourseHistory.vue
- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/SlotContainer.vue
- src/core/components/form/DateInput.vue
- src/core/components/table/AttendanceTable.vue
- src/core/components/table/TraineeAttendanceCreationModal.vue
- src/core/data/constants.js
- src/modules/client/components/planning/EventCreationModal.vue
> COM-3234 use constants for format

- src/core/components/courses/SlotContainer.vue
> COM-3244 remove moment from SlotContainer

- src/core/components/courses/CourseCell.vue
- src/core/helpers/courses.js
- src/core/helpers/dates/companiDurations.js
- src/core/helpers/dates/utils.js
> COM-3243 : remove moment from CourseCell

- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/components/courses/SlotContainer.vue
- src/core/components/courses/SlotEditionModal.vue
- src/core/components/learners/ProfileCourses.vue
- src/core/helpers/courses.js
- src/core/helpers/date.js
- src/core/helpers/dates/utils.js
> COM-3230: remove formatIntervalHourly, getDuration & formatDuration

- src/core/components/courses/ProfileBilling.vue
- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TraineeTable.vue
- src/core/components/table/AttendanceTable.vue
- src/core/helpers/courses.js
- src/core/helpers/utils.js
- src/core/mixins/courseFiltersMixin.js
- src/modules/vendor/components/companies/ProfileBilling.vue
Fusion de la branche `feature-refacto-company-course-link` dans `dev` apres avoir effectué les tests suivant: https://www.notion.so/compani/Refonte-lien-structure-Formation-Formations-INTRA-0c54a26893b04b38b6b8fb382ce1f072#e7889c1cafe040598ca2acf4f892392e
> Merge Feature-refacto-company-course-link in dev

- src/core/components/form/TimeInput.vue
- src/core/helpers/dates/companiIntervals.js
- src/core/helpers/dates/luxon.js
> COM-3232 add companiInterval + refacto TimeInput

- src/core/mixins/courseFiltersMixin.js
> COM-3260 add companiDate to courseFilterMixin

- src/core/components/courses/ProfileBilling.vue
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/components/courses/SmsCell.vue
- src/core/components/learners/ProfileCourses.vue
- src/core/components/table/AttendanceTable.vue
- src/core/mixins/eLearningCourseDirectoryMixin.js
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
- src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
> COM-3245 remove use of moment methods in helpers dates for formation

- src/core/helpers/dates/companiDurations.js
- src/core/mixins/courseTimeline.js
> COM-3247 refacto CourseTimeline

- src/core/helpers/dates/utils.js
> COM-3242: add isSame to sort

- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
> COM-3278 handler expectedBillsCount in intra course billing

- src/core/components/courses/ProfileBilling.vue
- src/core/components/courses/ProfileOrganization.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/components/courses/CourseCreationModal.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> Feature many bills

- src/core/mixins/courseFiltersMixin.js
> COM-3286: refacto kanban filter

- src/core/api/Courses.js
- src/core/components/courses/CompanyTable.vue
- src/core/components/courses/CourseHistory.vue
- src/core/composables/companiesCoursesLink.js
- src/core/data/constants.js
> COM-3274: can delete company from course

- src/core/components/courses/CourseHistory.vue
- src/core/data/constants.js
> COM-3294 show course history for estimatedStartDate init

- src/core/components/learners/ProfileCourses.vue
> COM-3291 remove formatDuration and use ISO format

- src/core/components/courses/CourseHistory.vue
> COM-3295 add history edition msg

- src/core/components/courses/CourseHistory.vue
> COM-3303 show history if date and hour are updated

- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-3264: can display bills

- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-3305 sort bills

- src/core/components/courses/CompanyTable.vue
> COM-3313: block company deletion for trainer

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/SlotContainer.vue
- src/core/components/courses/TraineeTable.vue
> COM-3317 estimatedStartDate : send update request only on blur

- src/core/components/courses/CourseHistory.vue
- src/core/data/constants.js
> COM-3235 add year in history messages

- src/core/components/courses/CourseCell.vue
- src/core/components/courses/CourseContainer.vue
> COM-3334 - add keyboard shortcut to open a new tab

- src/core/components/table/AttendanceTable.vue
> COM-3328: fix map and filter

- src/core/composables/companyDetachment.js
- src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
> COM-3336: redirection

- .github/workflows/endToEnd.js.yml
> COM-3347 - update github action mongodb version

- src/core/helpers/userCompanies.js
- src/modules/client/pages/ni/auxiliaries/Directory.vue
- src/store/userProfile.js
> COM-3365: can add auxiliary in the future

- .github/workflows/endToEnd.js.yml
- quasar.conf.js
- src/core/api/UserCompanies.js
- src/core/components/courses/TraineeContainer.vue
- src/core/components/learners/CompanyDetachModal.vue
- src/core/components/learners/ProfileCourses.vue
- src/core/components/table/CoachList.vue
- src/core/composables/companyDetachment.js
- src/core/composables/learners.js
- src/core/helpers/userCompanies.js
- src/modules/client/mixins/helperMixin.js
- src/modules/client/pages/ni/auxiliaries/Directory.vue
- src/modules/client/pages/ni/courses/LearnerProfile.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
- src/store/course.js
- src/store/userProfile.js
Fusion de la branche feature du projet Détacher un compte apprenant (sans rôle) d'une structure (hors-ERP)
> Feature detachment

- src/core/mixins/courseFiltersMixin.js
- src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
- src/store/course.js
> COM-3372 add filter on kanban : no address

- src/modules/client/router/routes.js
- src/modules/vendor/router/routes.js
> COM-3376 return back to traineeFollowUp

- src/core/components/courses/SlotContainer.vue
> COM-3382 - display error

- src/core/composables/courseFilters.js
- src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
- src/store/course.js
> COM-3373-2 add full course filter

- src/core/components/table/AttendanceTable.vue
> COM-3379: array is not sorted again when new attendances

- src/core/components/table/AttendanceTable.vue
> COM-3333: use company field rather than trainee field

- src/core/components/form/DatetimeRange.vue
> COM-3396 fix date time range

- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
> COM-3388 change filter

- src/core/components/table/AttendanceTable.vue
> COM-3400: add border and hide checkbox if no trainees

- src/core/helpers/userCompanies.js
> COM-3394 only return once the company in getCurrentAndFutureCompanies

- src/core/components/courses/LearnerCreationModal.vue
- src/core/composables/learners.js
> COM-3404: disable required on phone when future trainee coach side

- src/core/helpers/userCompanies.js
> COm-3414 fix getCurrentAndFutureCompanies

- src/store/userProfile.js
> COM-3421 route to 404 when user is not in the company anymore

- src/core/api/Courses.js
- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TrainingContractContainer.vue
- src/core/components/courses/TrainingContractInfosModal.vue
- src/core/components/courses/TrainingContractPriceAdditionModal.vue
- src/core/helpers/utils.js
> COM-3416: can generate contract

- src/core/components/table/AttendanceTable/index.vue
- src/core/components/table/SimpleTable.vue
> COM-3422 fix pasgination on attendancesheet table

- src/core/components/courses/TraineeContainer.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/store/course.js
> COM-3415 rename company to registrationcompany

- src/core/components/courses/ElearningFollowUpTable.vue
- src/core/components/courses/TraineeContainer.vue
- src/core/components/courses/TraineeTable.vue
- src/core/components/table/AttendanceTable/Composables/Attendances.js
- src/core/components/table/AttendanceTable/index.vue
- src/core/composables/learnersCreation.js
- src/core/composables/learnersEdition.js
- src/core/composables/traineeFollowUp.js
- src/modules/client/pages/ni/courses/LearnersDirectory.vue
- src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
> Com 3415 fix bug

- src/core/api/TrainingContracts.js
- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/components/courses/TrainingContractContainer.vue
- src/core/components/form/FileUploader.vue
> COM-3419: can download training contract

- src/core/api/TrainingContracts.js
- src/core/components/courses/TrainingContractContainer.vue
> COM-3420: can delete training contract

- src/modules/vendor/pages/ni/billing/BillingConfig.vue
> COM-3426: can display and update activity declaration number

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/SlotContainer.vue
- src/core/components/courses/SlotEditionModal.vue
- src/core/components/courses/TrainingContractContainer.vue
> COM-3424: fix bug + rename variable + button is activate when missing infos

- src/core/components/courses/TrainingContractTable.vue
- src/core/components/form/FileUploader.vue
> COM-3439: disable delete and download icons when no link

- src/core/components/courses/CourseCell/ForthcomingSection.vue
- src/core/components/courses/CourseCell/InProgressSection.vue
- src/core/components/courses/CourseCell/index.vue
- src/css/course.sass
> COM-3441: refacto coursecell

- src/core/components/courses/TrainingContractContainer.vue
- src/core/components/form/FileUploader.vue
> COM-3453: empty uploader for media

- src/core/components/courses/Trello.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> COM-3464 - reset completedCourseList on refresh

- .github/workflows/endToEnd.js.yml
> COM-3447 - update mongo version in test workflow

- src/core/api/Companies.js
- src/core/api/Holdings.js
- src/core/components/table/ResponsiveTable.vue
- src/core/helpers/rbac.js
- src/modules/vendor/components/holdings/ProfileInfo.vue
- src/modules/vendor/pages/ni/users/holdings/HoldingProfile.vue
- src/modules/vendor/pages/ni/users/holdings/HoldingsDirectory.vue
- src/modules/vendor/router/routes.js
- src/modules/vendor/store/holding.js
- src/store/index.js
> COM-3461: display holding profile

- package-lock.json
- package.json
- test/cypress/integration/auxiliary/planning/auxiliaryAgenda.spec.js
- test/cypress/integration/ni/billing/toBill.spec.js
- test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
> COM-3470 update quasar

- src/core/components/courses/ProfileOrganization.vue
> COM-3474 fix tmpCourse initialization on ProfileOrganization

- src/core/components/courses/TraineeContainer.vue
- src/core/helpers/utils.js
- src/store/course.js
> COM-3476: can see holding learners on course

- src/core/components/courses/ProfileFollowUp.vue
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/composables/traineeFollowUp.js
- src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
> COM-3479: display learners follow up

- src/core/components/courses/CourseCell/index.vue
- src/core/composables/courseFilters.js
- src/core/data/constants.js
- src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
- src/store/course.js
> COM-3491: refacto filter

- src/core/components/courses/ProfileOrganization.vue
> COM-3487: get learner list

- src/core/components/courses/ElearningFollowUpTable.vue
- src/core/components/courses/TraineeTable.vue
- src/core/components/table/AttendanceTable/index.vue
- src/core/composables/learnersEdition.js
- src/core/helpers/userCompanies.js
- src/core/helpers/utils.js
- src/store/course.js
> COM-3480: can edit trainee

- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
- src/core/components/table/AttendanceTable/Composables/Attendances.js
> COM-3486: can see attendances and attendance sheets

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TrainingContractContainer.vue
- src/core/components/courses/TrainingContractCreationModal.vue
- src/core/components/courses/TrainingContractTable.vue
> COM-3482: display training contracts for holding roles

- src/core/components/courses/ElearningFollowUpTable.vue
- src/core/components/courses/TraineeTable.vue
- src/core/components/table/AttendanceTable/index.vue
- src/core/composables/learnersEdition.js
> COM-3484: can't access other company user profile

- src/core/components/courses/TrainingContractContainer.vue
> COM-3502: rename downloaded file

- src/store/userProfile.js
> COM-3510: can access user

- src/modules/client/pages/ni/courses/ContactProfile.vue
> COM-3500 - display billingRepresentative on ContactProfile

- src/modules/client/mixins/configMixin.js
- src/modules/client/pages/ni/config/CompanyConfig.vue
> COM-3505 - can define billing representative of my company

- src/modules/client/mixins/configMixin.js
- src/modules/client/pages/ni/config/CompanyConfig.vue
> COM-3505 - fix validation bug

- src/core/components/courses/InterlocutorCell.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-3504 - can define billing representative on company's profile

- src/core/components/table/AttendanceTable/Composables/Attendances.js
> COM-3509: get trainees from course

- src/store/course.js
> COM-3445 - fix bug

- src/modules/vendor/components/programs/ProfileContent.vue
> COM-3386: display activities count on elearning step only

- src/modules/vendor/components/programs/cards/CardCreationModal.vue
- src/modules/vendor/components/questionnaires/ProfileEdition.vue
> COM-3521 - restrictive questionnnaire card templates

- src/css/app.sass
- src/modules/client/pages/ni/courses/LearnersDirectory.vue
- src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
> COM-3536: open learner in new tab

- src/core/components/courses/BlendedCourseProfileHeader.vue
- src/core/components/form/FileUploader.vue
> COM-3538: can archive and unarchive course easily

- src/modules/vendor/components/courses/CourseCreationModal.vue
> COM-3535: block non blended published subprograms

- src/core/components/table/TableList.vue
- src/core/composables/learnersCreation.js
- src/css/app.sass
- src/modules/client/pages/auxiliaries/customers/AuxiliaryCustomersDirectory.vue
- src/modules/client/pages/ni/auxiliaries/Directory.vue
- src/modules/client/pages/ni/courses/ELearningCoursesDirectory.vue
- src/modules/client/pages/ni/courses/LearnersDirectory.vue
- src/modules/client/pages/ni/customers/CustomersDirectory.vue
- src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue
- src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue
- src/modules/vendor/pages/ni/pedagogy/ProgramsDirectory.vue
- src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
- src/modules/vendor/pages/ni/users/holdings/HoldingsDirectory.vue
- src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
- src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> COM-3536: can cmd click for every directory

- src/core/components/courses/ProfileOrganization.vue
> COM-3539: holding admin as company representative

- src/core/components/questionnaires/cards/CardTemplate.vue
- src/core/components/questionnaires/cards/End.vue
- src/core/components/questionnaires/cards/Footer.vue
- src/core/components/questionnaires/cards/OpenQuestion.vue
- src/core/components/questionnaires/cards/Start.vue
- src/modules/notLogged/pages/QuestionnaireForm.vue
- src/modules/vendor/store/questionnaire.js
> Com 3526 rebase

- src/core/components/courses/ProfileOrganization.vue
- src/core/data/constants.js
- src/core/helpers/ability.js
> COM-3559: can update company representative

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TraineeContainer.vue
- src/core/composables/companiesCoursesLink.js
- src/core/helpers/ability.js
- src/modules/vendor/components/holdings/ProfileInfo.vue
> COM-3554: can add company

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TraineeContainer.vue
- src/core/components/courses/TraineeTable.vue
- src/core/helpers/ability.js
> COM-3556: can add trainee

- src/core/components/form/DateInput.vue
- src/core/components/form/DateRange.vue
- src/modules/client/pages/ni/billing/ToBill.vue
- test/cypress/integration/ni/billing/toBill.spec.js
> COM-3574 - fix blur trigger on date input icon click

- src/core/components/courses/ProfileOrganization.vue
> COM-3560: can download attendance sheet

- src/core/pages/signin/Authenticate.vue
- src/index.template.html
> COM-3578 - update meta data

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/learners/ProfileCourses.vue
- src/modules/client/pages/ni/courses/BlendedCourseProfile.vue
- src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue
> COM-3566: block sections

- src/core/helpers/courses.js
- src/modules/vendor/components/billing/CourseBillingCard.vue
> COM-3579 - add default description in draft bill

- src/core/composables/courseFilters.js
- src/core/data/constants.js
- src/modules/vendor/components/courses/CourseCreationModal.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> COM-3567: can create intra_holding course

- src/core/components/table/CoachCreationModal.vue
- src/core/components/table/CoachList.vue
> COM-3575 - can choose sending email at coach account creation

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TraineeContainer.vue
- src/core/helpers/ability.js
> COM-3564: can access history + boyscout

- src/modules/vendor/components/courses/CourseCreationModal.vue
> COM-3592: fix bug on course creation

- src/core/components/table/AttendanceTable/Composables/Attendances.js
> COM-3582: can get potential trainees

- src/core/components/courses/CourseCell/index.vue
- src/core/composables/courseFilters.js
- src/core/data/constants.js
> COM-3601: without trainer filter works

- src/core/components/courses/AttendanceSheetAdditionModal.vue
- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
> COM-3585: can upload intra_holding attendance sheet

- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
> COM-3584: can't add sheet if no companies

- src/core/api/Courses.js
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/data/constants.js
> COM-3611 - download zip pdf if user is coach or client admin

- src/core/components/courses/ProfileBilling.vue
- src/core/helpers/utils.js
- src/css/app.sass
- src/modules/vendor/components/billing/BillingPurchaseAdditionModal.vue
- src/modules/vendor/components/billing/CourseBillCreationModal.vue
- src/modules/vendor/components/billing/CourseBillValidationModal.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
- src/modules/vendor/components/billing/CourseFeeEditionModal.vue
- src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
- src/modules/vendor/components/billing/CoursePaymentEditionModal.vue
- src/modules/vendor/components/billing/PayerEditionModal.vue
> COM-3606: change course bill model from company to companies

- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
> COM-3614: change course credit note model from company to companies

- src/core/composables/courseBills.js
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-3615: can download credit note

- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/helpers/ability.js
> COM-3621 - display button on clientInterface and when role is trainer

- src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-3616: can create payment

- src/core/components/courses/ProfileBilling.vue
- src/core/composables/courseBills.js
- src/core/helpers/utils.js
- src/css/app.sass
- src/modules/vendor/components/billing/BillingPurchaseAdditionModal.vue
- src/modules/vendor/components/billing/CourseBillCreationModal.vue
- src/modules/vendor/components/billing/CourseBillValidationModal.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
- src/modules/vendor/components/billing/CourseFeeEditionModal.vue
- src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
- src/modules/vendor/components/billing/CoursePaymentEditionModal.vue
- src/modules/vendor/components/billing/PayerEditionModal.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
fusion de branche feature 20/11/23
> fusion de branche feature

- src/core/components/courses/ProfileBilling.vue
- src/core/composables/courseBills.js
- src/core/data/constants.js
- src/modules/vendor/components/billing/CourseBillCreationModal.vue
- src/modules/vendor/components/billing/CourseBillValidationModal.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/components/billing/CourseFeeEditionModal.vue
> COM-3608: can add counit unit

- src/modules/vendor/components/billing/CourseFeeEditionModal.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-3612: order bills in 3 arrays

- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-3612: show full companies

- src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
- src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> COM-3625: put info in banner

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TrainingContractContainer.vue
- src/core/helpers/ability.js
> COM-3587: can get intra holding training contracts

- src/core/components/courses/TrainingContractContainer.vue
- src/core/components/courses/TrainingContractCreationModal.vue
- src/core/components/courses/TrainingContractGenerationModal.vue
- src/core/components/courses/TrainingContractInfosModal.vue
- src/core/composables/courses.js
> COM-3588: include intra_holding case

- src/core/components/form/Input.vue
> COM-3511: overflow hidden

- src/core/api/TrainerMissions.js
- src/core/components/courses/TrainerMissionCreationModal.vue
- src/core/components/form/MultipleOptionGroup.vue
- src/modules/vendor/components/trainers/ProfileContract.vue
- src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
> COM-3632: can upload trainer mission

- src/core/components/courses/ProfileOrganization.vue
- src/core/helpers/ability.js
- src/modules/vendor/components/courses/CourseCreationModal.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> COM-3631: a course can have certifying tests

- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> fix bug on creation

- src/core/components/courses/TraineeContainer.vue
> COM-3633: hide button when no trainees

- src/core/components/courses/UserAdditionModal.vue
> COM-3646: fix bug

- src/core/components/courses/TrainerMissionCreationModal.vue
- src/core/components/courses/TrainerMissionInfosModal.vue
- src/core/components/courses/TrainingContractInfosModal.vue
- src/core/composables/courseDocumentInfosModal.js
- src/core/composables/infosModal.js
- src/core/data/constants.js
- src/modules/vendor/components/trainers/ProfileContract.vue
> COM-3634: can generate trainer mission

- src/core/api/TrainerMissions.js
- src/core/components/courses/TrainerMissionCreationModal.vue
- src/core/components/courses/TrainerMissionTable.vue
- src/modules/vendor/components/trainers/ProfileContract.vue
> COM-3630: can cancel trainer mission

- src/core/components/courses/ProfileOrganization.vue
> COM-3607: can update trainer with trainer mission

- src/modules/client/pages/ni/courses/ContactProfile.vue
> COM-3645 - display salesRepresentative on ContactProfile

- src/core/components/courses/BlendedCourseProfileHeader.vue
- src/core/components/courses/TrainerMissionTable.vue
- src/core/helpers/ability.js
- src/core/helpers/rbac.js
- src/modules/vendor/components/trainers/ProfileContract.vue
- src/modules/vendor/mixins/menuItemsMixin.js
- src/modules/vendor/pages/trainers/administrative/Contracts.vue
- src/modules/vendor/pages/trainers/administrative/Info.vue
- src/modules/vendor/router/routes.js
> COM-3629: can see my trainer missions as a trainer

- src/core/components/courses/TrainerMissionCreationModal.vue
- src/modules/vendor/components/trainers/ProfileContract.vue
- src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
> COM-3654: rof can have trainer mission

- src/core/components/courses/TrainerMissionInfosModal.vue
> COM-3634: fix bug

- src/core/composables/learnersCreation.js
- src/modules/client/pages/ni/courses/LearnersDirectory.vue
> COM-3659: can see holding trainees

- src/modules/client/pages/ni/courses/LearnersDirectory.vue
> COM-3517: can create trainee

- src/modules/client/pages/ni/courses/LearnerProfile.vue
- src/modules/vendor/components/companies/ProfileInfo.vue
- src/modules/vendor/pages/ni/pedagogy/ProgramProfile.vue
- src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
- src/modules/vendor/pages/ni/users/learners/LearnerProfile.vue
- src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
> COM-3656 - fix bug at company's edition

- src/core/components/courses/InterlocutorCell.vue
- src/core/components/courses/InterlocutorModal.vue
- src/core/components/courses/ProfileOrganization.vue
> COM-3518 : can remove trainer from course

- src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> COM-3662 - reset filters on arrival at BlendedCourseDirectory (clientInterface)

- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/css/modal.sass
> COM-3663 - rof can download completionC in pdf

- quasar.conf.js
> COM-3665 : add hydratation flag to remove warning

- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/helpers/ability.js
> Com 3663 fix

- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-3673: sort coursebills

- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-3666-2: fix bug

- src/core/components/courses/ProfileOrganization.vue
> COM-3666: fix label

- src/core/components/courses/ProfileOrganization.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
> MES 19/03/2024 - 2

- package-lock.json
- package.json
> COM-3685: update html-loader

- src/core/api/Questionnaires.js
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/components/courses/QuestionnaireQRCodeCell.vue
- src/core/components/questionnaires/cards/MetaInfos.vue
- src/core/helpers/courses.js
- src/modules/notLogged/pages/QuestionnaireForm.vue
- src/router/routes.js
> COM-3687: join both questionnaires

- src/modules/notLogged/pages/QuestionnaireForm.vue
> COM-3708 : display message when there is no card in questionnaire

- src/router/routes.js
> COM-3689 : remove useless temporary code

- src/modules/vendor/pages/trainers/management/SelfPositionningAnswersProfile.vue
> COM-3720 - reset trainerComment and add condition to block trainee selection

- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/modules/vendor/router/routes.js
> COM-3721 - display redirection to trainers questionnaire answers

- src/modules/vendor/components/questionnaires/SelfPositionningItem.vue
- src/modules/vendor/pages/trainers/management/SelfPositionningAnswersProfile.vue
> COM-3719 - display buttons only when there is endcourse answer

- src/core/components/LabelsDetails.vue
- src/core/components/courses/SurveyChart.vue
> COM-3703 : display all legends on SurveyChart

- .github/workflows/endToEnd.js.yml
> COM-3754 - update mongodb version in ci

- src/modules/vendor/pages/ni/users/holdings/HoldingsDirectory.vue
> COM-3747: display companies count

- src/core/composables/learnerDirectory.js
- src/core/composables/learnersCreation.js
- src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
> COM-3748: display holding name

- src/core/components/courses/CompanyAdditionModal.vue
- src/core/components/courses/TraineeContainer.vue
- src/core/components/courses/UserAdditionModal.vue
- src/core/components/form/CompanySelect.vue
- src/core/composables/companiesCoursesLink.js
> COM-3753: display holding in selector

- src/modules/vendor/components/courses/ProfileQuestionnaires.vue
- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
- src/modules/vendor/pages/ni/management/OldQuestionnaireAnswersProfile.vue
- src/modules/vendor/pages/ni/pedagogy/QuestionnaireAnswersProfile.vue
> COM-3704-fix display data when navigating from course profile

- src/core/components/form/CompanySelect.vue
- src/core/composables/courseFilters.js
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> COM-3751: holding in filter

- src/modules/vendor/pages/ni/pedagogy/QuestionnaireAnswersProfile.vue
> Com 3705 fix

- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
> COM-3702 - fix filter initialisation on trainer interface

- src/modules/vendor/components/companies/CompanyCreationModal.vue
- src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
> COM-3749: can link to holding on creation

- src/core/components/courses/SurveyChart.vue
- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
- src/modules/vendor/pages/ni/pedagogy/QuestionnaireAnswersProfile.vue
> COM-3763 - display startAnswers and endAnswers separatly

- src/core/composables/courseFilters.js
- src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/trainers/management/BlendedCoursesDirectory.vue
- src/store/course.js
> COM-3760 - on trainer interface : set archived filter on all courses

- src/core/components/form/Select.vue
- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
> COM-3777 - remove useless options / props + selected value is an object when multiple selection

- src/core/components/PictureUploader.vue
- src/core/components/courses/AttendanceSheetAdditionModal.vue
- src/core/components/table/TraineeAttendanceCreationModal.vue
- src/modules/vendor/components/billing/CourseFundingOrganisationCreationModal.vue
- src/modules/vendor/components/programs/cards/CardEdition.vue
> COM-3780: migrate file in vue3

- src/core/components/courses/LearnerCreationModal.vue
- src/core/components/courses/TraineeContainer.vue
- src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
> COM-3774: add holding name in creation user select

- src/core/components/courses/CompanyAdditionModal.vue
- src/core/components/form/CompanySelect.vue
- src/modules/vendor/components/companies/CompanyCreationModal.vue
- src/modules/vendor/components/holdings/ProfileInfo.vue
> COM-3750: can create company on holding profile

- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/billing/CourseBillCreationModal.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
> COM-3783: can add default description on creation

- src/core/components/courses/OpenQuestionChart.vue
> COM-3764 : fix answers filter on OpenQuestionChart

- src/core/components/courses/TraineeContainer.vue
> COM-3774: fix company options

- src/core/components/courses/TraineeContainer.vue
> COM-3789: on TraineeContainer change navigation with router-link

- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/billing/CompaniesSelectionModal.vue
- src/modules/vendor/components/billing/CourseBillCreationModal.vue
- src/modules/vendor/components/billing/PayerEditionModal.vue
> COM-3795: display holding in billing creation and edition

- src/core/components/courses/ProfileTraineeFollowUp.vue
> COM-3806 : display banner when SP questionnaire are answered

- src/core/helpers/rbac.js
- src/modules/vendor/router/routes.js
- [ X ] J'ai vérifié la fonctionnalité sur mobile
> COM-3812: change route in BlendedCourseProfile

- src/core/components/courseBilling/CourseBillingInfos.vue
- src/modules/client/mixins/configMixin.js
- src/modules/client/pages/ni/config/CompanyConfig.vue
- src/modules/vendor/components/companies/ProfileInfo.vue
- src/modules/vendor/pages/ni/config/MainConfig.vue
> Com 3799 2

- src/core/components/courses/CourseCell/index.vue
- src/core/composables/courses.js
> COM-3796 : display all trainers Name in headerInfo

- src/core/components/courses/TrainingContractInfosModal.vue
> COM-3824 - display all trainers on trainingContract

- src/core/components/courses/AttendanceSheetAdditionModal.vue
- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
- src/core/components/table/AttendanceTable/Composables/Attendances.js
- src/core/components/table/AttendanceTable/index.vue
- src/core/components/table/TraineeAttendanceCreationModal.vue
- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
> COM-3844 - fix typo + use middle point instead of .

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TraineeContainer.vue
> COM-3847: fix bug on openCertificationsUpdateModal

- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
- src/modules/vendor/pages/ni/pedagogy/QuestionnaireAnswersProfile.vue
> COM-3838: change trainer in trainers on ProfileAnswers

- src/core/components/courses/CourseContainer.vue
> COM-3861: use ref

- src/core/components/courses/ProfileBilling.vue
> COM-3846: change trainer with trainers in ProfileBilling

- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
- src/core/components/table/AttendanceTable/index.vue
> COM-3851: disable uncomplete attendance sheets

- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
- src/core/components/table/AttendanceTable/index.vue
> COM-3856: can generate file

- src/core/components/courses/TrainerMissionInfosModal.vue
- src/modules/vendor/components/trainers/ProfileContract.vue
> COM-3863: add trainer in trainer-mission-info-modal

- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
> COM-3858: edit deletion message

- src/core/helpers/vuelidateCustomVal.js
- src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
- src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
- src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
- src/modules/vendor/composables/CardTemplate.js
> COM-3770: rename field correct in isCorrect

- src/core/components/courses/SlotContainer.vue
> COM-3874: move first slot to plan and change warning message

- src/core/components/courses/AttendanceSheetAdditionModal.vue
- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
> COM-3875: can select trainer when add attendance sheet

- src/core/api/Courses.js
- src/core/components/courses/InterlocutorCell.vue
- src/core/components/courses/ProfileOrganization.vue
- src/core/data/constants.js
> COM-3881: add TutorModal in ProfieOrganization

- src/core/components/courses/CourseHistoryFeed.vue
- src/core/components/courses/ProfileOrganization.vue
> COM-3880 : change logic for coursehistories

- src/core/components/courseBilling/CourseBillingInfos.vue
- src/core/components/learners/ProfileCourses.vue
- src/modules/client/router/routes.js
- src/modules/vendor/router/routes.js
> COM-3882: display tutor courses

- src/core/components/courses/InterlocutorModal.vue
- src/core/components/courses/ProfileOrganization.vue
- src/core/composables/learnersCreation.js
> COM-3890: change logic for add tutor

- src/core/api/CourseBills.js
- src/modules/vendor/components/billing/CourseBillingCard.vue
> COM-3883: add delete bill in courseBillingCard

- src/core/data/constants.js
- src/modules/vendor/components/questionnaires/ProfileAnswers.vue
> COM-3878 - add new history export type

- src/core/components/courses/ProfileOrganization.vue
> COM-3889: validate before sending email

- src/modules/vendor/pages/ni/config/MainConfig.vue
> COM-3898: can add share capital to vendor company

- src/core/components/menu/SideMenuFooter.vue
- src/modules/client/router/routes.js
> COM-3903: redirect to vendor side

- src/core/components/courses/ProfileBilling.vue
> COM-3907: add logic for single course default description in bill

- src/core/components/table/AttendanceTable/index.vue
> COM-3918: can delete attendance sheet

- src/core/data/constants.js
> COM-3916: can display single courses in kanban

- src/core/helpers/ability.js
> COM-3908: change logic for holding role

- src/core/data/constants.js
- src/modules/vendor/components/courses/CourseCreationModal.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> COM-3909: add logic for certificate generation mode

- src/core/components/courses/ProfileOrganization.vue
- src/core/helpers/ability.js
> COM-3920: edition single course

- src/core/composables/learnerDirectory.js
- src/core/composables/learnersCreation.js
> COM-3929 - remove activityHistoryCount from learners columns directory

- src/core/components/courses/InterlocutorCell.vue
- src/core/components/courses/ProfileOrganization.vue
> COM-3943: display connection infos

- src/core/components/courses/TraineeContainer.vue
- src/core/composables/courses.js
> COM-3922: hide company on single course

- src/core/components/courses/ProfileOrganization.vue
> COM-3923: use type rather than subprogram

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/TraineeContainer.vue
- src/core/components/courses/TraineeTable.vue
- src/core/helpers/ability.js
> COM-3921: can't add or remove trainee from single course

- src/modules/vendor/pages/ni/billing/CompletionCertificatesDashboard.vue
> COM-3941: add company selector in completion certificates

- src/core/components/courses/AttendanceSheetAdditionModal.vue
- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
> COM-3926: adapt attendance sheet to single courses

- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/billing/CourseBillCreationModal.vue
- src/modules/vendor/components/billing/CourseBillValidationModal.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/components/billing/CourseFeeEditionModal.vue
> COM-3933: can create bill for single course

- src/modules/vendor/pages/ni/billing/CompletionCertificatesDashboard.vue
> COM-3939: add holding selector in completion certificates

- src/core/api/CompletionCertificates.js
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/helpers/dates/utils.js
- src/modules/vendor/components/courses/CompletionCertificateAdditionModal.vue
- src/modules/vendor/pages/ni/billing/CompletionCertificatesDashboard.vue
> COM-3940: creation add certificates in profile trainee follow up

- .github/workflows/endToEnd.js.yml
- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/helpers/ability.js
> COM-3960: hide useless sections

- src/modules/vendor/components/courses/CourseCreationModal.vue
> COM-3959: add trainee name as misc

- .github/workflows/endToEnd.js.yml
- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/components/table/AttendanceTable/index.vue
> COM-3954: can't add and see attendance for unregistered trainee

- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/components/table/CompletionCertificateTable.vue
- src/core/composables/completionCertificates.js
- src/modules/vendor/pages/ni/billing/CompletionCertificatesDashboard.vue
> COM-3913 - can generate completion certificates from profileTraineeFollowUp

- src/core/components/courses/SlotContainer.vue
- src/core/components/courses/TraineeTable.vue
> COM-3958: display error message

- src/core/composables/courseCreation.js
- src/modules/vendor/components/courses/CourseCreationModal.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
- src/modules/vendor/pages/ni/management/SingleCourseDirectory.vue
> COM-3971: can add price to course at creation

- src/core/components/courses/SlotEditionModal.vue
> COM-3970-fix: fix css delete button

- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/billing/CourseBillCreationModal.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
> COM-3975: add maturityDate for creation bill logic

- src/modules/vendor/components/billing/CourseBillEditionModal.vue
- src/modules/vendor/components/billing/CourseBillingCard.vue
> COM-3976: add maturityDate on course bill edition

- package-lock.json
- package.json
> Define airbnb-style in devDependancies

- src/core/components/courses/ProfileBilling.vue
> COM-3974: adapt to inter b2b/intra holding

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/composables/courses.js
> COM-3957: logic modification on followUpMissingInfo

- src/core/components/table/AttendanceTable/index.vue
> COM-3984: scroll to last slot

- src/core/components/table/AttendanceTable/index.vue
> COM-3984-fix: fix bug with slots without attendance

- src/core/components/courses/CourseHistory.vue
- src/core/data/constants.js
> COM-3993: add trainer in course history

- src/core/components/courses/ProfileBilling.vue
> COM-3979: fix bug

- src/core/components/ButtonToggle.vue
- src/core/components/CompaniHeader.vue
- src/core/components/CompanyLinkRequestCell.vue
- src/core/components/CourseProgress.vue
- src/core/components/DirectoryHeader.vue
- src/core/components/ProfileHeader.vue
- src/modules/client/pages/ni/courses/Dashboard.vue
> COM-3995-2: migration ButtonToggle in composition API

- src/core/api/CourseBills.js
- src/core/components/courses/ProfileBilling.vue
- src/core/composables/courseBills.js
- src/modules/vendor/components/billing/CourseBillingCard.vue
> COM-3987: refacto course billing card

- src/core/components/courses/BlendedCourseProfileHeader.vue
- src/core/components/courses/CourseHistory.vue
- src/core/data/constants.js
> COM-4001 - can restart course

- src/core/components/courses/ProfileBilling.vue
- src/core/composables/courseBills.js
- src/core/data/constants.js
- src/core/helpers/rbac.js
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/mixins/menuItemsMixin.js
- src/modules/vendor/pages/ni/billing/CourseBillsDashboard.vue
- src/modules/vendor/router/routes.js
> COM-3988: create dashboard

- src/modules/vendor/pages/ni/billing/CourseBillsDashboard.vue
> COM-3990: add filters

- src/core/components/courses/ProfileBilling.vue
- src/core/composables/courseBills.js
- src/modules/vendor/components/billing/CourseBillingCard.vue
- src/modules/vendor/components/billing/MultipleCourseBillEditionModal.vue
> COM-4008 - can edit several bills

- src/core/components/courseBilling/CourseBillingInfos.vue
- src/modules/client/pages/ni/courses/BillingProfile.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
> COM-4024 : fix profile billing

- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
- src/core/components/table/AttendanceTable/index.vue
> COM-4019: refacto signatures

- src/core/components/courses/ProfileBilling.vue
> COM-4008 - fix unrollBill

- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
- src/core/components/table/AttendanceTable/index.vue
> COM-4026: manon's review

- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
- src/core/components/table/AttendanceTable/index.vue
> COM-4027: can generate attendance sheet

- src/core/api/CourseBillingItems.js
- src/modules/vendor/pages/ni/billing/MainConfig.vue
> COM-4015: add delete logic for courseBillingItems

- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
> COM-4037: no warning modal on single course

- src/core/helpers/vuelidateCustomVal.js
- src/modules/vendor/pages/ni/billing/MainConfig.vue
> COM-4041 - add ics in Compani info

- src/core/data/constants.js
> COM-4045: minor changes

- src/core/composables/courseBills.js
- src/modules/vendor/components/billing/CourseBillingCard.vue
> COM-4057: can send description only for trainer fees with percentage

- src/core/components/courses/AttendanceSheetEditionModal.vue
- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
> COM-4067: update attendances on attendance sheet edit

- src/modules/vendor/composables/MenuItems.js
> COM-4069 - hide PaymentsDashboard

- src/core/components/courses/ProfileBilling.vue
> COM-4082: price is 0 if undefined
