CompaniTech/compani-webapp

- src/pages/ni/billing/TppBillSlips.vue
NB : ce qui n'allait pas :
la collection BillSlipNumber n'etait pas mise a jour apres la creation des bordereaux
les bordereaux etaient créés en doublon
la page n'etait pas triee par mois
> COM-933 - add pagination

- src/components/planning/Planning.vue
- src/pages/auxiliaries/planning/AuxiliaryAgenda.vue
- src/pages/ni/planning/CustomerPlanning.vue
- Périmetre interface : coach
- Périmetre pages : planning bénéficiaire et agenda
- Cas d'usage : les heures affichées sur le planning bénéficiaire étaient fausses + correction sur les props de modal de création et d'édition (`.sync` manquant sur planning bénéficiaire et agenda)
> COM-1017 Fix customer planning date display

- src/components/form/DateInput.vue
- src/components/form/DateRange.vue
- src/helpers/vuelidateCustomVal.js
- src/pages/ni/exports/HistoryExports.vue
Lorsque l'on exporte les évènements, ne permettre d'exporter que sur un an. 
J'ai également ajouter un loader sur le bouton pour notifier l'utilisateur que l'export est bien en train d'être fait car il peut être long.
> COM-1005 add min and max date for export

- src/modules/client/pages/customers/Subscriptions.vue
- Périmetre interface : Client / Aidants
- Périmetre pages : Souscriptions
- Cas d'usage : Quand j'arrive sur la page abonnements, je vois le tableau des souscriptions et non "Pas d'abonnement"
> Fix helpers subscriptions display

- src/core/components/table/TableList.vue
- src/modules/client/pages/ni/auxiliaries/Directory.vue
- src/modules/client/pages/ni/customers/CustomersDirectory.vue
- Périmetre interface :  coach/client_admin
- Périmetre pages : repertoires auxiliaires/bénéficiaires
- Cas d'usage :  affichage des pastilles d'alerte d'infos manquantes
> Fix TableList cell display

- src/core/data/constants.js
- Périmetre interface : Client 
- Périmetre roles : aux / RP / coach / admin
2 types d’arrêt maladie qui ne nécessitent pas de justificatif
- Enfants => Arrêt de travail - garde d’enfant
- Personne a risque (diabétique / enceinte) => Arrêt de travail - salarié a risque
> add absence nature

- src/modules/client/pages/ni/auxiliaries/Directory.vue
- Périmetre roles : coach/client_admin
- Cas d'usage : page répertoire auxiliaire
Petit fix pour l'affichage des noms d'auxiliaires qui n'ont pas de firstname.
> Fix name display of auxiliary in directory

- src/core/mixins/logInMixin.js
- src/router/index.js
- Cas d'usage :  authentification et changement de mot de passe
pour en savoir plus: https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378
> Com 1043 fix

- src/core/pages/AccountInfo.vue
- src/modules/client/pages/customers/Subscriptions.vue
- src/modules/client/store/customer/mutations.js
- src/modules/client/store/rh/mutations.js
- Cas d'usage : lorsque l'on arrive sur la page souscription par le menu sur l'interface aidant, le tableau mandat ne load pas indefiniment + lorsque l'on change de compte, le store a bien ete clear (par exemple lorsque l'on passe entre deux comptes aidants)
> fix mandates loading + clear store when logout

- src/modules/client/components/planning/ChipCustomerIndicator.vue
- src/modules/client/components/planning/Planning.vue
- Périmetre roles : coach/auxiliaire
- Cas d'usage : affichage du referent beneficiaire sur le planning en fonction de la date
> COM-1108 add referent on customer planning

- src/modules/vendor/components/courses/ProfileFollowUp.vue
- Cas d'usage : lorsque le bouton pour copier le lien est desactive, on ne peut pas copier le lien ou se rendre sur la page d'info des formation.
> COM-1115 when disabled we can't copy or go to link

- src/modules/vendor/components/courses/ProfileFollowUp.vue
- Cas d'usage : le contenu de l'onglet suivi de formation n'est pas cliquable si il manque le nom ou le numero de telephone du referent
> COM-1107 - add missing info

- src/modules/client/components/customers/CustomerProfileHeader.vue
- Cas d'usage : possibilite de supprimer un beneficiaire seulement si il n'a pas de contrat, taxcertificat, premiere intervention, creditnote, payment, bill. + fix icone sur front
> COM-1147 fix disable icon to delete customer

- src/modules/vendor/components/courses/ProfileFollowUp.vue
- Cas d'usage : correction du bug relevé par Romain : "si je mets un numéro de téléphone invalide (par exemple : “test”), les boutons de l’onglet “suivi de la formation” ne sont pas bloqués."
=> maintenant si
> Com 1107 fix

- src/modules/vendor/components/programs/ProfileInfo.vue
- Cas d'usage : sur la page d'information d'un programme dans l'onglet 'Configuration/Catalogue' du menu, je peut consulter et modifier un champs "Objectifs pédagogiques"
> add textarea 'Objectif Pédagogique' in 'program/ProfileInfo'

- src/core/helpers/rules.js
- src/modules/client/components/planning/Planning.vue
- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
- Périmetre roles : auxiliaire/referent planning/coach
- Cas d'usage:
un auxiliaire peut creer/editer un evenement pour elle ou en 'a affecter'
un referent planning peut creer/editer n'importe quel evenement
> COM-1167 change right event:own:edit

- src/modules/vendor/components/programs/ProfileInfo.vue
- Cas d'usage : Sur la page d'info d'un programme, quand je vide le champs "Objectifs pédagogiques", le message d'erreur ne s'affiche pas en dessous
> Fix program error

- src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
- Cas d'usage : dans l'onglet 'Structures' les structures sont affichées dans le repo avec leur nom commercial
> COM-1153 print 'trade name'(formerly 'name') in companies repo

- src/modules/client/components/ProfileTabs.vue
- src/modules/vendor/pages/ni/management/CourseProfile.vue
- Périmetre interface : vendeur / client
- Cas d'usage : dans tous les profileInfo (beneficiaires, auxiliaires, programmes, formations, structures, formateurs). Le but etait de limiter la taille d'un onglet à 33% pour que ça se sente mieux visuellement. Je suis pas hyper satisfait de mon truc:
-> (coté écran large) il me semble (au souvenir de ce qu'en disait Romain) ce ticket devait faire en sorte de casser l'alignement des onglets avec les deux inputs dans le corps (ex page profileInfo formation, première onglet). J'ai bien résolu le truc quand on a deux onglets (ils sont limité à 33%) mais quand y en a 4, en retrouve un peu l'alignement car deux onglets font 50%.
-> (coté ecran etroit) je sais pas si ça vous va, couper a 33% c'etait pas possible car pas assés …
> COM-1163 small change in tabs title display

- src/core/data/constants.js
- Cas d'usage : sur la tableaux des coach/admin, les admin ont pour role administrateur
> COM-1000 rename admin client to administrateur

- src/modules/client/mixins/payMixin.js
- src/modules/client/pages/ni/auxiliaries/AuxiliaryProfile.vue
- src/modules/client/pages/ni/pay/ContractEnds.vue
- src/modules/client/pages/ni/pay/ToPay.vue
- Cas d'usage : sur la page ni/pay/contract-ends (STC) je peux afficher les fin de contrat du mois précedent
note : j'ai du mal a voir ce qu'il faut mutualiser ou pas dans les mixins, j'aurai envie de le faire aussi pour validateCreation et createList (qui existe dans ToPay et ContractEnd)... mais j'attend vos retours.
> COM-1198 -- NEXT SPRINT -- add last month selection on end contract

- src/core/components/modal/HtmlModal.vue
- Périmetre interface : tous
- Cas d'usage : le header dans les modales rgpd, reglement interieur et conditions generales d'utilisation reste en haut lorsque l'on scroll
> COM-1176 header sticky in html modal

- src/modules/client/router/routes.js
- Périmetre roles : admin/coach sans erp
- Cas d'usage : lorsqu'un admin/coach sans erp se connecte a l'application, il arrive sur la page des formations.
> Com-1201 change default page for coach/admin without erp

- src/modules/vendor/components/courses/ProfileFollowUp.vue
- Cas d'usage : lorsque les objectifs pedagogiques du programme ne sont pas defini, j'ai un message m'expliquant pourquoi je ne peux pas telecharger les attestations de fin de formation
> COM-1173 add message if can't download completion certificate

- src/core/components/courses/ProfileFollowUp.vue
- Cas d'usage : enlever l'ancine nom 'referant formation' dans le champs du warning de profilFollowUp
> fix-warning-msg

- src/core/components/TitleHeader.vue
- src/modules/client/mixins/payMixin.js
- Cas d'usage : Dans l'export temporaire sur la page de la paie mensuelle : 
Separer en deux colonnes Nom et prenom de l'auxiliaire
Mettre des , plutot que des . dans les nombres
Enlever les retours de lignes dans le detail
> COM-1250 - update pay export

- src/modules/client/mixins/planningActionMixin.js
- Cas d'usage : ajout de la propriété isCancelled au payload quelle que soit sa valeur.
> COM-1266 set 'isCancelled' prop to edition payload even when falsy

- src/core/components/courses/ProfileFollowUp.vue
- src/core/components/table/LargeTable.vue
- src/core/components/table/ResponsiveTable.vue
- src/core/components/table/SimpleTable.vue
- src/core/components/table/TableList.vue
- src/css/app.styl
- Cas d'usage : changement UI pour profilefollowup des formations (partie SMS)
Pour que ca rende bien sur mobile j'ai ajoute un message lorsqu'il n'y avait pas de données. Dites moi ce que vous en pensez puisque du coup le responsive table n'est plus pareil partout.
> COM-1282 change UI for send sms part on profile follow up

- src/core/components/PictureUploader.vue
- src/core/pages/AccountInfo.vue
- src/modules/client/components/auxiliary/ProfileInfo.vue
- Périmetre interface : toutes
+ ajoute de la photo de profile la page 'mon compte'. 
J'ai laissé le stockage de photo tel quel, pour l'instant on a que deux dossiers dans cloudinary auxilaires et coach. Je vous propose :
- un dossier auxilaire/respo planning/auxiliairy_without_company
- un dossier coach/client_admin
- un dossier vendeur
- un dossier beneficiaire
- un dossier sans_role ou stagiaire ?
+ on les image uploadé vont dans le meme fichier qu'elles viennent de dev, ou prod... on laisse comme ça ?
+ j'ai forcé le re-render du composant picture-upload, car la photo voulait pas partir après suppression depuis 'mon compte', j'ai beaucoup cherché, j'ai pas compris pourquoi ce beug et j'ai pas trouvé mieux comme fix que de changer la prop …
> COM-1296 add profile picture to accountInfo

- src/core/components/Banner.vue
- src/core/components/courses/ProfileFollowUp.vue
- Périmetre interface : les deux
- Périmetre roles : coach admin rof formateur
- Cas d'usage : Affichage d'une baniere s'il manque des numeros de telephone de stagiaire.
Je n'ai que change le logo de la baniere pour la differencier des autres. J'ai essaye d'ajouter de l'opacité mais ca ne rendait pas tres bien et je ne sais pas si changer la couleur est une bonne idee. Dites moi ce que vous en pensez :)
> COM-1297 add banner if missing trainees phone number

- src/modules/client/mixins/helperMixin.js
- src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
- Cas d'usage : lorsque l'on cree un aidant et qu'il y a un soucis sur l'envoie d'email, la modale se ferme et le tableau des aidants mis a jour. Idem pour formateur.
> close modal if helper is created even if email is not sent

- src/core/components/table/CoachList.vue
- src/modules/client/components/customers/AddHelperModal.vue
- src/modules/client/pages/ni/auxiliaries/Directory.vue
- Cas d'usage : retirer les espaces de debut et de fin sur les emails des stagiaires, auxiliaires et aidants pour eviter le message d'erreur
> COM-1342 - add missing trim on email

- src/core/components/menu/SideMenuFooter.vue
- Cas d'usage : lorsque je n'ai qu'un role vendeur, je n'ai plus acces au bouton pour changer d'interface
> COM-1358 fix display switch interface when uer does not have two roles

- src/modules/vendor/pages/ni/config/ProgramsDirectory.vue
- Cas d'usage : Sur le catalogue des programmes on a une colonne de décompte d'étapes pour chaque types type ( e-learning/ presentiel).
> COM-1354 add two steps counts : one for e-learning and one for on_site

- test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
- Cas d'usage : l'evenement déjà existant est populate a la date du jour, donc si on execute le test un lundi on se retrouve a cliquer sur l'evenement au lieu de cliquer sur le fond blanc du planning (pour ouvrir la modale de creation on clique sur planning-cell eq(0)).
> COM-1395 avoid clicking on event to open creation modal

- src/core/api/ressources/alenviAxios.js
- src/core/mixins/logInMixin.js
- src/router/redirect.js
changement AlenviAxios: verification refreshtoken avant alenvi token et envoie d'erreur si les token ne sont pas definis
+ envoie d'une erreur si loggedUser n'est pas defini a la fin de la fonction login
+ on ne redirige pas vers login si il y a eu un soucis lors de l'authentification (cela engendrait une erreur navigationDuplicate).
> COM-1398 change alenviAxios + login

- src/modules/client/components/customers/ProfileInfo.vue
- Cas d'usage : lorsque j'upload un mandat pour les beneficiaires, le nom du fichier contient bien le prenom. 
ON a pusieurs fichiers dans le drive avec pour nom mandat_signe_function ()
> COM-1403 fix customerIdentity methods in customers ProfileInfo

- src/core/helpers/vuelidateCustomVal.js
- src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
- src/modules/vendor/mixins/templateMixin.js
- Cas d'usage : je ne peux pas avoir de balises de la forme `<trou> </trou>` ou `<trou> test </trou>`
> Com 1409 fix

- src/core/helpers/vuelidateCustomVal.js
- Cas d'usage :  Lorsqu'il n'y a qu'une balise `<trou></trou>` mal orthographié, le warning indique le fait que c'est mal ortographie et pas qu'il n'y a pas de balise.
> COM-1409 fix warning error when there is only one tag with error

- src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
- Cas d'usage : changement texte lorsqu'il n'y a pas le bon nombre de balises dans texte a trou
> COM-1409 change wording in warning for fill the gaps

- src/core/helpers/vuelidateCustomVal.js
- src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
- src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
- src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
- Cas d'usage : on enleve la comparaison avec le nbr de reponse en bd. Deux ptites coquilles fixées, le minimum de reponse dns un tableau et la regexp qui laissait passer les saut de ligne.
> COM-1410-template-fix remove useless dbCount and fix custom validation

- src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
- Cas d'usage : sur le plannnig des groots, lorsque je vais sur la premeire semaine de septembre et que je reviens sur la semanie courante, je vois le planning qui s'affiche.
> COM-1494 call refresh if there is auxiliaries or sectors in filter

- src/modules/vendor/components/programs/ProfileContent.vue
- Cas d'usage : le drag and drop des etapes est desactive si le sous programme est publié
> COM-1460 disable steps drag and drop if subprogram is published

- src/modules/vendor/components/learners/ProfileCourses.vue
- Cas d'usage : N'affiche plus les formations _eLearning_ sur la page profil d'un des stagiaires
(comme on ne peut pas encore inscrire un stagiaire à une formation _eLearning_, on peut vérifier que le filtre marche en remplaçant `BLENDED` par `STRICTLY_E_LEARNING` )
> COM-1560 filtered to blended only in ProfileCourses

- src/modules/client/mixins/configMixin.js
- src/modules/client/mixins/payMixin.js
- src/modules/client/pages/ni/config/RhConfig.vue
- src/modules/client/pages/ni/pay/ToPay.vue
- Périmetre interface : CLIENT
Dans les paies (stc et paie mensuelle), le champ 'autre frais' est devenu 'frais téléphonique'. Si l'auxiliaire à un justificatif de téléphone, les frais sont calculés, sinon ils sont de 0.
> COM-1549 - change otherFees to phoneFees

- src/modules/client/mixins/configMixin.js
- src/modules/client/pages/ni/config/CustomersConfig.vue
- src/modules/client/pages/ni/config/RhConfig.vue
- src/modules/client/pages/ni/config/SurchargeCreationModal.vue
- Périmètre interface : client
- Périmètre rôles : admin
- Cas d'usage : dans configuration bénéficiaire, j'ajoute une nouvelle majoration
l'affichage des erreurs pour les `numberInputs` se fait depuis la _configMixin_ : la fonction `nbrError` accède au `$v` de l'objet courant, or ici cela ne peut pas fonctionnner car `$v` est toujours remplacé par `validations` dans nos composants. J'ai donc remis `$v` comme prop mais on perd un peu en cohérence
qu'en pensez vous?
> Com 1578 - refacto surchargeCreationModal

- src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
- Périmetre interface : Vendor
- Périmetre roles : apprenant / rof / admin
Sur la page répertoire apprenant, la colonne 'formation suivies' ne prends pas en compte les formation e_learning. Fait suite au changement du nom de variable dans le back de coursesCount
> Com 1560 - Fix courses count

- src/modules/client/pages/ni/config/CustomersConfig.vue
- src/modules/client/pages/ni/config/RhConfig.vue
- Cas d'usage : sur la page rh config, lorsque je valide l'ajout ou la modification d'une equipe, la modale se ferme
> COM-1597 hide modal on submit for sector creation and edition modal

- src/modules/client/components/planning/EventCreationModal.vue
- src/modules/client/mixins/planningModalMixin.js
- Périmetre roles : aux/coach/admin
- Cas d'usage : Si un service est archive, je ne peux pas ajouter/modifier un evenement avec une souscription liée a ce service.
> COM_1587 disable sub if service is archived

- src/modules/vendor/mixins/templateMixin.js
- Périmetre roles : ROF / admin
Sur la carte QuestionAnswer, lorsque je sélectionne 'sélection multiple', je reçois un message d'erreur de mise à jour de la carte. Cela venait du fait qu'on utilise updateCard pour mettre à jour la valeur de ce booléen et qu'on ajoutait '.trim()' à ce booléen.
> COM-1585-fix - Fix updateCard

- src/modules/client/mixins/payMixin.js
- Périmetre roles : Admin / Coach
Dans le tableau d ela paie mensuelle, colonne "Heures à travailler" on affichait `hoursToWork - diff.absencesHours` mais dans l'export on affichait `hoursToWork - diff.hoursToWork` (alors meme que diff.hoursToWork n'existe pas... )
> CON-1621 - fix csv to match with table

- src/core/components/courses/SurveyChart.vue
- Cas d'usage : maquette revue par Romain
INFO: je n'ai pas géré la taille de la zone de texte (cf point 4)
NOTE DE ROMAIN:
Est ce que c’est facile de régler la taille des rectangles, ainsi que l’espaces qui les sépare ? Si oui, peux-tu essayer de coller à la maquette que je viens de mettre à jour ? 
* largeur de 56px
* hauteur de 160px
* espace de 8px entre chaque rectangle
* la zone de texte pour les labels qui ne dépasse pas la moitié de la 2ème colonne (soit 56 + 8 + 56/2 = 92 px de largeur pour la zone texte)
* Rajouter une marge entre les chiffres “1, 2, 3, 4, 5” et le haut du rectangle de 8px
> COM-1606 new Romain's sketch

- src/core/components/form/FileUploader.vue
- src/core/data/constants.js
- src/modules/vendor/components/programs/cards/templates/TextMedia.vue
- src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
- src/modules/vendor/mixins/templateMixin.js
- Périmetre roles : rof / admin
Sur une carte TitleMedia, je peux sélectionner l'input que je souhaite (image, video ou audio).
Ce qu'il manque sur cette PR :
- La gestion de l'upload par GCS (google cloud)
> Com 1628 - Upload Image, Video and Audio

- package-lock.json
- package.json
| Package                                  | Current       | Wanted        | Latest |
| ---------------------------------------- | ------------- | ------------- | ------ |
| `@quasar/app`                                         | 2.1.8               | 2.1.11              | 2.1.11  |
| `quasar`                                                   | 1.14.5              | 1.14.7        | 1.14.7 |
| `eslint`                                                      | 7.14.0        | 7.15.0        | 7.15.0 |
| `eslint-plugin-vue`                                        | 7.1.0         | 7.2.0         | 7.2.0  |
|` quasar-app-extension-testing-e2e-cypress` | 1.0.0-beta.13 | 1.0.0-beta.13 | 2.0.4  |
| `axios`                                    | 0.19.2        | 0.19.2        | 0.21.0 |
| …
> COM-1716 npm update

- src/core/api/Bills.js
- src/core/helpers/file.js
- src/core/pages/DisplayPdf.vue
- src/modules/client/components/customers/billing/CustomerBillingTable.vue
- src/router/routes.js
- Périmetre roles : Admin / Cocah / Aidant
- Cas d'usage : je peux charger mes factures depuis la page de facturation. l'appel se fait via alenviAxios et ne passe plus le `x-access-token` dans l'url
A tester sous chrome, firefox et safari :)
> COM-1689 - remove x-access-token from bills pdf url

- src/core/data/constants.js
- src/core/mixins/logInMixin.js
- Cas d'usage : Lorsqu'un utilisateur se connecte on sait s'il se connecte sur la webapp ou sur le mobile. On conserve la premiere fois qu'il se connecte sur l'application mobile.
> COM-1711 add origin in authentication payload

- src/core/helpers/vuelidateCustomVal.js
- src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
- src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
- src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
qcuFalsyAnswers, qcmAnswers et questionAnswers sont fondus en un seul champ qAnswers.
L'utilisation des qcm et des qcu se fera sous la même forme que question answer :
- ajout des champs answer en plus via un bouton
- passage par les routes /{_id}/answers (POST, PUT, DELETE)
Dans cette PR :
- uniquement la refonte en un seul champ
- le fait que qcm et qcu ne soit plus comme avant est voulu (préparation à l'ajout de réponse par bouton)
> Com 1691 - refacto qcm/qcu/questionAnswers

- src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
- src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
- src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
- src/modules/vendor/mixins/templateMixin.js
Suite du changement sur qcAnswers. L'édition de réponse pour QCM et QCU passe désormais par la route updateQuestionAnswer.
Changement dans l'utilisation de QCM (vu avec Sophie) :
- désormais le texte et la box sont indépendants : on peut avoir une carte qcm sans réponse valide, la carte sera bien sûr  invalide mais réponses seront gardées en back.
Reste à faire :
la route post et delete pour ajouter de nouvelles réponses et les enlever
ATTENTION : le commit COM-1691 - use updateTextAnswer in MultipleChoiceQuestion, n'est pas à prendre en compte. C'était une des deux propositions pour QCM et j'ai vu avec Sophie pour valider la bonne solution (la 2ème donc)
> Com 1691 put

- src/modules/vendor/components/programs/ProfileContent.vue
- Cas d'usage : les pastilles oranges affichent uniquement la valeur du virtual (respectivement isStepValid et isActivityValid)
> COM-1700 rules to publish sub-program

- src/core/api/Users.js
- src/core/api/ressources/alenviAxios.js
- src/core/components/form/FileUploader.vue
- src/core/helpers/alenvi.js
- src/core/mixins/logInMixin.js
- src/core/pages/signin/Authenticate.vue
- src/core/pages/signin/ForgotPassword.vue
- src/core/pages/signin/ResetPassword.vue
- src/modules/client/components/contracts/ContractsCell.vue
- src/modules/client/components/customers/infos/ProfileInfo.vue
- src/modules/client/layouts/Layout.vue
- src/router/index.js
- src/router/redirect.js
- test/cypress/integration/authenticate.spec.js
- test/cypress/integration/customer/agenda.spec.js
- test/cypress/integration/customer/billing.spec.js
- test/cypress/integration/customer/subscription.spec.js
- test/cypress/integration/ni/billing/toBill.spec.js
- test/cypress/support/index.js
Refonte de l'authentification :
- Cote WEBAPP : les cookies (`alenvi_token`, `refresh_token`, `user_id`) sont mis dans le state des réponses de l'api et enregistrer automatiquement dans le navigateur.
- Les 2 premiers ne sont plus accessible par du code JS (`httpOnly`) et sont automatiquement ajoutés aux requetes qui partent du front quand necessaire (`withCredentials` cote webapp)
- Il a donc fallu ajouter une route `logout` pour enlever les cookies lors de la déconnexion (on ne peut plus le faire directement en JS)
> Com 1689 cookies

- src/core/components/learners/ProfileCourses.vue
- src/modules/client/router/routes.js
- src/modules/vendor/router/routes.js
- Périmetre roles : coach / rof / admin
Dans le profile d'un apprenant, sur sa liste de formation, je peux cliquer sur le nom de cette formation et être renvoyé vers le profil de celle ci
> COM-1749 - go to blended course profile

- src/modules/client/pages/ni/courses/Dashboard.vue
- Périmetre roles : coach admin
- Cas d'usage : date de fin exclue alors qu'elle devrait être inclus (ex: on a pas les mêmes stats pour un 13/01 -> 15/01 et un 13/01 -> 16/01 alors que le 16 n'est pas encore passé et que ça devrait être identique)
> COM-1760: endDate non excluded

- src/modules/client/pages/ni/auxiliaries/Dashboard.vue
- Périmetre roles : Auxiliaire / coach
- Cas d'usage : Sur le tableau de bord equipe :
Si mon compteur est a 0, le voyant est vert => exemple Isabelle chez les GIrafes
Si mon compteur est a -35 le voyant est rouge
> COM-1832 - update counter limits

- src/modules/client/components/config/EstablishmentCreationModal.vue
- src/modules/client/pages/ni/config/CompanyConfig.vue
- Cas d'usage : sur la page de configuration generale, vue/no-mutating-props sur la modale de creation d'etablissement. 
+ lorsque je cree un etablissement et que je reviens sur la modale, les champs sont bien reset et je n'ai pas de warning.
> COM-1782 no mutating props for establisment creation modal

- src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
- src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
- Cas d'usage :  je peux indiquer à l'aide d'une checkbox si dans les textes à trou les réponses sont interchangeables ou non
> COM-1846: add checkbox for commutative answers on fillthegap cards

- src/core/mixins/traineeFollowUpTableMixin.js
- Périmetre roles : admin / coach
Fix les trainees dans la formation elearning côté client (on les prenait tous, alors qu'il ne faut que les trainees de la company du client)
> COM-1877 - Fix course in client ELearningCourseProfile

- src/core/components/table/AttendanceTable.vue
- Cas d'usage : amélioration du tableau d'émargement
separators: je n'ai pas trouvé un moyen de les ajouter sans désaxer les colonnes
scroll: j'ai enlevé le display-table pour pouvoir avoir un scroll, le display-table servait à garder les colonnes a gauche.
j'ai deux possibilités de rendu (cf mon commentaire sur les width des colonnes)
> COM-1851 table enhancements

- src/core/components/courses/SlotContainer.vue
- Périmetre roles : rof / admin / trainer
Si un créneau est émargé, je ne peux pas le supprimer (suivi des stagiaires -> cocher un créneau -> tenter de le supprimer)
> COM-1895 - disable slot deletion if attendance exist

- src/statics/cguCompani.html
- Périmetre interface : vendeur et client
- Périmetre roles : tous 
- Cas d'usage : dans les CGU le nom était marqué comme facultatif à la création de compte alors qu'il est obligatoire + dans "support@alenvi.ioCe signalement" il manque ". "
> COM-1899: fix minor errors

- src/modules/client/pages/ni/config/CustomersConfig.vue
- ~~[ ] J'ai verifié la fonctionnalite sur mobile~~
Fix d'un petit oubli sur config bénéficiaire, qui cassait le delete de fichier (donc directement lié à 1879)
> COM-1879 - Fix bug

- src/core/components/table/SimpleTable.vue
- src/css/app.styl
- src/css/table.styl
- Périmetre roles : auxiliaires, coach, planning referent, admin
- Cas d'usage : on fixe le header des tableaux SimpleTable pour pouvoir le garder en scrollant (notamment sur mobile)
> COM-1886: add sticky header

- package-lock.json
- package.json
⚠️ Ne mettez pas à jour npm, ça casse tout.
L'upgrade sera creusé dans un prochain ticket. (cf https://github.com/sophiemoustard/alenvi-webapp/pull/974)
https://stackoverflow.com/questions/65724281/npm-error-cannot-destructure-property-name-of-node-as-it-is-null
npm/cli#2599
**@casl/vue**
1.2.2 -> 2.0.2
On doit rester en 1.2.2 (décrit sur leur github + dans la dernière PR npm update) (cf https://github.com/sophiemoustard/alenvi-webapp/pull/974)
https://github.com/stalniy/casl/tree/master/packages/casl-vue
**@quasar/quasar-app-extension-testing-e2e-cypress**
1.0.0-beta.13 -> 3.0.1
On ne le met pas à jour, sinon ça casse tout. Il sera maj lorsques les tests e2e seront d'actualités (cf https://github.com/sophiemoustard/alenvi-webapp/pull/974) …
> WEBAPP - npm update

- src/modules/client/pages/ni/billing/TppBillSlips.vue
Dans le tableau des bordereaux tier payeurs, je vois la liste bien triée (avant Janvier 2021 était juste après Janvier 2020)
> COM-1888 - Fix sort on month in tppBillSlips

- src/modules/client/mixins/payMixin.js
- src/modules/client/pages/ni/pay/ContractEnds.vue
- src/modules/client/pages/ni/pay/ToPay.vue
- ~~J'ai ajouté une variable d'environnement : ~~
-  ~~[ ] J'ai précisé sur le slite de MES et MEP les modifications faites ~~
Dans le tableau STC, je peux cliquer sur la modale exo / majo lorsque les interventions exo et majo relèvent de la diff et pas du mois sélectionné.
Comment tester :
- créer une auxiliaire
- lui ajouter une heure de travail exo / majo (dimanche / 1er janvier, ...) en janvier.
- mettre fin à son contrat en février
- vérifier que sur le tableau STC vous pouvez cliquer sur les heures exo majo.
- verifier que sur la branche locale 'dev' ce n'est pas le cas
> COM-1923 - Fix modal opening condition

- package-lock.json
- package.json
- server.js
~~- [ ] J'ai précisé sur le slite de MES et MEP les modifications faites~~
- Cas d'usage : MAJ de heroku-ssl-redirect
en passant de la version 0.0.4 a la version 0.1.1, ils ont changé l'export de leur fichier : il sont passer de `module.exports` à `export default`. il faut donc egalement changer la maniere dont nous l'importons dans le fichier `server.js`
solution trouvée ici : https://www.gitmemory.com/issue/paulomcnally/node-heroku-ssl-redirect/17/686772810
explication de la solution : https://stackoverflow.com/questions/43247696/javascript-require-vs-require-default
> COM-1968 - update heroku-ssl-redirect

- src/core/components/courses/SlotContainer.vue
- src/core/components/form/Select.vue
- src/core/data/user.js
- src/modules/client/components/auxiliary/ProfileInfo.vue
- src/modules/client/mixins/menuItemsMixin.js
- src/modules/client/pages/ni/auxiliaries/Directory.vue
- src/modules/client/pages/ni/billing/CreditNotes.vue
- src/modules/client/pages/ni/config/CustomersConfig.vue
- src/modules/vendor/components/programs/SubProgramPublicationModal.vue
- Périmetre interface : client / vendeur
- Cas d'usage : Sur le trello, si je supprime le filtre il ne se remet pas à la valeur par défaut
j'ai choisi la première option de stratégie technique car en mettant à null la valeur par défaut, le champ du sélecteur est vide à l'initialisation
fix boyscoot : menu item bénéficiaire : ajout des accents
> COM-1875: default value for filter on trello

- src/modules/vendor/router/routes.js
- Périmetre roles : trainer
Je ne pouvais pas cliqué sur une formation mixte en tant que trainer sur le trello -> j'avais une 404.
C'était dû à un oubli de cookie
> Remove missing user_id cookie in trainer route

- src/modules/client/pages/ni/auxiliaries/Dashboard.vue
- Périmetre roles : coach/admin/ROF
- Cas d'usage : lorsqu'il n'y a que 2 auxiliaires à afficher le chevron s'aligne avec les compteurs des auxiliaires
(tester avec RIVIA sur avril 2021 par exemple)
> COM-1822: fix bug when two auxiliaries on dashboard

- src/modules/client/pages/ni/pay/ContractMonitoring.vue
- Cas d'usage : sur la page de suivi contrats/avenants, essayer de modifier un contrat/avenant, si il y a une erreur dans la startDate, cela s'affiche bien. (+ plus d'erreur dans la console en arrivant sur la page)
> COM-1991 fix startDateError

- src/core/components/ProfileTabs.vue
- src/css/app.styl
Bug constaté :
- Sur Suivi des stagiaires pour une formation ayant beaucoup de créneaux, le design est cassé et le tableau d'émargement sort de la page. Constatable sur dev -> Passer d'une posture de manager à une posture de coach - Rouen (INTER B2B)
Cause : 
- Sur profile tabs, on avait ajouté 'column' à une div de ProfileTabs pour fix le design sur l'édition de carte questionnaire.
Or column = display flex + flex-direction column + flex-wrap wrap. Et c'est ce flex-wrap qui cassait le design.
Résolution : 
- J'ai remplacé column par flex-column, une nouvelle classe qui ne fait que display flex + flex-direction column. Ce qui répare donc le bug sans casser le design de l'édition de carte questionnaire.
commit responsable (git bisect) : …
> COM-2028 - Fix design bug

- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/modules/client/pages/ni/config/RhConfig.vue
- Périmetre roles : admin/ROF/formateur
- Page d’une formation mixte : désactiver les boutons téléchargement et suppression des feuilles d’émargement
- Page config rh : désactiver le bouton de suppression des documents administratifs
Il n'est pas vraiment possible de tester ce ticket étant donné qu'en local les liens sont d'office supprimés au moment du dump. Par conséquent,  on ne peut pas vérifier que les icônes sont activées quand le lien existe sans faire des branchements un peu risqué avec la prod.
Le mieux qu'il peut être fait est de vérifier d'une part que les icônes sont bien désactivés et s'assurer, en checkant la BDD prod, que le disable porte sur le bon champ
Pour les …
> COM-1990: disbale links when missing

- package-lock.json
- package.json
**@quasar/app**  2.2.4 => 2.2.5
* feat(app/wrappers): add TSDoc for boot wrapper
* perf(app): Backport "only recreate the webpack conf when absolutely necessary" from Qv2
* fix(app): Backport "duplicate postcss plugins" fix from Qv2 (when enabling RTL)
https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-v2.2.5
**@quasar/extras** 1.10.2 => 1.10.4 
* feat(extras): Update Google Material fonts and SVGs
* feat(extras): updated Google Material Design fonts and SVGs
https://github.com/quasarframework/quasar/releases 
**eslint** 7.24.0 => 7.25.0   
*  Minor updates and doc
https://github.com/eslint/eslint/blob/master/CHANGELOG.md   
**eslint-webpack-plugin**  2.5.3 => 2.5.4    
*  Bug fixes
https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/CHANGELOG.md …
> COM-2052: npm update

- src/core/components/DirectoryHeader.vue
- Cas d'usage : le toggle avait disparu sur le répertoire auxilaire, il y est de nouveau. Il ne fallait pas supprimer le toggle de directoryHeader qui est utilisé à plein d'endroit mais juste enlever les props de customerdirectory
> COM-2065-2 : undo change on directoryheader

- src/modules/client/components/planning/EventHistoryFeed.vue
- Périmetre interface : client + mobile erp
- Cas d'usage : dans le flux d'historique des evenements je n'ai pas ceux lié a l'horodatage.
> dont show timestamp in event histories feed

- package-lock.json
- package.json
**Paquets MAJ**
- dotenv 9.0.2 => 9.0.2 
Dans le changelog, ils font mention de pouvoir importer directement dotenv/config mais ils n'ont pas changé leur README pour expliquer comment. Puisqu'on utilise seulement dotenv.config(), ça peut potentiellement nous intéresser 
 https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md
 **Paquets non-MAJ**
- @casl/vue 1.2.2 => 2.0.2 non maj car la version 2 est compatible avec Vue3. Pour Vue2 il faut rester sur la v1
- @quasar/quasar-app-extension-testing-e2e-cypress. 1.0.0-beta.13 => 3.1.0 On ne le met pas à jour, sinon ça casse tout. Il sera maj lorsques les tests e2e seront d'actualités
- chart.js 2.9.4 => 3.2.1 non maj car relié à vue-chart-js (testé et ça casse encore)
- date-holidays 2.1.1 => 3.3.0 non maj car quasar ne supporte pas les …
> COM-2106 - npm update

- src/modules/client/components/planning/EventHistory.vue
- Cas d'usage : il y avait un tiret en trop entre "horodaté" et "à 15h30" sur le message d'horodatage de fin d'evenement
> COM-2075 - remove -

- src/core/components/form/DatetimeRange.vue
- src/core/helpers/date.js
- src/core/mixins/learnerDirectoryMixin.js
- src/modules/client/components/planning/DeleteEventsModal.vue
- src/modules/client/components/planning/EventCreationModal.vue
- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/mixins/planningModalMixin.js
- src/modules/client/pages/ni/planning/CustomerPlanning.vue
- Périmetre roles : coach/admin/aux
- Cas d'usage : je ne peux pas créer une intervention pour un bénéficiaire arrêté (postérieur à la data d'arrêt)
- arrêter un bénéficiaire
- essayer de lui créer une intervention après sa date d'arrêt (planning aux et bénéficiaire) (pop up warning)
- essayer de modifier une autre intervention postérieure à la date d'arrêt pour l'affecter au bénéficiaire arrêté (il ne doit pas apparaitre dans la liste)
- essayer de modifier une intervention du bénéficiaire antérieure à la date d'arrêt pour la faire passer après la date d'arrêt (on doit avoir un message d'erreur sur la date)
> COM-2095: block creation and edition after stopping date

- src/core/components/table/CoachList.vue
Dans les cas suivant, verifier que l'on cree bien un objet UserCompany :
Ajout d'un apprenant dans une structure (verifier sur le repertoire apprenant cote client + ajout de stagiaire intra (cote client et coté vendeur + ajout de stagiaire inter cote vendeur)
Ajout d'un coach (cote client et cote vendeur)
Ajout d'une auxiliaire
Ajout d'un aidant
Verifier egalement que si l'utilisateur a deja une entreprise, cela ne recree pas un UserCompany.
Verifier les cas de creation ainsi que de modification d'utilisateurs
> dont send company if user already have one on coachlist

- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/components/planning/Planning.vue
- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/pages/ni/pay/Absences.vue
- src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
- src/modules/client/pages/ni/planning/CustomerPlanning.vue
- Cas d'usage : Le planning s'affiche + suppression du bouton pour les historiques d'evenement dans la modale. 
J'ai revert un commit de la PR COM-2075  --> Verifier qu'il n'y a pas de changements dans la pr COM-2075 qui sont incompatibles avec ce revert. 
Tester la creation/l'edition d'evenement et de repetitions
> Com 2075 fix

- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
- src/modules/client/pages/ni/pay/Absences.vue
- src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
- src/modules/client/pages/ni/planning/CustomerPlanning.vue
- Périmetre roles : coach/auxiliaire
- Cas d'usage : Lorsque j'ouvre une modale d'edition d'evenement, les champs sont desactivés, et s'activent quand les  historiques sont recus. (Pour tester, ne pas hesiter a ralentir artificiellement la connexion avec les devtools)
Tester : 
- sur le planning auxiliaire (cote coach et auxiliaire)
- sur le planning beneficiaire (cote coach et auxiliaire)
- sur l'agenda auxiliaire (cote auxiliaire)
- sur la page absence (cote coach)
> COM-2075 disable fields on history loading

- src/index.template.html
- Cas d'usage : Sur l'app quand j'ouvre la console, je n'ai plus d'erreur (cf image)
> fix favicon error in console

- src/modules/client/components/planning/ChipCustomerIndicator.vue
- Cas d'usage : Sur safari, sur le planning bénéficiaire, je vois bien le nom du référent
> COM-2217 - fix display on safari

- src/core/data/constants.js
- src/modules/client/pages/customers/Subscriptions.vue
- src/modules/client/pages/ni/config/CustomersConfig.vue
- Périmetre roles : admin / aidant
ETQ aidant, lorsque je clique sur 'les conditions générales de services Alenvi Home SAS.' dans mon onglet 'Abonnement', je vois le template de cgs d'Alenvi. Attention, ce fichier ne peut-être que un HTML pour l'instant. Je ne pense pas que ça soit le comportement voulu mais ça sort du périmètre du ticket, donc si vous êtes d'accord, je préviendrai Romain.
Si je suis un aidant d'une autre structure, je vois bien le template de ma structure ainsi que le nom de ma structure sur le lien
> COM-2211 - Fix gcs use and add dynamic name

- src/core/data/constants.js
- src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
- src/modules/client/components/customers/infos/CustomerNoteHistory.vue
- src/modules/client/components/table/CustomerNoteCell.vue
- Périmetre roles : auxilaire/coach/admin
- Cas d'usage : Lorsque l'on modifie la description d'une note de suivi, c'est enregistré dans l'historique.
> COM-2207 create customerNote decription history

- src/core/components/learners/ProfileInfo.vue
- src/core/pages/AccountInfo.vue
- src/modules/client/components/auxiliary/ProfileInfo.vue
- src/modules/vendor/components/trainers/ProfileInfo.vue
- Périmetre roles : auxiliaire/admin/coach/formateur
- Cas d'usage : Si j’essaie de modifier l’adresse mail d’un utilisateur avec une adresse mail déjà existante je n'ai plus la pop-up verte et le mail erroné n'est pas gardé.
A vérifié pour : 
Fiche Auxiliaire
Fiche Apprenant (côté client et côté vendeur)
Fiche Formateur (coté vendeur)
Informations personnelles (côté formateur)
Mon compte (côté client et côté vendeur)
> COM-2167: remove green popup when fail on email change

- src/core/components/table/ExpandingTable.vue
- Cas d'usage : sur le tableau de progression des stagiaire, le tri n'a plus que 2 états au lieu de 3 (état "pas de tri" supprimé).
> COM-2229: no third state when sort column

- src/core/components/PictureUploader.vue
- src/core/components/courses/CourseHistoryFeed.vue
- src/core/components/modal/HtmlModal.vue
- src/core/components/modal/Modal.vue
- src/modules/client/components/contracts/ContractEndingModal.vue
- src/modules/client/components/contracts/ContractsCell.vue
- src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
- src/modules/client/components/planning/DeleteEventsModal.vue
- src/modules/client/components/planning/EventHistoryFeed.vue
- src/modules/client/components/planning/PlanningModalHeader.vue
- src/modules/client/pages/customers/Subscriptions.vue
- Périmetre interface : tous
- Cas d'usage : les boutons clear deviennent des boutons close.
Changements : 
- Croix pour supprimer sa photo de profil dans les infos du compte
- Croix pour fermer la modale des CGU et RGPD dans les infos du compte
- Croix pour fermer l’historique d’une formation sur le profil organisation d’une formation
- Croix pour fermer une modale
- Croix dans la cellule d’un contrat auxiliaire pour mettre fin au contrat et croix sur le bouton Mettre fin au contrat dans la modale associée
- Croix sur la modale des heures d’une auxiliaires dans le planning auxiliaire (lorsqu’on clique sur le compteur d’heures)
- Croix sur le bouton Supprimer les interventions dans la modale de suppression des …
> COM-2089: change clear button in close button

- src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
- Périmetre roles : Coach et Auxiliaire
- Cas d'usage : Sur le planning, je peux selectionner un auxiliaire et son equipe dans le selecteur en haut :
je ne vois qu'une fois le planning de l'auxiliaire concernée
je peux accéder a l'historique du planning
si je supprime l'equipe je vois toujours le planing de l'auxiliaire (qui reste selectionné)
si je supprime l'auxiliaire je vois toujours son planning car l'équipe reste selectionnée
> COM-2276 - do not add auxiliary in array if already inside

- package-lock.json
- package.json
@quasar/extras : MAJ https://quasar.dev/start/release-notes#introduction
-> feat(extras): upgrade Google material icons to latest
eslint-plugin-import : MAJ -> pas de change log
@casl/vue : non maj car il faut mettre quasar et vue a jour avant
@quasar/app : sera mis a jour en meme temps que quasar
chart.js : non maj car la version 2 est compatible avec Vue3. Pour Vue2 il faut rester sur la v1
date-holidays :  non maj car quasar ne supporte pas les es modules
eslint-webpack-plugin : non maj car ne supporte plus webpack4 et quasar1 est sur webpack4 - il faut passer a quasar 2 pour avoir webpack5 -> https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/CHANGELOG.md
html-loader : non maj car ne supporte plus webpack4 et quasar1 est sur webpack4 - il faut passer a quasar 2 pour …
> COM-2292 - npm i

- src/core/components/courses/TraineeTable.vue
- [] J'ai verifié la fonctionnalite sur mobile
- Périmetre interface : outils / formation
- Périmetre roles : coach, rof
- Cas d'usage : etq coach quand j;ajoute des stagiaires a une formation INTRA, je ne vois pas leur structure dans le select (car c'est celle de la formation, pas besoin de le rajouter)
> COM-2300-fix hide compoany for intra

- package-lock.json
@casl/vue : non maj car il faut mettre quasar et vue a jour avant
@quasar/app : sera mis a jour en meme temps que quasar
chart.js : non maj car la version 2 est compatible avec Vue3. Pour Vue2 il faut rester sur la v1
date-holidays :  non maj car quasar ne supporte pas les es modules
eslint-webpack-plugin : non maj car ne supporte plus webpack4 et quasar1 est sur webpack4 - il faut passer a quasar 2 pour avoir webpack5 -> https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/CHANGELOG.md
html-loader : non maj car ne supporte plus webpack4 et quasar1 est sur webpack4 - il faut passer a quasar 2 pour avoir webpack5
quasar : sera mis a jour d'ici la fin de l'année a priori dans une PR a part
> Com 2347 - npm update

- src/core/helpers/utils.js
- src/modules/client/components/customers/billing/ManualBillCreationModal.vue
- Périmetre interface : client 
- Lors de la creation d'une facture manuelle, lorsque l'utilisateur ajoute plusieurs articles de facturation le total hors taxe s'affiche correctement 
- Sur la page Factures manuelles, les prix s'affichent correctement 
La methode `formatPrice` a été modifie, vérifier que l'affichage des prix est correct sur: 
- la page des avoirs
- le profil d'un beneficiaire (l'affichage des montants correspondant aux factures)
- la page bordereaux tiers-payeurs
- la page suivi des plans d'aide
- la page balances clients
> COM-2298 - fix to display correctly exclTaxesPrice

- src/core/components/form/OptionGroup.vue
- ~J'ai ajouté une variable d'environnement :~
- Périmetre interface : toute la webapp
- Périmetre roles : tous les roles
- Cas d'usage : je ne veux plus voir la bordure autour d'un group-option. 
- Le pb vient de : input.styl > ligne 35 : 
```
.modal-padding
.q-field__control
border: 1px solid $copper-grey-300
border-radius: 3px
```
> COM-2358 fix border

- src/core/components/form/Input.vue
- src/core/components/form/Select.vue
- src/css/input.styl
- src/modules/client/components/customers/infos/CustomerNoteEditionModal.vue
- src/modules/client/components/planning/PlanningModalHeader.vue
- Périmetre interface : client outil
- Cas d'usage : suppression de la bordure en trop sur les modales de `notes de suivi benef` et `creation d'evenement`. J'ai fais un tour des modales de la webapp et j'ai pas trouvé d'autre soucis d'affichage
> COM-2358-border no-border option in select and input

- package-lock.json
- package.json
MAJ
axios - 0.21.4 -> 0.22.0 - https://github.com/axios/axios/blob/master/CHANGELOG.md
NON MAJ
@casl/vue : non maj car il faut mettre quasar et vue a jour avant
@quasar/app : sera mis a jour en meme temps que quasar
chart.js : non maj car la version 2 est compatible avec Vue3. Pour Vue2 il faut rester sur la v1
date-holidays :  non maj car quasar ne supporte pas les es modules
eslint-webpack-plugin : non maj car ne supporte plus webpack4 et quasar1 est sur webpack4 - il faut passer a quasar 2 pour avoir webpack5 -> https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/CHANGELOG.md
html-loader : non maj car ne supporte plus webpack4 et quasar1 est sur webpack4 - il faut passer a quasar 2 pour avoir webpack5
quasar : sera mis a jour d'ici la fin de l'année a priori dans une …
> COM-2398 - npm update

- src/core/helpers/date.js
- src/modules/client/components/contracts/ContractsCell.vue
- Cas d'usage : Sur la page d'un auxiliaire, si celui-ci a des evenements apres la date de debut de son contrat, je ne peux pas supprimer le contrat, sinon je peux le supprimer.
> COM-2405 fix deletion button disabled on contract page

- src/modules/client/components/customers/infos/ProfileInfo.vue
- src/modules/client/components/table/ToBillRow.vue
- Cas d'usage : sur la page profile d'un beneficiaire, sur la modale de creation d'une souscription, les noms des services sont bien les derniers noms donnés aux services. 
Sur la page a facturer, ca ne devrait rien changer mais verifier egalement que c'est bien le dernier nom du service qui s'affiche.
> COM-2432 fix displayed service name in subscription creation modal

- src/modules/client/pages/ni/billing/ManualBills.vue
- Périmetre roles : client_admin
lorsque je créé une facture manuelle pour un beneficiaire, je n'ai plus la ligne Tiers-payeur sur la facture avec un montant de -0,00
POUR TESTER : 
facture manuelle à un bénéficaire avec 2 articles de facturation : 
PU TTC: 1,43 Volume: 7
PU TTC: 2, Volume: 8
> COM-2404: calculate netInclTaxes in backend

- src/modules/client/components/planning/ChipCustomerIndicator.vue
- Cas d'usage : les interventions d'une répétition ne sont pas créés si le bénéficiaire a une absence. Les absences ne sont pas prises en compte dans le compte des heures de la semaine réalisées chez le beneficiaire.
> COM-2492 - remove customer absences from weekly hours count

- src/core/components/courses/AttendanceSheetAdditionModal.vue
- Cas d'usage :  Correction de bug. Dans la modale d'ajout d'une feuille d’émargement, il n'y a plus de doublon de date dans le select
> COM-2515 remove duplicate in select options

- src/core/components/form/DateRange.vue
- src/core/helpers/date.js
- Périmetre roles : auxiliaire/ coach/ admin
- Cas d'usage : Je peux mettre a jour une absence bénéficiaire jusqu'à la date d'arrêt du beneficiaire.
( rappel: le bug était 'lorsque je mets a jour une absence jusqu'a la date d'arrêt du beneficiaire, une erreur arrive --> Impossible: la personne est arrêtée sur cette période`)
- Cette modification peut impacter: 
- la creation d'une absence beneficiaire --> verifier qu'on ne peut pas creer d'absence apres la date d'arrêt d'un evenement 
- l'archivage d'un beneficiaire --> verifier qu'on peut archiver un beneficiaire apres sa date d'arrêt
- la creation d'evbenements --> verifier qu'on peut créer un évènement avant ou le jour de la date d'arrêt mais pas apres
- la …
> Com 2552 fix

- src/modules/client/components/planning/EventCreationModal.vue
- src/modules/client/components/planning/EventEditionModal.vue
- Périmetre roles : Auxiliaire / coach / admin
- Cas d'usage : sur les modales de création et d'édition d'un événement, le champ "note" s'étend sur plusieurs lignes 
A vérifier sur les deux modales: 
- pour une heure interne: 
- ajouter l'adresse (ou la modifier si on est sur la modale d'édition)
- sortir du champ
- éditer le champ notes --> verifier qu'aucun appel a l'api du gouvernement ne part
- sortir du champ --> verifier que les modifications du champ note sont bien enregistrées 
- supprimer l'adresse --> verifier que les modifications du champ note sont encore enregistrées 
- ajouter l'adresse 
- modifier d'autres champs de la modale --> verifier que les appels a l'api du gouvernement ne partent que …
> COM-2365 add textarea type to enlarge note area

- src/core/api/CustomerAbsences.js
- src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
- src/modules/client/pages/ni/planning/CustomerPlanning.vue
- Périmetre interface :  client 
- Périmetre roles : Auxiliaire/Coach/Admin
- Cas d'usage : Je peux supprimer une absence beneficiaire.
> COM-2553 - can remove customer absence

- src/core/components/form/DateRange.vue
- src/modules/client/components/planning/DeleteEventsModal.vue
- Périmetre roles : admin / coach / auxiliaire
Refacto de la suppression de masse d'évènement : on envoyait une date de fin en prenant le `startOf('day')`. C'est changé : on envoie désormais startOf('day') pour la date de début et endOf('day') pour la date de fin
Pour tester : 
- Ajouter un bénéficiaire, des interventions et vérifier que la suppression de masse fonctionne bien
- Arrêter ce bénéficiaire
- Essayer de créer une absence le jour de son arrêt -> l'absence est crée
- Essayer de lui créer une absence pour une date postérieure à son arrêt -> erreur
> COM-2576 - Fix customer absence creation on stop date

- src/modules/client/components/config/ThirdPartyPayerCreationModal.vue
- src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
- src/modules/client/pages/ni/config/CustomersConfig.vue
- Cas d'usage : Bug relevé par Manon : parfois si on modifie le champ teletransmissionId et qu'on blur, le champ change direct pour son ancienne valeur.
=> Le pb vient de l'utilisation de "set" sans initialiser les champs. Prenons un tpp avec aucun `teletransmissionId`.
- Au moment, ou tu entre le premier caractere dans le champ `teletransmissionId`. 
-  le `set(this.editedThirdPartyPayer, path, value);` fait son travail et crée le champ. On peut le verifier en affichant `editiedThirdPartyPayer` juste apres.
- Mais vue ne met pas a jour tout de suite `editedThirdPartyPayer`. Il suffit de regarder avec le vueDevTool. C'est au blur que le champ est créé. => debut de l'incoherence.
- …
> COM-2463-fix edition

- package-lock.json
- package.json
Fix de la version de casl/vue qui causait un warning.
Il fallait passer à la version 2 : https://github.com/stalniy/casl/blob/master/packages/casl-vue/CHANGELOG.md#200-2021-01-22
Cependant je n'ai pas l'impression que casl/vue soit utilisé, donc je l'ai supprimé
> COM-2583 - Fix @casl/vue vversion

- src/modules/client/pages/ni/auxiliaries/AuxiliaryProfile.vue
Quand j'arrive sur le fiche auxiliaire, je n'ai plus les messages d'alerte sur la reactivité des onglets. Je peux changer d'onglet sans souci
en creusant cette histoire de message d'alerte sur la reactivité des composant, je me suis dit qu'n fait, on pouvait créer un tabContent qui n'est pas reactif : passer en APi de composition et ne pas utiliser le ref. On a un objet JS classique et pas une donnée reactive
> COM-2583 - Fix reactivity warning

- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/mixins/planningModalMixin.js
- Périmetre interface :  client coach/admin/auxiliaire
- Périmetre roles : Je peux éditer des congés payées a la demi-journée
- editer une absence demi-journalière
- exporter l'historique des absences et verifier que les absences demi-journalière sont bien prises en compte
> COM-2605 - half-daily absence edition

- src/core/components/courses/ProfileAdmin.vue
- src/core/components/courses/ProfileTraineeFollowUp.vue
- Sur drive, j'ai créé un modele de certificat de fin de formation pour dev specifiquement
- Sur heroku, j'ai modifié le lien vers le certificat pour pointer vers mon modele nouvellement créé
- Périmetre interface : client / vendeur
- Périmetre roles :   rof / coach
- Je peux telecharger les attestations de fin de formation non plus dans l'onglet "Admin" mais dans "Suivi des stagiaires"
- Si les infos necessaires ne sont pas remplies (un stagiaire, un créneau, un.e formateur.ice avec tel) le bouton est grisé.
- Si les objectifs peda du programme ne sont pas remplis, le bouton est grisé et une banniere m'informe
- Lorsque je genere une attestation, la durée de presence du/de la stagiaire est inscrite automatiquement
- Comment tester: 
- dans les .env coté API, modifier …
> COM-2612 move completion certificates

- src/core/components/learners/ProfileCourses.vue
- Périmètre interfaces / rôles : vendeur/client admin_vendeur/admin_client/coach/rof
- Cas d'usage : je peux visualiser les présences dans les formations suivies sur le profil d'un apprenant
- Comment tester ? : se mettre sur le profil d'un apprenant et en comparant avec ce qu'on a sur l'appli mobile et les émargements sur les formations s'assurer pour chaque formation: 
- que la progression elearning totale est la bonne
- que la présence totale est la bonne
- que la progression elearning de chaque étape est la bonne
- que la présence pour chaque étape est la bonne
- ⚠️ : 
- si absence à tous les créneaux => 0h /xh
- si elearning pas fait 0%
- si pas de créneaux (progression totale) => vide
- si pas de elearning (progression totale) => vide
- si pas de créneaux dans l'étape => 0h/0h
_Si …
> COM-2615: display presence progress

- src/core/components/learners/ProfileCourses.vue
- Périmètre interfaces / rôles :  vendeur/client   client_admin/coach/vendor_admin/rof
- Cas d'usage : quand le créneau d'une étape n'est pas encore passé au lieu d'être noté "absent", on a la mention "à venir"
- Comment tester ? : regarder la fiche apprenant d'un stagiaire inscrit à une formation dont certains créneaux ne sont pas passés => ils doivent être marqué "à venir"
> COM-2642: add to come mention for slot to come

- src/core/components/learners/ProfileCourses.vue
- Périmètre interfaces / rôles : client/vendeur rof/admin/coach
- Cas d'usage : changement du style de la mention à venir pour les créneaux non passés dans le récap des émargements d'un apprenant
- Comment tester ? : regarder le tableau d'un stagiaire inscrit à une formation ayant des créneaux à venir
> COM-2642: change 'to come' mention style

- src/core/data/constants.js
- src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
- src/modules/client/components/customers/billing/ManualBillCreationModal.vue
- src/modules/client/pages/ni/billing/CreditNotes.vue
- Périmètre interfaces / rôles : client
- Cas d'usage : Je peux créer un avoir sur les articles manuels
Créer un avoir avoir lié à des articles de facturations.
La création d'avoir étant complexe, je vous conseille de créer un avoir sur les souscriptions et un avoir lié à des évènements.
Essayer sur un bénéficiaire avec et sans tpp, avec plusieurs souscriptions, essayer avec plusieurs articles  de facturations, changer les prix / quantité des articles.
⚠️ Le filtre sur les options de articles de facturations n'est pas possible à faire facilement (limitation de quasar). Vu avec Romain : on bloque l'ajout de doublon en front et en back
> Com 2657 2

- src/modules/client/components/planning/EventHours.vue
- src/modules/client/mixins/planningEventMixin.js
- Remarques de Romain:
- La nouvelle couleur des horaires rend le contraste très faible sur les heures internes : peut-on passer les horaires copper/700 finalement ?
- Par ailleurs, je me rends compte que le fait de mettre les 3 premières lettres du prénom font qu’on ne voit même plus les premières lettres du nom, pour un mobile avec écran étroit, comme c’est mon cas. Dans le design que proposait Félix, ça marchait, mais c’est parce qu’on avait réussi à gagner de l’espace horizontal. Du coup finalement, désolé, mais revenir sur R.Delenda (en revanche, continuer à retirer l’espace après le point, pour gagner de la place) 
- ETQ Coach/Auxiliaire, sur le planning auxiliaire:
- le titre de la cellule est P.NOM
- l'horaire et l'icones d'horodatage sont visibles pour les …
> COM-2659 - fix Romain's reviews

- src/modules/client/mixins/subscriptionMixin.js
- src/modules/client/pages/customers/Subscriptions.vue
- ~~[ ] J'ai ajouté une variable d'environnement~~
- Périmètre interfaces / rôles : client / admin -coach
Lorsque j'ajoute/édite une souscription avec une majoration le samedi -> je retrouve l'info dans l'historique
J'ai aussi l'info dans l'export des données de souscriptions
Dans profil benef onglet infos -> ajoute/édite une souscription avec une majoration le samedi -> clique sur le bouton historique
Télécharge  l'export des données de souscriptions
> COM-2710 - Add saturday to subscription history and data export

- src/modules/client/pages/ni/planning/CustomerPlanning.vue
- Périmètre interfaces / rôles : client admin/coach/auxiliaire
- Cas d'usage : quand j'édite une absence bénéficiaire j'ai une modale de confirmation + boyscout retrait du paramètre inutile de updateCustomerAbsence
- Comment tester ? : modifier une absence bénéficiaire et s'assurer qu'on a bien la modale de confirmation
> COM-2695: add confirmation modal

- src/modules/client/components/customers/infos/ProfileInfo.vue
- Périmètre interfaces / rôles : COACH
- Cas d'usage : Les validations fonctionnent pour tous les cas de tests ci-dessous.
Je ne peux pas creer/editer de souscription:
- liee a un service forfaitaire si : 
- `Prix unitaire TTC` est nul
-  `Nombre d'interventions hebdomadaire estimatif` est nul 
- liee a un service horaire sans article de facturation si:
-  `Prix unitaire TTC` est nul
- `Volume horaire hebdomadaire estimatif ` est nul 
- liee a un service horaire avec article de facturation si:
- `Prix unitaire TTC` est nul
- `Volume horaire hebdomadaire estimatif ` est nul 
- `Nombre d'interventions hebdomadaire estimatif` est nul
Je peux creer/ editer des souscriptions.
> Com 2709 fix

- src/modules/client/components/customers/SubscriptionCell.vue
- src/modules/client/components/customers/infos/ProfileInfo.vue
- src/modules/client/mixins/subscriptionMixin.js
- src/modules/client/pages/customers/Subscriptions.vue
- ~~[ ] J'ai ajouté une variable d'environnement~~
- Périmètre interfaces / rôles : aidant
Refacto du design des souscriptions de l'aidant
Comparer le design au [Figma](https://www.figma.com/file/PlYziIhmznu7y7EEK7uoBD/Prochain-Sprint?node-id=8630%3A38242) pour des souscriptions en jouant sur : le prix, la nature du service, les majorations, les financements, ...
Vérifier aussi que le tableau des souscription côté coach n'a pas cassé
> COM-2690 - Visual refacto for helpers subscriptions

- src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
- src/modules/client/components/customers/billing/CustomerBillingTable.vue
- Périmètre interfaces / rôles : client / admin / coach / aidant
Sur le pdf de l'avoir (bénef / tpp), je vois le motif de l'avoir s'il existe
Pour un benef, faire plusieurs avoir : avec / sans motif, avec / sans tpp. Vérifier que le motif apprait bien où il doit apparaitre sur le pdf + dans le tableau
> COM-2734 - Add misc to credit note pdf

- src/core/components/learners/ProfileCourses.vue
- src/core/helpers/date.js
- src/modules/vendor/components/programs/ProfileContent.vue
- src/modules/vendor/components/programs/StepEditionModal.vue
- Cas d'usage : dans la modale d'édition d'une étape, les heures et les minutes sont séparées
- sur la branche dev (local) rajouter une durée théorique à une étape
- se mettre sur la branche de la PR : 
- la durée théorique affichée n'a pas changée
- quand j'ouvre la modale, celle-ci contient les bonnes infos
- quand je modifie la durée, elle s'affiche correctement et j'ai la bonne durée en base  
> COM-2718: change theoretical hours in modal

- src/core/helpers/date.js
- src/modules/vendor/components/programs/ProfileContent.vue
- Périmètre interfaces / rôles : vendeur/client rof/admin coach/admin
- Cas d'usage : quand je défini une durée d'étape, je ne suis pas obligé de définir heures ET minutes si l'un des deux vaut 0 (ex: je peux remplir juste le champ heure pour une étape d'une heure) + boyscout sur le format des heures : 
- heures + minutes = xh xxmin ou xxh xxmin (1 chiffre pour l’heure < 10, 2 chiffres pour l’heure > 10, 2 chiffres pour les 
- minutes peu importe le nombre de minutes)
- heures = xh (1 chiffre pour l’heure < 10, 2 chiffres pour l’heures > 10, rien pour les minutes)
- minutes = xxmin (rien pour les heures, 2 chiffres pour les minutes peu importe le nombre de minutes) 
- modifier une durée d'étape avec une heure pile (exemple 2h) sans spécifier les minutes => j'ai la …
> COM-2718: required if other field not defined + boyscout format

- src/css/app.sass
- src/modules/client/components/customers/SubscriptionCell.vue
- Périmètre interfaces / rôles : aidant
Fix des retours de Romain : 
```
Rajouter “ / semaine” après le montant pris en charge, cf maquettes mises à jour
Rajouter le petit texte “(cette estimation peut varier selon l’évolution du plan d’aide et du volume horaire)” sous la ligne concernant le TP, cf maquettes mises à jour. Attention, notez bien que c’est en police 12, plus petit que le reste du texte
Lorsque le financement est forfaitaire, actuellement ça affiche une prise en charge de 0,00€. Ce que je propose : ne pas afficher la ligne relative à la prise en charge lorsque le financement est forfaitaire.
```
Vérifier que les retours de Romain sont pris en compte
> COM-2690 - Fix Romain's review

- src/modules/client/pages/ni/billing/ToBill.vue
- Périmètre interfaces / rôles : Client amdin
- Cas d'usage : Quand je télécharge un fichier de télétransmission, j'ai un loader sur le bouton de la modal
S'assurer d'avoir un tiers payeur en télétransmission + des bénéficiaires avec un financement sur ce tiers-payeur et des interventions sur ce mois
Sur la page "A facturer", ouvrir la modal de teletransmission, sélectionner ce tiers-payeur et le mois en cours
Valider le téléchargement => le loader tourne le temps de la requête
> COM-2743 - add loading

- src/core/components/courses/CourseBilling.vue
- src/modules/vendor/components/billing/CourseFeeEditionModal.vue
- Périmètre interfaces / rôles : formation vendeur / rof
- je ne peux pas modifier le prix ou la quantité d'une commande de base qd la facture est facturée.
- NB: je n'ai pas pris en compte les autres points du ticket
- sur une facture facturée
- sur la commande de base, les champs prix et quantité sont grisés
- sur la commande de base, je peux modifier la description
- sur une facture non facturé
- sur la commande de base,  je peux toujours modifier ce que je veux
- sur la branch dev coté webapp (et COM-2731 coté api)
- lorsque je modifie le prix ou la qtt, j'ai une erreur qui pop 
> COM-2731 deisable mainFee.count and mainFee.price when billed

- src/modules/client/pages/ni/courses/ELearningCourseProfile.vue
- src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
- Périmètre interfaces / rôles : formation vendeur et formation client / cof et coach
- sur une fiche formation eLearning, je peux voir la durée totale de la formation 
- sur une fiche formation elearning coté client : vérifier la durée 
- sur une fiche formation elearning coté vendeur : vérifier la durée 
- verifier que ca ne change rien sur les fiches formations mixtes coté client et vendeur
> COM-2720 print total elearning duration:

- src/core/components/courses/CourseBilling.vue
- Périmètre interfaces / rôles : formation vendeur
- blocage de toutes les modifications sur une facture facturée (excepté les descriptions de commande)
- le crayon d'edition du payeur a disparu
- le bputon d'ajout d'article a disparu
- sur la modale d'edition d'une commande d'article, les champs prix et qtt sont grisés 
> Com 2731 2

- src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
- Périmètre interfaces / rôles : auxi
Fix des retours de Corentin
Regarder que j'ai bien fix les retours de Corentin : 
- on pourrai mettre “visible par les clients” (comme on a decidé que le masculin pluriel est “neutre” dans compani)
- Tu as rajouté un point dans le pdf, du coup ca en fait deux quand l’utilisateur.ice en a deja mis un dans la modale. Je pense qu’il ne faut pas en ajouter.
> COM-2734 - Fix Corentin's reviews

- src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
- Périmètre interfaces / rôles : client / coach - admin
Dans la modale d'édition d'un tier payeur, si j'ai rempli le champ de `ID de télétransmission`, les champs Identifiant structure et Type d'aide sont affichés comme requis
C'est assez explicite
> COM-2729 - Fix Ulysse's reviews

- src/core/components/courses/CourseBilling.vue
- src/modules/vendor/components/programs/StepEditionModal.vue
- Cas d'usage : boyscout : plus d'astérisque sur le deuxième champ de la modèle d'édition d'étape + je ne peux plus ouvrir la modale d'édition de financeur si la facture est facturée
- Comment tester ? : c'est explicit ⬆️ 
> mini-fixes-mes-22-03: minor fixes

- src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
- Périmètre interfaces / rôles : compani outils / admin
- Cas d'usage : dans la modela d'edition d'un tiers payeur,  je peux suppprimer le type d'aide si il n'y a pas d'ID de teletransmission
- Comment tester ? : supprimer l'id => le select devient "vidable"
> COM-2729-fix-2 type is clearable

- test/cypress/plugins/index.js
- Périmètre interfaces / rôles : -np
- Cas d'usage : Suppression du warning quand on lance un test avec cypress
- Comment tester ? : Lancer un test avec cypress, il ne devrait pas y avoir le warning 
```
Deprecation Warning: The before:browser:launch plugin event changed its signature in version 4.0.0
```
Note : je pense que notre version de cypress est definie par l'extension que l'on utilise pour utiliser cypress avec quasar. J'ai vu qu'il y avait une nouvelle version de cette extension --> je propose d'en faire un ticket en dehors du sujet que l'on traite actuellement. Qu'en penses-tu ? 
> COM-2766 remove warning on test launch

- package-lock.json
- package.json
- test/cypress/integration/auxiliary/planning/auxiliaryAgenda.spec.js
- test/cypress/integration/customer/agenda.spec.js
- test/cypress/integration/customer/subscription.spec.js
- test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js
- test/cypress/support/index.js
- Périmètre interfaces / rôles :np
- Cas d'usage : Remplacement de Cypress.moment par luxon pour reparer le probleme du numero de la semaine. Je n'ai pas beaucoup creusé pourquoi est-ce que Cypress.moment ne nous renvoyait pas les bonnes valeurs car je suis assez vite tombé sur les changelog de cypress, qui indiquait que Cypress.moment etait deprecie et supprimé dans une version superieur. Du coup j'ai remplacé par luxon. (Dans l'exemple de cypress, ils utilisaient dayjs mais je me suis dit qu'il vallait mieux qu'on utilise luxon)
https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/blogs__dayjs/cypress/support/index.js
https://docs.cypress.io/guides/references/changelog#7-0-0
- Comment tester ? : Vérifier que les tests modifiés par cette pr passent bien 
- …
> COM-2769 use luxon instead of cypress.moment

- src/modules/client/pages/ni/config/CustomersConfig.vue
- src/modules/vendor/pages/ni/billing/BillingConfig.vue
- Cas d'usage : je ne peux pas supprimer un financeur s'il est utilisé pour une facture (validée ou non)
- créer un financeur
- l'assigner à une facture => je ne peux plus le supprimer
- le désassigner de la facture => je peux le supprimer
- valider la facture avec le financeur => je ne peux plus le supprimer
- faire ces tests pour le disable en front et pour le blocage back (retirer le disable pour tester cette deuxième façon) 
> COM-2751: disable button + boyscout

- src/core/components/courses/CourseBilling.vue
- Périmètre interfaces / rôles : formation / rof
- je vois plus d'info sur une facture
- le numero de la facture, la date
- le nom. l'adresse et le siret du créditeur
- le nom et l'adresse du debiteur
- le nom de la structure cliente
- un footer avec un rappel sur la TVA
- sur demande de ROmain, j'ai bloqué la facturation si il manque l'adresse du debiteur (pas de financeur et il manque l'addresse de la structure cliente)
- verifier toutes les infos sur une facture telechargée 
- ajouter un financeur sur une facture, verifier le nom et l'adresse du financeur sur la facture
- ne pas ajouter de financeur, verifier le nom et l'adresse de la structure cliente sur la facture
- valider une facturation sans adresse sur la structure cliente (qui est aussi le …
> COM-2753 forbid bill validation if no client address

- src/core/api/GoogleDrive.js
- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/helpers/file.js
- src/modules/client/components/customers/billing/CustomerBillingTable.vue
- src/modules/client/composables/taxCertificates.js
- src/modules/client/mixins/customerMixin.js
- Périmètre interfaces / rôles : tous 
- Cas d'usage : lorsque je télécharge un document il se télécharge vraiment il ne s'ouvre pas dans l'onglet courant ou dans un autre onglet (sur Firefox les pdfs continuent de s'ouvrir dans un autre onglet en plus de se télécharger)
pour comprendre la fonction getExtension : https://www.ibm.com/docs/en/wkc/cloud?topic=catalog-previews certains mimeType correspondent à l'extension (pdf, les images) et d'autres doivent être modifié pour que ça colle (docx, xlsx, txt)
- Comment tester ? : télécharger le plus de type de fichiers différents (pdf, jpeg, docx, txt...) sur plusieurs navigateurs (Chrome, Firefox, Safari)
> COM-2780: download files

- src/core/components/courses/ProfileBilling.vue
- src/core/components/table/ExpandingTable.vue
- src/core/data/constants.js
- src/core/helpers/utils.js
- src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
- Périmètre interfaces / rôles : vendeur /rof/admin
- Cas d'usage : sur le profil d'une structure je peux visualiser ses factures avec leur détail + boyscout bloquer date d'avoir antérieure à facturation
- facturer une formation
- sur le profil de la structure associée la facture apparait bien (aucun règlement)
- lui ajouter des règlements/remboursements => ils apparaissent dans le détail et les colonnes solde et réglé/crédité sont mises à jour
- faire un avoir sur la facture => je ne peux pas mettre une date d'avoir antérieur à la date de facturation + il apparait bien dans le détail et les colonnes solde et réglé/crédité sont mises à jour
- facturer une autre formation de la même structure
- refaire les étapes précédentes
- le solde total est le bon
_Si tu as lu …
> COM-2773: add columns

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/SlotContainer.vue
- src/modules/vendor/components/courses/CourseCreationModal.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
- Cas d'usage : je peux ajouter une date de démarrage souhaitée pour une formation
- sur la branche dev exporter les formations pour une période donnée
- faire de même sur cette branche et s'assurer qu'on a bien la même chose (à l'exception de certains champs de "comptage" ou le vide a été remplacé par 0
- créer une formation avec une date de démarrage dans la période précédemment utilisée et exporter les formations => j'ai bien ma formation dans l'export
- ajouter un créneau à la formation, en dehors de la période donnée => la date de démarrage ne s'affiche plus sur le profile de la formation + la formation n'est plus dans l'export 
> COM-2792: display estimated start date field

- src/core/components/courses/ProfileBilling.vue
- src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
- Cas d'usage : lorsque je crée un avoir, dans la modale j'ai une référence à la facture associée, à son prix et au nom de la formation
- Comment tester ? : créer un avoir sur une formation et s'assurer qu'on a les bonnes infos dans la modale de création
> COM-2772: add text and subtext in modal

- src/modules/client/components/customers/infos/ProfileInfo.vue
Périmètre interfaces / rôles : coach
Cas d'usage : Modification des countDocuments de countSubscriptionUsage pour n'avoir que 0 ou 1 suivant si la subscription est lié à un évènement ou non.
Comment tester ? :
Sur la page profile d'un bénéficiaire, je ne peux pas supprimer une souscription si il a au moins un évènement ou une repetition. --> Seul endroit ou les champs sont effectivement utilisés
Autres endroits à vérifier car il y a l'utilisation de Customer.findOne
- Je peux supprimer un bénéficiaire
- Je peux générer un qrcode pour un bénéficiaire
- Je peux créer une répétition
- Je peux créer et modifier un financement
- Je peux modifier le rib d'un beneficiaire et je vois un nouveau mandat
- ETQ aidant je peux signer un mandat
- Je peux générer un devis
- Je peux changer le referent …
> COM-2823 rename field

- src/modules/vendor/components/companies/ProfileBilling.vue
- Cas d'usage : quand je clique sur le nom d'une formation depuis l'onglet factu sur une fiche structure, je ne peux cliquer que sur le nom pour être redirigé et non plus juste à côté du nom
- Comment tester ? : cf cas d'usage
> COM-2791: can't click outside of program name

- src/modules/client/components/customers/billing/DeliveryDownloadModal.vue
- src/modules/client/pages/ni/billing/ToBill.vue
- Périmètre interfaces / rôles : admin
- Cas d'usage : sur la facturation, je peux telecharger le doc de teletransmission uniquement pour les evenements passés
- Comment tester ? : telecharger le fichier de teletransmission pour le mois entier et uniquement pour les evenements passés et verifier que c'est coherent + verifier que pour l'id CIDDHExchangedDocument, on a bien l'id de l'evenement
> COM-2833 add checkbox in teletransmission for onlyPastEvents

- src/core/components/courses/CourseHistory.vue
- src/core/components/courses/SlotContainer.vue
- src/core/components/courses/SlotEditionModal.vue
- Périmètre interfaces / rôles : vendeur/client rof/admin_vendeur/admin_client/trainer/coach
- Cas d'usage : seul les admin vendeur/rof peuvent créer et supprimer des créneaux + boyscout création d'historique : meetinglink pris en compte + pas d'historique à la suppression de créneaux à planifier
- côté vendeur (rof/admin) : 
- créer un créneau dans une formation => je ne peux pas le supprimer si c'est le seul de l'étape
- je supprime un créneau à planifier => je n'ai pas d'historique créé
- je créé/supprime un créneau d'une étape distancielle avec un lien de visio => le lien est dans l'historique
- côté client (coach/admin) / côté vendeur (trainer) : 
- je ne peux pas supprimer ni créer de créneau
- je peux éditer un créneau   
_Si tu as lu cette description, pense …
> COM-2816: hide button for clients

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/SlotContainer.vue
- src/css/quasar.variables.sass
- Périmètre interfaces / rôles : client/vendeur coach/rof/trainer
- Cas d'usage : les créneaux sont rangés par étape, en tant que rof je peux les créer, en tant que coach/formateur je peux les modifier : 
- bloc blanc => étape elearning / pas d'interaction
- bloc orange => étape avec des créneaux à planifier
- bloc bleu => étape sans créneaux à planifier
- si je rajoute des créneaux à planifier dans une étape bleu => orange
- si je rempli des créneaux à planifier dans une étape orange => bleu
- Comment tester ? :  
- en tant que rof : 
- je peux créer des créneaux à planifier dans une étape
- je peux modifier des créneaux
- en tant que coach/trainer : je peux modifier des créneaux  
> COM-2837: display slots by step

- src/core/components/courses/SlotContainer.vue
- Périmètre interfaces / rôles : rof/admin/coach/trainer
- Cas d'usage : retour de Romain : les créneaux à planifier sont en dessous des créneaux déjà planifier dans une cellule d'étape
- Comment tester ? : ajouter un créneau à planifier à une étape => il s'affiche en dessous des créneaux déjà planifier dans l'étape
> COM-2837: move slots to plan section

- src/core/helpers/numbers.js
- src/core/helpers/utils.js
- src/modules/client/pages/ni/billing/CreditNotes.vue
- Périmètre interfaces / rôles : admin client
- Cas d'usage : je peux creer un avoir lié a des interventions pour un tiers-payeur (la validation bloquait la creation car le format de inclTaxesTpp et inclTaxesCustomer n'était pas bon)
-  voir description api
> COM-2858 - round inclTaxes amounts to pass validations

- src/modules/client/pages/ni/config/RhConfig.vue
- Périmètre interfaces / rôles : client admin
- Cas d'usage : ETQ admin, je peux paramétrer la comptabilité des jours fériés dans les heures travaillées
- lancer le script 
- se connecter avec son compte 
- sur la page `configuration RH` dans  l'onglet Contrats prestataires la checkbox les jours fériés ne sont pas travaillés` apparait cochée
- la cocher puis la décocher et verifier que la modification s'effectue en bdd
- creer une nouvelle structure
- lui ajouter un administrateur
- se connecter avec ce compte 
- sur la page `configuration RH` dans  l'onglet Contrats prestataires la checkbox `les jours fériés ne sont pas travaillés` apparait décochée
- la cocher puis la décocher et verifier que la modification s'effectue en  bdd
_Si tu as lu cette description, pense a …
> COM-2861 - add shouldPayHolidays checkbox

- src/core/components/courses/ProfileBilling.vue
- Cas d'usage : sur le profile d'une structure, je peux voir les factures pour lesquelles la structure est le payeur
- facturer une formation d'une structure A avec une structure B en payeur
- la facture apparait sur le profile de la structure A et de la structure B 
> COM-2812: add companies as possible payers

- src/modules/client/pages/ni/billing/ClientsBalances.vue
- Périmètre interfaces / rôles : admin client
- Cas d'usage : Bug -  sur la page balances clients, lorsque l'on sélectionne la checkbox dans le header du tableau, seuls les beneficiaires 'prelevables' sont selectionnés
- dumper la prod en local
- se placer sur dev 
- sur la page balances clients, sélectionner la checkbox dans le header du tableau (sélection multiple)
- prelever les bénéficiaires --> ko
- se placer sur cette branche 
- sur la page balances clients, sélectionner la checkbox dans le header du tableau (sélection multiple)
- prelever les bénéficiaires --> ok 
- verifier que les bénéficiaires ont bien ete prélevés (sur la fiche beneficiaire --> onglet facturation)
> COM-2863 - fix q-checkbox multiple selection

- src/modules/client/pages/ni/billing/TppBillSlips.vue
- Périmètre interfaces / rôles : client admin 
- Je peux télécharger les bordereaux tiers-payeur, les montants affichés sont justes et tiennent compte des remises.  (avant on ne prenait pas en compte les remises, il y avait donc un écart entre le montant total figurant sur le bordereau correspond au montant affiché dans la colonne `Montant TTC` de la page bordereau tiers-payeur )
- Lorsque je telecharge un avoir sur des interventions, les montants sont justes (`total TTC - total HT = tva`) 
- voir sur la PR back 
> COM-2834 - use formatStringToPrice

- src/modules/client/pages/ni/courses/BillingProfile.vue
- src/modules/vendor/components/companies/ProfileBilling.vue
- Périmètre interfaces / rôles : vendeur/client rof/admin
- Cas d'usage : les règlements sont bien alignés dans le tableau des factures + rajout d'un s au titre de la page côté client
le bug venait de l’utilisation de white-space:no wrap dans la classe ellipsis qui change l’espacement pour une raison que j’ignore. Or cette props est obligatoire pour que l’ellipsis se fasse en css du coup pour contourner le problème j’ai dû essayer de reproduire l’ellipsis en JS plutôt qu’en CSS
- tableau des factures (onglet facturation du menu formation côté client / onglet facturation de la fiche structure côté vendeur : 
- côté client : le titre de la page est Facture**s**
- côté client et vendeur lorsque j'ajoute un règlement, le montant de celui-ci est aligné avec la colonne …
> COM-2843: fix wrong alignment on table

- src/modules/client/pages/ni/billing/ManualBills.vue
- Périmètre interfaces / rôles : ETQ admin
- Cas d'usage : Lorsque je créé une facture manuelle, je peux envoyer un mail d'information a l'aidant.
- creer une facture manuelle en sélectionnant 'Envoyer par email'
- vérifier qu'en bdd la facture a ete cree avec le champ `shouldBeSent` a true
- creer une facture manuelle en désélectionnant 'Envoyer par email'
-  vérifier qu'en bdd la facture a ete cree avec le champ `shouldBeSent` a false
- ajouter un aidant au beneficiaire pour lequel la facture a ete créée
- Verification de l'envoie d'email:
- Dans `BillRepository` > `findBillsAndHelpersByCustomer`, commenter la ligne `$lt: moment(date).add(1, 'd').startOf('d').toDate(),` pour recuperer les factures du jour
- Sur postman: appeler la route `GET /scripts/bill-dispatch` …
> COM-2872 - add q-dialog + use api composition

- src/core/components/courses/SlotContainer.vue
- Périmètre interfaces / rôles : vendeur/client rof/admin
- Cas d'usage : quand je survole le lien d'un créneau distanciel il se souligne
- Comment tester ? : sur une étape distancielle rajouter 4 créneaux
- créneau à planifier => comme actuellement
- créneau avec lien court => il s'affiche intégralement, au survol il se souligne, au clic il s'ouvre dans un autre onglet
- créneau avec lien long => il est ellipsé, au survol il se souligne, au clic il s'ouvre dans un autre onglet
- créneau sans lien => "lien vers la visio non renseigné s'affiche intégralement, pas de soulignement au survol, au clic il ouvre la modale 
> COM-2880: underline link on hover + style

- src/core/helpers/rbac.js
- src/modules/client/mixins/menuItemsMixin.js
- src/modules/client/pages/ni/planning/RepetitionsPlanning.vue
- src/modules/client/router/routes.js
- Périmètre interfaces / rôles : Planning référent / Coach / Admin client
- Cas d'usage : J'ai accès à la page `Gérer les répétitions`
- Comment tester ?  
- Se connecter ETQ Admin client --> la page est accessible et s'affiche bien (Pour le moment on a que le titre)
- Se connecter ETQ référent planning --> la page est accessible et s'affiche bien (Pour le moment on a que le titre)
-  Se connecter ETQ coach --> la page est accessible et s'affiche bien (Pour le moment on a que le titre)
-  Se connecter ETQ auxiliaire --> la page n'est pas accessible 
> COM-2897 - create repetitions screen

- src/core/components/courses/CourseInfoLink.vue
- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/ProfileTraineeFollowUp.vue
- src/core/mixins/courseMixin.js
- Périmètre interfaces / rôles : vendeur/client admin/rof/coach
- Cas d'usage : sur l'onglet organisation j'ai une section Documents Utiles avec la convocation et les feuilles d'émargement
- sur une formation intra, en bas de l'onglet organisation je peux télécharger la convocation et les feuilles d'émargement, dans l'onglet suivi des stagiaires je peux toujours télécharger les feuilles d'émargement 
> COM-2877: move usefull docs section

- src/modules/client/components/planning/EventEditionModal.vue
- Périmètre interfaces / rôles : client admin/coach/auxiliaire
- Cas d'usage : sur petit écran les bouton rétablir/annuler et corbeille sont espacés
- sur grand écran le toggle et les deux boutons sur sur la même ligne
- sur petit écran les deux boutons son à la ligne et espacés 
> COM-2821: on small screen space between both buttons

- src/modules/client/mixins/menuItemsMixin.js
- src/modules/client/router/routes.js
- Périmètre interfaces / rôles : ETQ Coach / Admin Client / Planning referent 
- Cas d'usage : Je peux supprimer une repetition.
- supprimer des repetitions qui sont reliées a des evenements 
- vérifier en bdd que les evenemnts postérieurs a la Date entrée ont ete supprimés
- verifier que la repetition est supprimée
- supprimer des repetitions non rattachées a des evenements
- verifier que la repetition est bien supprimee 
> COM-2899 - restore repetition menu

- src/modules/client/pages/ni/billing/CreditNotes.vue
- src/modules/client/pages/ni/billing/ManualBills.vue
- Périmètre interfaces / rôles : client admin
- Cas d'usage : Les montants figurant sur une facture manuelle et sur un avoir sur des articles de facturation sont justes.
Exemple de combinaison qui donnait des factures / avoirs avec des montants incohérents
- generer une facture manuelle
- verifieer que tous les montants sont coherents (dans la modale de creation et sur la facture)
- generer un avoir sur les articles de facturation
- verifier que tous les montants sont coherents (dans la modale de creation et sur la facture)
- vérifier que les montants sont justes dans la modale d'édition d'un avoir 
> COM-2893 - fix customereInclTaxese and customerExclTaxes  on creditNotes

- src/modules/client/components/table/ToBillRow.vue
- Périmètre interfaces / rôles : Admin client
- Cas d'usage : Sur la page A facturer, je peux enregistrer une remise négative
- Sur la page A facturer, je peux enregistrer une remise négative
- Sur le PDF de la facture, la remise apparait en positif et incrémente le montant final
> COM-2970 - allow negative discount

- src/modules/vendor/components/courses/CourseCreationModal.vue
- src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
- Périmètre interfaces / rôles : ROF
- Cas d'usage : depuis le kanban des formations, quand je crée une formation mixte INTRA, je peux définir un nombre max d'inscrits
- Comment tester ? 
- lancer le script mep66.js 
- creer une formation mixte intra
- tester les validations du champ "Nombre d'inscrits max"
- creer une formation inter   
> COM-2980 - add maxTrainees to intra courses

- src/modules/vendor/components/programs/ProfileContent.vue
-  je ne peux pas rajouter une activité à une étape présentielle ou distancielle
> COM-2983: can't show activity on non-elearning step

- src/modules/client/pages/ni/billing/ClientsBalances.vue
- src/modules/client/pages/ni/billing/ToBill.vue
- Périmètre interfaces / rôles : compani outil / coach
- sur les pages "a facturer" et "balance client", la scrollbar ne cache plus les checkbox de l'entete et du corps des tableaux
- j'ai mis une div autour car <th> n'a pas l'air d'accepter la prop `class` et sur la doc yen a pas d'autre pour appliquer du style
- verifier sur la page  a facturer
- verifier sur la page balance client
> COM-2957 add margin right to checkbox

- src/core/components/courses/ProfileOrganization.vue
- src/core/components/courses/SmsSendingModal.vue
- Périmètre interfaces / rôles : coach/rof
- Cas d'usage : je peux envoyer un sms aux apprenants
- Comment tester ? : vérifier que le type de sms par defaut et le bon et que l'on peut envoyer : 
- tout type si la formation n'a pas commencé
- rappel ou autre tant qu'il reste des créneaux planifies dans le futur
- autre sinon
> COM-3002 add other type message

- src/core/components/courses/BlendedCourseProfileHeader.vue
- src/core/components/courses/SlotContainer.vue
- src/core/components/form/DatetimeRange.vue
- src/core/helpers/dates/companiDate.js
- src/modules/client/components/planning/EventCreationModal.vue
- src/modules/client/components/planning/EventEditionModal.vue
- Périmètre interfaces / rôles : vendeur/client rof/admin/coach/formateur
- Cas d'usage : le créneau par défaut est de 3h30 (9h00-12h30) pour les formations
- créer et éditer des événements : rien ne change (créneau par défaut 8h-10h => +2h quand on bouge l'heure de début après l'heure de fin)
- éditer créneau formation : 9h-12h30 par défaut => + 3h30 quand on bouge l'heure de début après l'heure de fin
> COM-3001: change default slot

- src/core/components/form/DateRange.vue
- src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
- src/modules/client/components/planning/DeleteEventsModal.vue
- Périmètre interfaces / rôles : coach/auxiliaire
- Cas d'usage : Dans une modale au blur, on n'affiche pas de Notifywarning
- Comment tester ? : Le notify warning ne s'affiche pas au blur sur les dateRange dans les modales (modification et creation d'une absence beneficiaire). Dans les autres cas, le notify warning s'affiche bien : 
- Pages d'exports (client et vendeur)
- Page de facturation sur le profile beneficiaire (ou sur page cote aidant)
- Page A facturer
- Tableaux de bords formation
- Page Absences
- Page Contrats
> COM-2990 dont show notify warning if not in modal for date range

- src/modules/client/components/planning/EventCreationModal.vue
- Périmètre interfaces / rôles : client coach/admin
- Cas d'usage : je n'ai plus d'appels à la routes absence quand je quitte la modale de création/édition absence
- tester que je peux toujours créer des absences, les prolonger, etc.
- je n'ai plus d'appel à la route absence à la fermeture de la modale (comparer avec dev pour se rendre compte) 
> COM-2964: remove useless call to absences route

- src/core/components/courses/SlotContainer.vue
- src/core/components/form/DatetimeRange.vue
- src/core/components/form/TimeInput.vue
- src/core/helpers/date.js
- src/core/helpers/dates/companiDates.js
- src/core/helpers/vuelidateCustomVal.js
- src/modules/client/components/planning/EventCancellationModal.vue
- src/modules/client/components/planning/EventCreationModal.vue
- src/modules/client/components/planning/EventEditionModal.vue
- src/modules/client/composables/planningAction.js
- src/modules/client/mixins/planningActionMixin.js
- src/modules/client/mixins/planningModalMixin.js
- src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
- src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
- src/modules/client/pages/ni/planning/CustomerPlanning.vue
- Périmètre interfaces / rôles :
- Cas d'usage : Dans le composant `datetimerange` si je mets une heure au format invalide, j'ai une erreur et je ne peux pas valider la modale
- Edition des créneaux de formation
- Sur le planning auxiliaire ET sur l'agenda auxiliaire
- Création d'une intervention
- Création d'une heure interne
- Création d'une absence
- Création d'une indispo
- Édition d'une intervention
- Édition d'une heure interne
- Édition d'une absence
- Édition d'une indispo
- Sur le planning bénéficiaire
- Création d'une intervention
- Édition d'une intervention
- Sur la page des absences :
- Édition d'une absence
- Coté horaire il faut aussi tester : 
- l'heure de debut est changé à postérieure a l'heure de fin => l'heur de fin passe a heure de debut + …
> Com 2991 time input

- src/modules/client/pages/ni/billing/CreditNotes.vue
- Périmètre interfaces / rôles : coach 
- Cas d'usage : je peux creer editer des avoirs d'interventions
Verifier que l'on peut creer/editer des avoirs d'intervention
_Note :_
_j'ai verifie qu'il n'y avait pas d'autres appels à toString qui semblaient problematique_
_j'ai l'impression que le probleme etait bien present avant, mais je pense que l'erreur ne nous remontait pas car une date invalide ne remontait pas d'erreur avant alors que maintenant CompaniDate renvoie bien une erreur_
> COM-3224 fix creation and edition of credit note

- src/core/components/courses/AttendanceSheetAdditionModal.vue
- src/core/components/courses/BlendedCourseProfileHeader.vue
- src/core/components/table/AttendanceTable.vue
- src/core/components/table/TraineeAttendanceCreationModal.vue
- Périmètre interfaces / rôles : rof
- migration de moment vers luxon sur le tableau des emargements
- boyscout :
-  j'ai mis un majuscule a l'importation de `CompaniDate` dans BlendedCOurseProfile
- j'ai enlevé le new Date() inutile et l'appel a l'ancien formatDate dans AttendanceSheetAdditionModal
- Vérifier l’affichage du tableau d’émargement
- Vérifier l’affichage des dates disponibles pour l’ajout d’une feuille d’émargement 
- Vérifier l’affichage des créneaux lors de l’ajout d’un stagiaire non inscrit à la formation
> COM-3219 replace moment with luxon

- src/core/components/courses/AttendanceSheetAdditionModal.vue
- src/core/components/form/Input.vue
- Périmètre interfaces / rôles : vendeur formateur/rof/admin
- Cas d'usage : je ne peux ajouter que des pdf et des images comme feuilles d'émargements
- essayer d'ajouter un autre type de fichier que image ou pdf comme feuille d'émargement => je ne peux pas
- je peux bien ajouter une image (jpg, png) ou un pdf comme feuille d'émargement
> COM-3202: block non image/pdf file upload

- .github/workflows/endToEnd.js.yml
- .github/workflows/lint.yml
Mise à jour des library `actions/checkout` et `actions/setup-node` car les actions utilisant node12 est bientot déprécié.
> COM-3371 update libraries for github actions

- .github/workflows/endToEnd.js.yml
Les tests cassent sur la PR de MES. Je ne sais pas trop pourquoi ils ne cassaient pas avant, mais je me suis demandée si ce n'était pas parce qu'on ne précisait pas sous quel version de node il fallait être. En ajoutant cette info, ca refonctionne (j'ai teste de lancer les github action en mettant comme base branche dev et master et les deux fonctionnent). 
> test defining node version

- package-lock.json
- package.json
- src/core/components/charts/LineChart.vue
- src/core/components/courses/ProfileFollowUp.vue
> COM-3697: update chart.js

- .github/workflows/endToEnd.js.yml
- quasar.conf.js
- src/core/components/courses/AttendanceSheetAdditionModal.vue
- src/core/components/table/AttendanceTable/Composables/AttendanceSheets.js
- src/core/components/table/AttendanceTable/index.vue
> COM-3842: add slot in modal attendance sheet
