src/components/table/PrefixedCellContent.vue

La branche s'appelle fix-few-bugs mais enfait elle en fixe qu'un seul ^^

delete cursor pointer on balance

---

package-lock.json
src/components/Modal.vue
src/components/auxiliary/ProfileInfo.vue
src/components/customers/ProfileInfo.vue
src/components/form/DatetimeRange.vue
src/components/form/TimeInput.vue
src/css/btn.styl
src/css/modal.styl
src/mixins/helperMixin.js
src/pages/ni/auxiliaries/Directory.vue

Cette PR concerne : 
- la mise a jour du time-input pour avoir une liste d'heure plutot que l'horloge et pouvoir rentrer n'importe quelle heure valide
- un changement sur le taille des modals car elle etait plus large qu'avant (cf modals du planning)
- le retrait du fond coloré au hover sur les boutton
- la mise a jour de l'erreur au moment de la creation d'un auxiliaire avec un email existant

COM-756 - Fix auxiliaries

---

src/components/form/Input.vue
src/components/table/EditableTd.vue
src/pages/signin/Authenticate.vue

Fix keyup enter event

---

quasar.conf.js
src/App.vue
src/components/DirectoryHeader.vue
src/components/auxiliary/ProfileInfo.vue
src/components/customers/ProfileFollowUp.vue
src/components/customers/ProfileInfo.vue
src/components/form/DateInput.vue
src/components/form/MultipleFilesUploader.vue
src/components/form/SearchAddress.vue
src/components/form/Select.vue
src/components/planning/PlanningModalHeader.vue
src/css/app.styl
src/css/drawer.styl
src/css/planning.styl
src/index.template.html
src/mixins/planningModalMixin.js
src/pages/auxiliaries/planning/AuxiliaryAgenda.vue
src/pages/customers/CustomerAgenda.vue
src/pages/customers/Subscriptions.vue

Pour le périmètre du ticket, les commits sont assez detaillés
COM-756 - update menu logo size
COM-756 - add ajax bar
COM-756 - update planning header height
COM-756 - update view mode on customer connection
COM-756 - fix directory header style
COM-756 - remove doble update on birthdaate
COM-756 - Add extensions to multiple file uploader
COM-756 - Add input in agenda select

Com 756 mobile design

---

src/components/ProfileHeader.vue
src/components/planning/EventCreationModal.vue
src/mixins/planningModalMixin.js
src/pages/ni/auxiliaries/Directory.vue
src/pages/ni/config/CustomersConfig.vue

Nom commercial obligatoire et limité à 11 caractères.

COM-793 Trade name is now mandatory and limited to 11 caracters.

---

src/components/menu/SideMenuAuxiliary.vue
src/components/menu/SideMenuCoach.vue
src/components/menu/SideMenuCustomer.vue
src/layouts/Layout.vue
src/mixins/sideMenuMixin.js

J'ai l'impression que ce n'était plus utilisé à part pour configuration.

remove highlight when entering a section in the menu

---

src/components/auxiliary/ProfilePay.vue

Sur fiche auxiliaire, onglet paie, suppression d'une fiche de paie.

COM-902 qdialog profile pay

---

src/components/ProfileHeader.vue
src/components/auxiliary/ProfileContracts.vue
src/components/auxiliary/ProfileInfo.vue
src/components/auxiliary/ProfilePay.vue
src/components/customers/ProfileInfo.vue
src/components/planning/DeleteEventsModal.vue
src/helpers/vuelidateCustomVal.js
src/mixins/configMixin.js
src/mixins/contractMixin.js
src/mixins/financialCertificatesMixin.js
src/mixins/helperMixin.js
src/mixins/planningActionMixin.js
src/pages/auxiliaries/planning/AuxiliaryAgenda.vue
src/pages/ni/billing/ClientsBalances.vue
src/pages/ni/billing/CreditNotes.vue
src/pages/ni/billing/ToBill.vue
src/pages/ni/config/CustomersConfig.vue
src/pages/ni/config/RhConfig.vue
src/pages/ni/pay/Absences.vue
src/pages/ni/pay/ToPay.vue
src/pages/ni/planning/AuxiliaryPlanning.vue
src/pages/ni/planning/CustomerPlanning.vue

- Suppression d'une version de contrat
- Suppression d'un évènement
- Suppression d'un justificatif d'absence
- Fix bug sur l'edition d'une absence

Com 902 contracts events

---

src/api/Bills.js

S'appelle COM-917 mais est lié au ticket COM-918

COM-917 delete route bill showall

---

src/pages/ni/config/CustomersConfig.vue

Info manquante pour le bordereau tiers payeur

COM-934 Add siren to company data

---

src/pages/ni/planning/AuxiliaryPlanning.vue

Les lignes 'a affecter' ne s'affichaient plus

COM-907 fix a affecter

---

src/pages/ni/planning/AuxiliaryPlanning.vue

On ne pouvait plus voir le planning des semaines a venir

COM-907 fix planning display future events

---

src/components/customers/ProfileBilling.vue

On ne pouvait pas selectionner l'annee dans la modale

fix year selection for attestation

---

src/pages/auxiliaries/administrative/Documents.vue

- Périmetre interface : interface auxiliaire
- Périmetre pages : administratif - pages
- Cas d'usage : En tant qu'auxiliaire, je peux télécharger des documents administratifs

COM-972 download documents

---

src/mixins/contractMixin.js
src/pages/auxiliaries/administrative/Contracts.vue
src/pages/customers/Contracts.vue
src/pages/ni/pay/ContractMonitoring.vue

Fix pour la création d'un contrat avec signature en ligne

COM-761 - fix contract creation

---

src/api/BillSlips.js
src/pages/ni/billing/TppBillSlips.vue

- Périmetre interface : admin/superAdmin
- Périmetre pages : /ni/billing/tpp-bill-slips

COM-995 Change billSlip pdf file to docx

---

src/components/auxiliary/ProfileInfo.vue
src/components/auxiliary/ProfilePay.vue
src/components/contracts/Contracts.vue
src/components/customers/ProfileBilling.vue
src/components/customers/ProfileInfo.vue
src/pages/auxiliaries/administrative/Documents.vue
src/pages/ni/auxiliaries/StaffRegister.vue
src/pages/ni/billing/TppBillSlips.vue
src/pages/ni/config/RhConfig.vue
src/pages/ni/pay/Absences.vue

[] J'ai vérifié la fonctionnalité sur mobile - non pertinent
Périmètre interface : Coach / Auxiliaire / Aidant
Périmètre pages :
- Profile auxiliaire : téléchargement de la photo
- Contrat : téléchargement des contrats signés et des archives
- Pay : téléchargement des fiches de paie
- Absences : téléchargement des justificatifs 
- Bordereau : téléchargement des bordereau
- Profile bénéficiaire : téléchargement des mandats et devis
- Onglet facturation : téléchargement des attestations
- Registre unique du personnel : téléchargement des pièces d'identité
- Document administratif : téléchargement des doc
- Rh config : téléchargement des docs administratif
Cas d'usage : téléchargement des documents

Remove prod admin doc

---

src/components/form/DatetimeRange.vue
src/pages/ni/pay/Absences.vue

- Périmetre interface : coach/auxiliaire
- Périmetre pages : planning auxiliaire/bénéficiaire, agenda
- Cas d'usage : création/édition d'évènement

COM-1018 Set seconds and ms in DatetimeRange

---

src/components/auxiliary/ProfileInfo.vue
src/components/menu/SideMenuAuxiliary.vue
src/components/menu/SideMenuFooter.vue
src/helpers/acl/can.js
src/helpers/checkPermission.js
src/layouts/Layout.vue
src/pages/auxiliaries/customers/AuxiliaryCustomersDirectory.vue
src/pages/signin/Authenticate.vue
src/router/routes.js

- Périmetre interface : Auxiliaire / coach
- Périmetre pages : authentification / profile auxilaire / menu
- Cas d'usage : authentification / profile auxilaire / menu

Com 1014 fix

---

src/components/form/DateRange.vue
src/pages/ni/exports/HistoryExports.vue

- Périmetre interface : COach
- Périmetre pages : Export
- Cas d'usage : quand je fais un export, le fonctionnement du date range est plus simple

COM-1005 - fix date range

---

src/api/Users.js
src/components/auxiliary/ProfileInfo.vue
src/components/auxiliary/ProfilePay.vue
src/components/customers/ProfileBilling.vue
src/components/customers/ProfileFollowUp.vue
src/components/form/SelectSector.vue
src/components/menu/SideMenuAuxiliary.vue
src/components/menu/SideMenuCoach.vue
src/components/menu/SideMenuFooter.vue
src/components/planning/Planning.vue
src/helpers/acl/can.js
src/helpers/checkPermission.js
src/layouts/Layout.vue
src/mixins/helperMixin.js
src/mixins/planningModalMixin.js
src/pages/AccountInfo.vue
src/pages/ni/auxiliaries/Dashboard.vue
src/pages/ni/auxiliaries/Directory.vue
src/pages/ni/planning/AuxiliaryPlanning.vue
src/pages/ni/planning/CustomerPlanning.vue
src/pages/signin/Authenticate.vue
src/router/routes.js

- Périmetre interface : Coach / auxiliaire / aidants
- Périmetre pages : Authentification / Fiche auxiliaire / Fiche beneficiaire / Menu / Planning auxiliaire / Planning bénéficiaire / Répertoire auxiliaire / Tableau de bord / Mon compte
- Cas d'usage : changement de role > role.client

COM-1008 - updtae role to role.client

---

src/components/customers/ProfileBilling.vue

- Périmetre interface : Coach
- Périmetre pages : Facturation bénéficiaire
- Cas d'usage : edition d'un paiement lié a un tiers-payeur

COM-663 - fix payment edition

---

src/components/auxiliary/ProfileInfo.vue

- Périmetre interface : Coach / Auxiliaire
- Périmetre pages : Profil auxiliaire
- Cas d'usage : Chargement d'un justificatif

COM-1008 - fix certificates update

---

src/css/app.styl
src/pages/customers/Subscriptions.vue

Fix typo on import

---

src/core/api/Users.js
src/core/pages/signin/ForgotPwd.vue
src/core/pages/signin/ResetPwd.vue

- Périmetre interface : générale
- Périmetre pages :  mot de passe oublié et reset
- Cas d'usage : mot de passe oublié

Com 1008 fix forgot password

---

src/modules/client/mixins/helperMixin.js

- Périmetre interface : coach
- Périmetre pages : info beneficiaire
- Cas d'usage : email envoye lors de la creation d'un aidant

fix helper sending email

---

src/api/Users.js
src/pages/signin/ForgotPwd.vue
src/pages/signin/ResetPwd.vue

COM-1008 Fix forgot password

---

src/modules/client/mixins/helperMixin.js

- Périmetre interface : coach
- Périmetre pages : info beneficiaire
- Cas d'usage : lors de la creation d'un aidant, on peut ajouter un numero de telephone

COM-1022 add phonenumber for helper creation

---

src/modules/client/pages/ni/planning/CustomerPlanning.vue

- Périmetre interface : Auxiliaire / Caoch
- Périmetre pages : Planning beneficiaire
- Cas d'usage : Affichage d'une equipe

COM-1040 - fix customer planning

---

src/core/api/Companies.js
src/core/components/form/OptionGroup.vue
src/core/components/table/TableList.vue
src/core/mixins/companyMixin.js
src/modules/client/components/planning/DeleteEventsModal.vue
src/modules/client/pages/ni/config/CompanyConfig.vue
src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue

- Périmètre interface : Vendeur / admin + responsable organisme formation
- Périmètre pages : répertoire structure
- Cas d'usage : création d'une structure

Com 1028 creation

---

src/core/components/table/TableList.vue

- Périmetre interface : coach, admin_vendor
- Périmetre pages : repertoires 
- Cas d'usage : verifier que l'affichage se fait bien + prend bien en compte uniquement les colonnes visibles sur le repertoire structures

fix table list

---

src/core/data/constants.js
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Périmetre interface : admin_vendeur
- Périmetre pages : repertoire formateur
- Cas d'usage : creer des formateurs en base et verifier l'affichage 
Pour l'instant pas de creation.

Com 1037 trainer

---

src/modules/client/components/customers/PaymentCreationModal.vue
src/modules/client/components/customers/PaymentEditionModal.vue
src/modules/client/components/planning/ChipCustomerIndicator.vue
src/modules/client/components/planning/EventCreationModal.vue
src/modules/client/components/planning/EventHistory.vue
src/modules/client/components/planning/PlanningEvent.vue
src/modules/client/components/planning/PlanningModalHeader.vue
src/modules/client/mixins/configMixin.js
src/modules/client/mixins/subscriptionMixin.js
src/modules/client/pages/customers/Subscriptions.vue
src/modules/client/pages/ni/billing/ClientsBalances.vue
src/modules/client/pages/ni/billing/CreditNotes.vue
src/modules/client/pages/ni/billing/TppBillSlips.vue
src/modules/client/pages/ni/config/CompanyConfig.vue

- Périmetre pages : 
Sousciption : affichage du tableau
Info beneficiaire : affichage du tableau des souscriptions / maj du beneficiaire
Configuration generale : maj des infos
Planning auxiliaire : affichage du flux / modal de creation / modal edition / vue staffing
Planning beneficiaire : Modal creation / modal edition / chip
Paiement : Creation et edition
Avoirs : affichage des évènements de l'avoir
Bordereau : affichage de la liste

Com 1036 lodash

---

src/core/api/Courses.js
src/modules/vendor/components/courses/ProfileProgram.vue
src/modules/vendor/pages/ni/config/CourseProfile.vue
src/modules/vendor/pages/ni/config/CoursesDirectory.vue
src/modules/vendor/router/routes.js

⚠️ Quand on met a jour le nom de la formation ca ne change pas le titre de la page. Ce n'est pas normal mais ok pour la PR : je vais sans doute passer par le store et avant ca j'ai envie de retravailler le store et l'utilisation qu'on en a => Pr in coming
- Périmetre interface : Vendeur / admin + ROP
- Cas d'usage : Affichage et edition d'une formation

COM-1033 - add course profile

---

.github/pull_request_template.md
src/core/data/constants.js
src/core/mixins/userMixin.js
src/modules/client/components/customers/ProfileInfo.vue
src/modules/client/pages/ni/auxiliaries/Directory.vue
src/modules/client/pages/ni/customers/CustomersDirectory.vue
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Périmetre roles : coach, admin_vendor
**repertoire formateur**: creer un formateur
**info beneficiaire**: creer/editer un aidant
**repertoire auxiliaire**: creer un auxiliaire

COM-1037 create trainers

---

src/modules/vendor/pages/ni/config/CoursesDirectory.vue
src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Cas d'usage : affichage en ordre alphabetique des pages repertoire formation et repertoire structure

COM-1025 COM-1028 - sort by name

---

src/modules/client/pages/ni/customers/CustomerProfile.vue
src/modules/vendor/components/trainers/ProfileInfo.vue
src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue
src/modules/vendor/router/routes.js

NOTE: pour l'instant il n'y a que le header sur la page
- Périmetre role : admin_vendor 
- Cas d'usage : redirection vers la page du formateur

COM-1038 go to trainer profile

---

src/core/api/Courses.js
src/modules/vendor/components/courses/ProfileProgram.vue
src/modules/vendor/pages/ni/config/CourseProfile.vue
src/modules/vendor/store/course/actions.js
src/modules/vendor/store/course/getters.js
src/modules/vendor/store/course/index.js
src/modules/vendor/store/course/mutations.js
src/modules/vendor/store/course/state.js
src/store/index.js

- Cas d'usage : Affichage et edition de la page info formation

COM-1033 - add store on course profile

---

src/modules/client/components/ProfileTabs.vue
src/modules/client/pages/customers/Subscriptions.vue
src/modules/client/pages/ni/pay/ContractMonitoring.vue
src/modules/vendor/components/companies/ProfileInfo.vue
src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
src/modules/vendor/router/routes.js
src/modules/vendor/store/company/actions.js
src/modules/vendor/store/company/getters.js
src/modules/vendor/store/company/index.js
src/modules/vendor/store/company/mutations.js
src/modules/vendor/store/company/state.js
src/store/index.js

- Cas d'usage : Affichage de la fiche d'une entreprise + edition de son nom

COM-1030 - add store on company profile

---

src/modules/vendor/components/courses/ProfileProgram.vue
src/modules/vendor/pages/ni/config/CourseProfile.vue
src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue

- Périmetre roles : admin vendeur
- Cas d'usage : lorsque l'on change d'une structure a une autre on a bien les informations de la bonne structure

COM-1030 add beforedestrouy

---

src/core/components/form/Input.vue
src/core/mixins/userMixin.js
src/modules/client/components/auxiliary/ProfileInfo.vue
src/modules/client/store/customer/actions.js
src/modules/client/store/rh/actions.js
src/modules/vendor/components/trainers/ProfileInfo.vue
src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue
src/modules/vendor/store/company/actions.js
src/modules/vendor/store/course/actions.js

- Périmetre interface : interface vendeur
- Périmetre roles : vendor admin 
- Cas d'usage : possibilite d'editer un formateur

COM-1038 profile info

---

src/modules/client/pages/customers/Subscriptions.vue

- Périmetre interface : Aidant
- Périmetre pages : ouverture de la modale de signature du mandat

Fix mandate signature

---

src/modules/client/components/customers/ProfileInfo.vue
src/modules/client/pages/ni/billing/ClientsBalances.vue
src/store/main/getters.js

- Périmetre interface : Coach / Admin
Fiche bénéficiaire : telechargement d'un devis
Balance client : oeil pour aller sur la fiche bénéficiaire

Com 1067 1066

---

src/modules/vendor/components/menu/SideMenuAdmin.vue
src/modules/vendor/pages/ni/operations/CoursesDirectory.vue
src/modules/vendor/router/routes.js

- Périmetre roles : ROF, admin
- Cas d'usage : page formations accessible

COM-1064 formation page creation

---

src/modules/client/components/customers/ProfileInfo.vue
src/modules/client/pages/ni/billing/ClientsBalances.vue
src/store/main/getters.js

Com 1066 com 1067

---

src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue

modification et envoi du sms a l'auxiliaire
Envoi sms code d'activation

COM-1071 - fix update sms

---

src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue

Com 1071 staging

---

src/core/data/constants.js

add absence nature

---

src/core/pages/AccountInfo.vue

- Cas d'usage : la route de sauvegarde d'email n'est pas appelée si le mail n'a pas ete change

COM-588 fix save email if has not changed

---

src/modules/vendor/components/companies/ProfileInfo.vue

- Périmetre roles : admin vendeur
- Cas d'usage :  création d'un coach/admin client

COM-1061 Add company to new user payload

---

src/core/components/table/ResponsiveTable.vue
src/modules/vendor/components/courses/ProfileOrganization.vue

- Cas d'usage : Affichage des creneaux groupés par date (un peu comme pour la facturation)

COM-1052 - update table design

---

src/modules/client/components/customers/ProfileFollowUp.vue
src/modules/client/components/customers/ProfileInfo.vue
src/modules/client/mixins/customerMixin.js

- Périmetre roles : auxiliaire/coach
- Cas d'usage : keyboard normal sur les champs telephone

COM-1073 change input type for phone number

---

src/core/mixins/logInMixin.js
src/core/mixins/loggingMixin.js
src/core/pages/signin/Authenticate.vue
src/core/pages/signin/ResetPassword.vue

- Cas d'usage : Lors du changement de mot de passe on est bien connecte automatiquement.

COM-1043 logging user on reset password

---

src/modules/vendor/components/courses/ProfileOrganization.vue
src/modules/vendor/components/menu/SideMenuAdmin.vue

- Cas d'usage : affichage du tableaux des créneaux sur mobile + homogénéisation du compteurs avec les stagiaires + ajout d'un accent manquant dans le menu

Com 1052 fix

---

src/core/helpers/vuelidateCustomVal.js
src/core/mixins/passwordMixin.js
src/core/pages/AccountInfo.vue

Roll-back sur les contraintes de mot de passe

COM-1063 - remove passwrod contraints

---

src/core/components/form/OptionGroup.vue
src/core/components/modal/Modal.vue
src/core/components/table/ResponsiveTable.vue
src/core/components/table/SimpleTable.vue

`functional` retiré de : 
- OptionGroup
- Modal
- ResponsiveTable
- SimpleTable

COm-1090 - remove functional components

---

src/core/mixins/logInMixin.js

- Cas d'usage : Redirection apres creation du mot de passe et connexion

COM-1043 - fix redirect after logging

---

src/core/components/table/LargeTable.vue
src/core/components/table/TableList.vue
src/modules/client/components/auxiliary/ProfilePay.vue
src/modules/client/pages/auxiliaries/administrative/Documents.vue
src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
src/modules/client/pages/ni/billing/DebitsArchive.vue
src/modules/client/pages/ni/billing/TppBillSlips.vue
src/modules/client/pages/ni/pay/ContractMonitoring.vue

Loading pour les table-list et large-table
- Périmetre roles : admin/auxiliaire
verifier le chargement des tableaux sur les pages suivantes
**Interface admin vendeur**
- repertoire program/entreprises/trainers
**Interface admin client**
- info paie auxiliaire
- RUP
- balance client
- avoirs
- archives prelevements
- a facturer
- financement monitoring
- absence
- STC
- contract monitoring
- paie
- repertoire auxiliaire/beneficiaire
**Interface auxiliaire**
- paie
- documents
- financement monitoring
- repertoire auxiliaire/beneficiaire

Com 1060 table list

---

src/modules/vendor/components/courses/ProfileOrganization.vue
src/modules/vendor/components/menu/SideMenuAdmin.vue
src/modules/vendor/pages/ni/operations/CourseProfile.vue

- Périmetre roles : admin / ROF
- Cas d'usage : quand je cree un creneau en confilt avec un autre, j'ai un message d'erreur explicite

COM-1052 - udpate error message on course slot conflicts

---

src/modules/vendor/components/courses/ProfileOrganization.vue

- Périmetre roles : admin / ROF
MAJ du message de validation lorsqu'on retire un stagiaire de la formation
Message d'erreur explicite quand on essaie d'ajouter un stagiaire qui ne fait pas partie de la même organisation que celle de la formation

COM-1056 - update error and deletion message

---

src/modules/client/components/customers/ProfileFollowUp.vue
src/modules/client/components/customers/ProfileInfo.vue
src/modules/client/mixins/customerMixin.js

- Périmetre roles : auxiliaire/coach
- Cas d'usage : On ne peut rentrer que un numero de telephone dans le champs telephone + on peut entrer ce qu'on veut dans le champs complements

COM-1073 change in telephone input + add complement input

---

src/core/components/table/LargeTable.vue
src/core/components/table/ResponsiveTable.vue
src/core/components/table/SimpleTable.vue
src/core/components/table/TableList.vue
src/css/table.styl
src/modules/client/components/auxiliary/ProfileContracts.vue
src/modules/client/components/contracts/ContractsCard.vue

- Périmetre roles : admin/auxiliaire/aidant
- Cas d'usage :  verifier le fonctionnement des loading des tableaux responsive 
**Admin client**
- page contrat
- info beneficiaire
- configs (beneficiaire, RH et generale)
**Admin vendeur**
- page company
- page organisation de la formation
**Auxiliaire**
- page contrat
**AIdant**
- page souscription

COM-1060 fix contracts table loading

---

src/modules/client/pages/customers/Subscriptions.vue

- Périmetre roles : Aidant
- Cas d'usage : boucle infini sur la page de souscription de l'aidant quand un mandat existe mais n'est pas signé

COM-1060 - Fix infinite loop on subscription apge

---

src/core/pages/AccountInfo.vue
src/modules/client/pages/customers/Subscriptions.vue
src/modules/client/store/customer/mutations.js
src/modules/client/store/rh/mutations.js

fix mandates loading + clear store when logout

---

src/core/api/Courses.js
src/core/api/ressources/alenviAxios.js
src/core/pages/CourseInfo.vue
src/router/routes.js

- Périmetre interface : aucune
- Périmetre roles : aucun
- Cas d'usage : header sur la page d'info d'une formation

COM-1093 add course info page

---

src/modules/client/components/customers/ProfileFollowUp.vue

- Périmetre roles : Coach admin
- Cas d'usage : Suppression du referent

COM-988 - fix referent update

---

src/core/mixins/companyMixin.js
src/modules/client/components/customers/ProfileBilling.vue
src/modules/client/components/menu/SideMenuCustomer.vue
src/modules/client/pages/customers/Billing.vue
src/modules/client/pages/customers/Contact.vue
src/modules/client/pages/customers/Subscriptions.vue
src/modules/client/pages/ni/config/CompanyConfig.vue
src/modules/client/router/routes.js

- Cas d'usage : possibilite de mettre un email de support facturation dans la configuration generale

A fusionner apres la mise en staging - COM-1109

---

src/core/api/Courses.js
src/core/helpers/file.js
src/modules/vendor/components/courses/ProfileFollowUp.vue

- Cas d'usage : telechargement du zip des attestations

COM-1085 - download zip

---

src/modules/client/components/menu/SideMenuCustomer.vue
src/modules/client/pages/customers/Contact.vue
src/modules/client/router/routes.js

- Périmetre roles : helper
- Cas d'usage : information sur l'auxiliaire referente si il y en a une

COM-1053 add referent phone number on contact

---

src/modules/vendor/components/trainers/ProfileInfo.vue

- Périmetre interface :  vendeur
- Périmetre roles :  ROF / admin vendeur
- Cas d'usage : ajout d'un champ biographie sur le profil formateur

COM-1106 Add trainer biography

---

src/core/api/Courses.js
src/core/api/Twilio.js
src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
src/modules/vendor/components/courses/ProfileFollowUp.vue

- Périmetre roles : ROF, admin
- Cas d'usage : Possibilite d'envoyer un sms aux stagiaires

COM-1084 sending sms to trainees

---

src/modules/vendor/components/courses/ProfileFollowUp.vue

- Cas d'usage : Acceder a la page info de la formation + copier le lien

COM-1115 - add course info link

---

src/core/data/constants.js

- Cas d'usage : export referent

COM-1092 export referent

---

src/core/pages/CourseInfo.vue

- Cas d'usage : Prise en compte des retours de Romain
-- Titre et image de la page alignés a gauche sur mobile
-- Ajout de la phrase : "Vous êtes convoqué(e) à la formation"
-- Pour la prochaine date, rond et police plus grande, rond avec une ombre
-- Si pas d'adresse, "Adresse non renseignée"
-- Mise a jour de la meta donnée Titre

COM-1094 - update design

---

package-lock.json
package.json
quasar.conf.js
src/boot/vueclipboard.js
src/modules/vendor/components/courses/ProfileFollowUp.vue

- Cas d'usage : copy du lien de la formation

COM-1115 - use vue package to copy

---

src/modules/client/components/planning/EventEditionModal.vue
src/modules/client/components/table/ToBillRow.vue
src/modules/client/pages/ni/billing/ToBill.vue
src/modules/client/pages/ni/config/CustomersConfig.vue
src/modules/client/pages/ni/config/RhConfig.vue
src/modules/client/pages/ni/pay/ContractEnds.vue
src/modules/client/pages/ni/pay/ToPay.vue

- Cas d'usage : Verifier les checkbox sur les elements suivants: 
- creation/edition d'evenements
- Page facturation
- modales sur config beneficiaire
- config rh
- Paie
- STC

Com-1119 fix checkbox

---

src/core/pages/CourseInfo.vue

- Cas d'usage : sur un ordi, l'adresse s'affiche en dessous de l'horaire

COM-1094 desktop design closer to mobile design

---

src/core/pages/CourseInfo.vue

Reverts sophiemoustard/alenvi-webapp#369

Revert "COM-1094 desktop design closer to mobile design"

---

src/core/pages/CourseInfo.vue

- Périmetre interface 
- Périmetre roles : stagiaire
- Cas d'usage : je vois le formateur sur la page info de la formation

COM-1095 - add trainer to course info page

---

src/modules/client/mixins/fundingMixin.js

- Cas d'usage : Mise a jour du tableau des financements a la creation / maj / suppression

COM-1146 - fix funding update

---

src/core/pages/CourseInfo.vue
src/statics/cguCompani.html
src/statics/rgpd.html
src/statics/rules.html

- Cas d'usage : le reglement interieur s'affiche dans une modale sur la fiche info de formation.

COM-1097 add rules of procedure

---

src/modules/vendor/components/courses/ProfileOrganization.vue

Périmetre interface : Vendeur
Périmetre roles : Admin
Cas d'usage : Affichage du tableau des creneaux
Corriger le calcul de la durée

Com 1085 fix

---

src/modules/client/components/customers/ProfileFollowUp.vue
src/modules/client/store/customer/actions.js
src/modules/vendor/components/courses/ProfileOrganization.vue
src/modules/vendor/store/course/actions.js

- Cas d'usage : MAJ du formateur d'une formation

COM-1085 - fix trainer update

---

src/core/pages/CourseInfo.vue
src/statics/rules.html

- Périmetre roles : Stagiaire
Titre de la page : en rose
Formateur : largeur plus adaptée
Règlement intérieur : mettre a gauche le bouton et diminuer le titre des sections

Com 1096 COM 1097 fix

---

src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue

- Cas d'usage : le lien envoye par le sms piece manquante n'etait pas le bon

fix url for PM

---

src/modules/client/components/customers/ProfileInfo.vue

- Cas d'usage : sur le tableau mandat de prelevement, le point actif/inactif n'etait plus centre

fix dot position

---

src/core/components/TitleHeader.vue
src/modules/client/pages/ni/billing/ClientsBalances.vue
src/modules/client/pages/ni/billing/ToBill.vue
src/modules/client/pages/ni/billing/TppBillSlips.vue
src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue
src/modules/client/pages/ni/pay/Absences.vue
src/modules/client/pages/ni/pay/ContractMonitoring.vue
src/modules/client/pages/ni/pay/ToPay.vue
src/modules/vendor/components/courses/CourseCard.vue
src/modules/vendor/components/courses/CourseContainer.vue
src/modules/vendor/pages/ni/operations/CoursesDirectory.vue

- Cas d'usage : affichage de la liste des formations en 3 colonnes

Com 1100 - A merger apres la mise en staging

---

src/modules/vendor/pages/ni/operations/CoursesDirectory.vue

- Cas d'usage : dans l'onglet 'Formation' dans la modale 'Ajouter une formation' je vois les suggestions de l'input 'Programme' par ordre alphabetique

add alphabet sort on 'Programme' in 'ajouter une formation

---

src/modules/client/mixins/configMixin.js
src/modules/client/pages/ni/config/RhConfig.vue

- Cas d'usage : Je ne peux pas supprimer une equipe des qu'un auxiliaire en a fait partie

COM-1152 - fix sector deletion

---

src/modules/client/pages/ni/auxiliaries/Directory.vue
src/modules/client/pages/ni/customers/CustomersDirectory.vue
src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue

- Périmetre roles : coach, admin vendeur
- Cas d'usage : test Object.freeze sur listes auxiliaires, bénéficiaires, et suivi des plans d'aide

Test object freeze

---

src/modules/vendor/components/courses/CourseCard.vue
src/modules/vendor/pages/ni/management/CoursesDirectory.vue

- Périmetre roles : Admin / formateur
- Cas d'usage : le nombre de dates sur le trello est correct

COM-1134 - fix slots count on trello

---

src/modules/client/components/auxiliary/ProfileInfo.vue
src/modules/client/mixins/validationMixin.js

- Cas d'usage : Acces a la page info auxiliaire

Remove lodash

---

test/cypress/integration/customerAgenda.spec.js
test/cypress/support/commands.js

- Cas d'usage : Creation de la fonction de login qui sera utilisé dans les tests end2end. 
(best practice: https://docs.cypress.io/guides/references/best-practices.html#Organizing-Tests-Logging-In-Controlling-State)

COM-1151 create login fonction

---

src/modules/vendor/components/courses/CourseCard.vue
src/modules/vendor/pages/ni/management/CoursesDirectory.vue

- Périmetre roles : ROF, admin vendeur
- Cas d'usage : affichage de la progression des créneaux de formation

COM-1133 Add slots progression

---

src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Cas d'usage : fix label erreur dans la modal d'ajout de formateur

COM--1162 fix email error label when creating trainer

---

src/modules/vendor/components/courses/ProfileOrganization.vue

- Cas d'usage : Un stagiaire ajouté une deuxième fois sur une formation renvoi une erreur sur l'appli

COM-1156 notify directly the error from back

---

src/modules/vendor/router/routes.js

- Périmetre roles : Formateur
- Cas d'usage : Acces a la page formation

COM-1144 - fix vuex

---

src/modules/client/components/planning/Agenda.vue
src/modules/client/components/planning/PlanningNavigation.vue
src/modules/client/pages/customers/CustomerAgenda.vue
test/cypress/integration/customerAgenda.spec.js

- Périmetre roles : helper
- Cas d'usage : test end2end de l'agenda

Com 1151 agenda

---

src/modules/vendor/components/courses/CourseCard.vue

- Cas d'usage : dans chaque cards de formation, le message de rappel de la date la plus proche, si elle est aujourd'hui, s'écrit pas avec "0 jour(s)" mais avec "aujourd'hui"

Com 1135 fix nearest date today

---

src/core/pages/DocumentSigned.vue

- Cas d'usage : Probleme d'affichage du composant documentSigned apres la signature en ligne

Fix signed document display

---

src/modules/client/pages/ni/config/CompanyConfig.vue

- Cas d'usage : Ajout de la section facturation sur la page Configuration generale

COM-1168 - add billing section

---

src/modules/vendor/components/companies/ProfileInfo.vue

- Cas d'usage : on ne peut plus supprimer de coach/admin

COM-1070 no coach/admin deletion

---

src/core/pages/CourseInfo.vue

- Périmetre interface : -np
- Périmetre roles : -np
- Cas d'usage : sur la page d'info de la formation pour les stagiaires: 
l'icone pour le formateur a ete change + les objectifs pedagogiques sont a presents visible

COM-1120 add learning goals in course info

---

src/modules/vendor/components/companies/ProfileInfo.vue

- Cas d'usage : affichage section 'Abonnement' dans profile info structure

Com 1164 fix

---

src/modules/vendor/components/courses/ProfileFollowUp.vue

- Cas d'usage : je n'ai pas accès au sms 'Convocation' dans la page 'suivi de la formation' si la formation a débuté

COM--1160 disable 'Convocation' if course ongoing

---

src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue

- Cas d'usage : changement du label 'nom commercial' -> 'nom'

Com 1153 fix

---

src/core/pages/CourseInfo.vue

- Cas d'usage : Sur la page d'info des formations fix du probleme en format mobile + fix du centrage en format ordi.

COM-1120 fix design course info page

---

src/core/mixins/companyMixin.js
src/modules/vendor/components/companies/ProfileInfo.vue

- Cas d'usage : Quand je rentre un nom commercial de plus de 11 caracteres, j'ai un message d'erreur approprié

COM-1153 - update error message

---

src/modules/vendor/components/courses/ProfileOrganization.vue

- Cas d'usage : dans les infos d'une formation, le titre de la section des créneaux donne des infos générales

COM-1181 add icone and infos on slots title

---

src/core/helpers/rbac.js

- Périmetre roles : Admin sans abonnement erp
- Cas d'usage : acces a la page configuration / coach

Com 1165 fix

---

src/modules/vendor/components/courses/ProfileOrganization.vue
src/modules/vendor/mixins/courseMixin.js
src/modules/vendor/pages/ni/management/CoursesDirectory.vue

- Cas d'usage : possibilite d'ajouter des stagiaires a des formation interb2b

COM-1188 add trainee in INTERB2B courses

---

src/core/components/table/CoachList.vue
src/core/helpers/ability.js
src/modules/client/components/menu/SideMenuCoach.vue

- Périmetre roles : admin sans erp
- Cas d'usage : possibilite d'ajouter des coach/admin dans la page coach + micro fix sur le display du menu

COM-1000 fix coach list when user hasnt the erp subscription

---

src/modules/client/mixins/helperMixin.js
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Cas d'usage : Un email est envoye aux formateurs à sa creation (que ce soit un nouvel utilisateur ou non)

COm-1125 send welcome email to trainer

---

src/core/components/modal/Modal.vue
src/core/components/table/ResponsiveTable.vue
src/core/helpers/rbac.js
src/modules/client/components/table/FundingGridTable.vue
src/modules/client/mixins/customerMixin.js
src/modules/client/pages/customers/Subscriptions.vue
test/cypress/integration/authenticate.spec.js
test/cypress/integration/customer/subscription.spec.js

- Périmetre roles : helper
- Cas d'usage : tests end2end de la partie abonnements/souscriptions + fix sur l'affichage du titre de l'aidant dans la validation de la souscription

COM-1193 add tests for customer subscriptions

---

src/core/data/constants.js
src/modules/client/components/customers/ProfileFollowUp.vue

- Périmetre roles : admin/auxiliaire
- Cas d'usage : possibilite de changer la situation d'un beneficiaire.

COM-1091 add followup.situation for customers

---

src/modules/client/pages/customers/Contact.vue
test/cypress/integration/customer/contact.spec.js
test/cypress/integration/customer/subscription.spec.js

- Cas d'usage : Test end 2 end pour la page contact de l'aidant

COM-1193 - add customer contact page

---

src/core/components/form/DatetimeRange.vue
src/core/components/table/SimpleTable.vue
src/css/planning.styl
src/css/table.styl
src/modules/client/components/customers/CustomerBillingTable.vue
src/modules/client/components/customers/ProfileFollowUp.vue
src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
src/modules/client/mixins/helperMixin.js
src/modules/client/pages/ni/auxiliaries/Dashboard.vue

1. fix de la taille de la font sur le dashboard
2. fix simple table en mobile
3. fix taille de la date et l'heure dans datetimerange

Com 1195 & COM-1194

---

src/css/planning.styl
src/modules/client/components/planning/Agenda.vue
src/modules/client/components/planning/AuxiliaryIndicators.vue
src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
src/modules/client/components/planning/PlanningModalHeader.vue
src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
src/modules/client/pages/customers/CustomerAgenda.vue
src/modules/client/pages/ni/auxiliaries/Dashboard.vue

- Cas d'usage : Amelioration du design sur mobile notamment pour les indicateurs du tableau de bord, sur le planning, et le nom des auxilaire

COM-1195 - fix indicator style

---

src/core/pages/AccountInfo.vue
src/modules/client/components/menu/SideMenuAuxiliary.vue

- Périmetre interface : toutes
- Cas d'usage : Center les boutons sur la page Mon compte sur mobile

Center buttons on mobile

---

src/core/data/constants.js
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Périmetre roles : trainer/ admin
- Cas d'usage : plus de status pour les formateurs

COM-1205 remove internal/external for trainer

---

src/core/components/menu/SideMenuFooter.vue
src/core/mixins/sideMenuMixin.js
src/index.template.html
src/statics/favicon_metadata/browserconfig.xml
src/statics/favicon_metadata/site.webmanifest

- [] J'ai verifié la fonctionnalite sur mobile : np
> j'ai refait l'audit automatique avec https://realfavicongenerator.net/
- Cas d'usage : tous les formats de favicons

add all favicon formats

---

src/core/data/constants.js

- Cas d'usage : dans la modale de modification d'un evenement, une coquille dans les motifs d'annuations est corrigée

COM-1211-fix coquille

---

src/core/helpers/ability.js
src/core/mixins/logInMixin.js
src/core/mixins/sideMenuMixin.js
src/core/pages/404.vue
src/core/pages/AccountInfo.vue
src/modules/client/components/menu/SideMenuEmpty.vue
src/modules/client/layouts/Layout.vue
src/modules/client/router/routes.js
src/store/main.js

- Périmetre roles : admin / sans role
- Cas d'usage : >  j'ai la possibilité en tant que qu'admin, de créer des utilisateur.ice.s sans role, dans la modale d'ajout de stagiaire a une formation
> j'ai la possibilité en tant que sans role, d'acceder a d'espace 'mon compte' (coté client)

COM-1197 allow access without role

---

src/core/api/Users.js
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Cas d'usage : changement de la modale d'ajout de formateur. On verifie tout d'abord si l'utilisateur existe grace au mail.

COM-1206 add first step to modal to add trainers

---

src/core/pages/AccountInfo.vue
src/modules/client/store/customer/actions.js
src/modules/client/store/planning/actions.js
src/modules/client/store/rh/actions.js
src/modules/vendor/pages/ni/config/ProgramProfile.vue
src/modules/vendor/pages/ni/management/CourseProfile.vue
src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue
src/modules/vendor/store/company.js
src/modules/vendor/store/course.js
src/modules/vendor/store/program.js

- [] J'ai verifié la fonctionnalite sur mobile np
- Cas d'usage : au moment de logout, les operations de reset du store se font avec des actions

COM-1218 add actions to reset client store

---

src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Cas d'usage : Champ prénom au dessus du champ nom

COM-1206 - move firstname field

---

src/modules/client/pages/customers/Subscriptions.vue
test/cypress/integration/customer/subscription.spec.js

- Cas d'usage : test de la partie mandat du beneficiaire. 
Note: 
- Je ne peux pas verifier le contenu du document de eversign parce que c'est une image, du coup je verifie ce qu'on envoie au back.

COM-1208 add tests for the mandate part

---

src/modules/client/components/customers/AddHelperModal.vue
src/modules/client/components/customers/ProfileInfo.vue
src/modules/client/mixins/helperMixin.js

- Cas d'usage : changement de la modale lors de la creation d'un aidant

COM-1209 check if user exists before adding helper

---

src/core/components/courses/CourseContainer.vue
src/core/components/courses/ProfileFollowUp.vue
src/css/app.styl

- Cas d'usage : changement de place pour la baniere

COM-1173 move banner

---

src/core/components/Banner.vue
src/core/components/courses/ProfileFollowUp.vue
src/css/app.styl
src/css/banner.styl
src/modules/client/components/auxiliary/ProfileContracts.vue

- Cas d'usage : Mise a jour de la couleur de fond du message d'erreur sur la page contrat

COM-1173 - update background on client sside

---

src/modules/client/components/customers/AddHelperModal.vue
src/modules/client/mixins/helperMixin.js

- Cas d'usage : changement validation modal ajout aidant

COM-1209 change modal validation

---

src/core/components/table/CoachList.vue
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Cas d'usage : changement modal ajout de coach + fix du loading pour modal formateur

COM-1210 change modal to add coach

---

package-lock.json
package.json

En regardant ici: https://quasar.dev/start/release-notes je n'ai pas l'impression qu'il y est des changements qui nous concerne entre les versions 1.6.1 et 1.9.3.

run audit fix

---

src/modules/client/components/customers/CustomerProfileHeader.vue

- Cas d'usage : Acces a la fiche de Acloque par exemple

FIx customer header

---

src/core/components/courses/ProfileOrganization.vue
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Cas d'usage : la modale d'ajout d'un stagiaire se developpe en fonction des infos a fournir

COM-1204 before front-testing with exist

---

src/core/components/courses/ProfileOrganization.vue
src/core/components/table/CoachList.vue
src/modules/client/components/customers/AddHelperModal.vue
src/modules/client/components/customers/EditHelperModal.vue
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Cas d'usage : fixer le probleme de marge entre le champ role et le champ nom sur la modal s'ajout de coach

FIx margin

---

test/cypress/plugins/index.js

- Cas d'usage : Est-ce que vous pouvez verifier que les tests passent toujours chez vous ? Chez moi ca ne passe toujours pas

fix deprecation

---

src/core/pages/404.vue
src/modules/vendor/router/routes.js

- Cas d'usage : gestion des 404 selon les roles

COM-1219 - fix 404

---

src/core/components/courses/ProfileOrganization.vue
src/modules/client/pages/ni/auxiliaries/Directory.vue

- Cas d'usage : la modale d'ajout d'un stagaire me propose d'abord un email, puis m'invite a rentrer le reste des infos. Si l'email existe déjà et correspond a un.e stagiaire (sans role) les infos disponible apparaissent dans la modale, sinon on notify que l'email est déjà prit

COM-1245 refacto auxiliary creation modale

---

src/core/components/courses/ProfileOrganization.vue
src/core/components/form/OptionGroup.vue
src/core/components/table/CoachList.vue
src/core/helpers/vuelidateCustomVal.js
src/core/pages/AccountInfo.vue
src/modules/client/components/auxiliary/ProfileInfo.vue
src/modules/client/mixins/configMixin.js
src/modules/client/pages/ni/config/CompanyConfig.vue
src/modules/client/pages/ni/config/CustomersConfig.vue
src/modules/client/pages/ni/config/RhConfig.vue
src/modules/vendor/pages/ni/config/ProgramsDirectory.vue
src/modules/vendor/pages/ni/management/CoursesDirectory.vue
src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- [] J'ai verifié la fonctionnalite sur mobile np
-  j'ai laissé les modale qui ont un composant imbriqué (trop pénible d'emettre un event 'invalid') (ex: paymentCreationModal)
- j'ai changé le moins de chose possible pour pas interferer sur des trucs que je comprend pas, mais j'ai l'impression (notamment dans CompanyConf) que les conditions de validité peuvent etre écourtées.

COM-1281 refacto modals confirm

---

src/core/components/form/Input.vue
src/core/components/form/OptionGroup.vue
src/modules/client/components/customers/PaymentCreationModal.vue
src/modules/client/components/customers/PaymentEditionModal.vue
src/modules/client/components/customers/ProfileBilling.vue
src/modules/client/components/planning/EventCreationModal.vue
src/modules/client/components/planning/EventEditionModal.vue
src/modules/client/mixins/paymentMixin.js
src/modules/client/mixins/planningActionMixin.js
src/modules/client/mixins/planningModalMixin.js
src/modules/client/pages/ni/billing/CreditNotes.vue
src/modules/client/pages/ni/config/RhConfig.vue

- Périmetre roles : coach/admin et auxiliaire
On peut cliquer sur le bouton de validation des modales suivantes: planning, agenda, attestation, reglement, avoir et la modal d'ajout de document administratif dans la config rh. 
J'ai aussi ajouter le label d'erreur sur les input de type file.

Com 1281 client modals

---

test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js

Ajout des roles coach, admin et auxiliaire pour les tests sur la page planning

COM-1231 - add coach, admin and auxiliary roles

---

src/core/components/courses/CourseCard.vue
src/css/planning.styl
src/css/quasar.variables.styl

- Cas d'usage : fix design sur le kanban (pour la couleur autour des creneaux a venir, c'est valide avec Romain)

COM-1252 fix slots timeline

---

src/core/components/table/CoachList.vue

- Cas d'usage : lorsque l'on cree un coach/admin ca leur envoie un mail

COM-1267 send mail to coach and admin

---

src/core/components/courses/ProfileFollowUp.vue

- Périmetre roles : admin/rof/trainer
- Cas d'usage : On sait qui a envoye les sms aux stagiaires

COM-1283 add sender to course SMS history

---

src/modules/client/components/customers/AddHelperModal.vue
src/modules/client/mixins/helperMixin.js

- Cas d'usage : Ophélie ajoute les aidants dans cet ordre email/prénom/nom, du coup on inverse

COM-1292 switch name/firstname

---

src/core/mixins/courseFiltersMixin.js
src/core/mixins/filtersMixin.js
src/css/app.styl
src/css/course.styl
src/modules/vendor/pages/ni/management/CoursesDirectory.vue

- Cas d'usage : filtres sur le repertoire de formations

COM-1277 add filters on course directory for rof and admin

---

src/core/components/table/CoachList.vue

- Cas d'usage : lorsque j'ajoute un coach/admin d'une entreprise avec erp il ne recoit pas de mail

COm-1267 dont send mail if user has erp

---

src/core/helpers/alenvi.js
src/core/pages/AccountInfo.vue

- Cas d'usage : fix suppression des cookies

COM-1290 add sameSite arg in cookie removal

---

src/core/components/courses/ProfileFollowUp.vue

- Cas d'usage : ajout du nom du programme aux sms de convocation et de rappel

COM-1265 add program title to sms

---

src/core/pages/courses/CourseInfo.vue

- Périmetre roles : admin/stagiaire
- Cas d'usage : j'ai créé une computed car sans j'avais une erreur en console, course.program se charge pas assés vite et du coup, n'existe pas pendant le premier rendu

COM-1264 move program name from bottom to title

---

src/modules/client/components/customers/ProfileInfo.vue
src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue

- Cas d'usage : suppression des souscriptions

COM-1294 - fix dissable on profile info button

---

src/core/components/courses/CourseContainer.vue
src/core/mixins/courseFiltersMixin.js
src/modules/vendor/pages/ni/management/CoursesDirectory.vue

- Périmetre roles : ROF / admin
- Cas d'usage : Ajustement des filtres
En changeant la manière de faire, ca a mise en place le truc que demandait romain : que less filtres en soient alimentés que par le contenu des formations qui arrivent du back

Com 1277 fix

---

src/core/components/courses/ProfileOrganization.vue
src/core/mixins/companyMixin.js
src/core/mixins/courseMixin.js
src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
src/modules/client/pages/ni/auxiliaries/Directory.vue
src/modules/vendor/pages/ni/management/CoursesDirectory.vue
src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
src/modules/vendor/pages/ni/users/companies/CompanyProfile.vue

- [] J'ai verifié la fonctionnalite sur mobile np
- Cas d'usage : le tradename n'est gardé que pour les sms

COM-1286 remove tradename exept for sms

---

src/core/mixins/courseFiltersMixin.js
src/modules/client/pages/ni/courses/CoursesDirectory.vue
src/modules/vendor/pages/ni/management/CoursesDirectory.vue
src/modules/vendor/pages/trainers/management/CoursesDirectory.vue

- Cas d'usage : je peux filtrer les formations sur les entreprises et les programmes

COm-1279 add filters for trainer

---

src/modules/client/components/auxiliary/ProfileContracts.vue
src/modules/client/components/contracts/ContractsCard.vue
src/modules/client/components/contracts/VersionEditionModal.vue
src/modules/client/mixins/contractMixin.js
src/modules/client/pages/auxiliaries/administrative/Contracts.vue
src/modules/client/pages/customers/Contracts.vue
src/modules/client/pages/ni/pay/ContractMonitoring.vue

- Périmetre roles : aidant, auxiliaire, coach
- Cas d'usage : modification de la modale sur les pages contrats (auxiliaire et suivi contrat)

COM-1295 fix contract modals

---

src/modules/client/components/planning/Agenda.vue
test/cypress/integration/customer/agenda.spec.js
test/cypress/integration/customer/contact.spec.js
test/cypress/integration/ni/planning/auxiliaryPlanning.spec.js

- Cas d'usage : Fix des tests end 2 end

COM-1239 - fix end 2 end tests

---

src/modules/client/components/auxiliary/ProfileContracts.vue
src/modules/client/components/contracts/VersionEditionModal.vue
src/modules/client/components/documents/DocumentUpload.vue

- Cas d'usage : oubli sans doute suite a un rebase

COM-1287 - fix avec rebase

---

src/core/api/ressources/alenviAxios.js
src/core/helpers/alenvi.js
src/core/pages/AccountInfo.vue
src/core/pages/signin/ResetPassword.vue
src/modules/client/router/routes.js
src/modules/vendor/router/routes.js
src/router/index.js
src/router/redirect.js
src/router/routes.js
src/store/main.js

- Cas d'usage : enlever la boucle infini sur le refresh token

COM-1238 - refresh token

---

src/modules/client/router/routes.js
src/modules/vendor/router/routes.js

- Cas d'usage : Quand j'ouvre l'application dans un nouvel onglet je ne suis pas deconnecté

Fix new tab

---

src/core/data/user.js
src/core/helpers/utils.js
src/core/mixins/userMixin.js
src/core/pages/AccountInfo.vue
src/modules/client/components/auxiliary/ProfileInfo.vue
src/modules/client/router/routes.js
src/modules/client/store/rh.js
src/modules/vendor/components/trainers/ProfileInfo.vue
src/modules/vendor/router/routes.js
src/store/main.js

J'ai supprime le mergedUserProfile en inserant la logique dans le store plutot 
Tous les roles : page mon compte + changement de l'url pour enlever l'_id
Coach : fiche detail auxiliaire
Auxiliaire : Informations personnes

Merge user profile

---

src/modules/client/router/routes.js

- Cas d'usage : Ajout d'un import manquant

COM-1323 - add missing import

---

src/core/api/Courses.js
src/core/pages/courses/CourseInfo.vue

- Périmetre interface : page info formation
- Périmetre roles : tous / sans authentification
- Cas d'usage : la page info formation va chercher les infos du back avec une route specifique

Com 1298 public infos

---

src/modules/vendor/store/course.js

- Cas d'usage : pour les formations inter je ne vois que les stagiaires de ma structure

Com 1316 trainees

---

src/modules/vendor/pages/ni/config/ProgramsDirectory.vue

- Cas d'usage : sur le repertoire des programmes, on voit le nombre de modules pour chaque programme
Note: j'ai supposé que pour l'instant on ne faisait pas la duree vu qu'on ne le fait plus pour les activites/modules

COM-1302 add module number on program directory

---

src/core/components/courses/ProfileFollowUp.vue

- Périmetre interface : vendeur 
- Cas d'usage : le lien redevient cliquable si les infos sont là

Com 1316 fix link

---

test/cypress/integration/authenticate.spec.js

- Cas d'usage : suppression du test e2e qui verifie que l'id de l;utilisateur est bien de la lien account vu que celui-ci a ete enleve.

remove irrelevant e2e test

---

src/core/components/table/CoachList.vue
test/cypress/integration/authenticate.spec.js

Com 1321 and e2e fix

---

src/modules/client/router/routes.js
src/modules/vendor/router/routes.js

- Cas d'usage : fix erreur page login (cf erreur sentry sur staging)

COM-1357 fix error on login page

---

src/core/components/courses/CourseCard.vue
src/core/components/courses/ProfileFollowUp.vue
src/core/mixins/courseMixin.js
src/core/pages/courses/CourseInfo.vue
src/core/pages/courses/CourseProfile.vue
src/modules/vendor/components/ProfileHeader.vue

- Cas d'usage : si INTRA/interface vendeur(etiquette kanban et titre profileInfo) : on affiche structure + programme + info complementaire (si ya)
sinon programme + info complementaire (si ya)

Com 1322 misc

---

src/core/components/menu/SideMenuFooter.vue

COM-1358 use getters to know of roles are defined for user

---

src/modules/vendor/components/programs/ProfileInfo.vue

- Cas d'usage : on voit le nombre d'etapes

COM-1356 add number of steps

---

src/core/components/courses/CourseCell.vue
src/core/components/courses/SlotContainer.vue
src/core/components/courses/Trello.vue
src/core/mixins/courseFiltersMixin.js
src/modules/client/pages/ni/courses/CoursesDirectory.vue
src/modules/vendor/pages/ni/management/CoursesDirectory.vue
src/modules/vendor/pages/trainers/management/CoursesDirectory.vue

- Périmetre roles : coach/admin/rof
- Cas d'usage : Les dates a planifier sont modifiables + Ajout du nombre de dates a planifier dans slotsContainer + changement du sort dans le kaban + refacto des fonctions du kanban

Com 1333 edit

---

src/core/data/constants.js
src/modules/vendor/components/programs/ProfileInfo.vue

- Cas d'usage : je peux choisir un type pour les etapes

COm-1332 add type to step

---

src/core/components/courses/CourseCell.vue
src/core/components/courses/ProfileFollowUp.vue
src/core/components/courses/SlotContainer.vue
src/core/components/courses/Trello.vue
src/core/mixins/courseFiltersMixin.js
src/core/pages/courses/CourseInfo.vue
src/core/pages/courses/CourseProfile.vue

- Périmetre roles : admin/rof/coach/trainer
- Cas d'usage : changement de la taille de la police pour les creneaux a planifier + changement du tri sur le kanban + changement de quelques wording + changement sms + slotsToPlan est maintenant une virtual

Com 1335 fix

---

src/core/api/Activities.js
src/modules/vendor/components/programs/CardContainer.vue
src/modules/vendor/components/programs/ProfileInfo.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue

- Cas d'usage : Slidebar + bouton d'ajout de carte + esquisse de modale + esquisse de cellule

COM-1308 add cardCreation

---

src/core/data/constants.js
src/css/quasar.variables.styl
src/modules/vendor/components/programs/CardContainer.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue

Modal : j'ai fini l'affichage, j'ai mis un bouton en plus avec la prochaine carte pour pouvoir verifier le switch entre les boutons
Cellule : j'ai fini l'affichage
CardContainer : j'ai pas encore traité le scroll, ni l'affichage même vide de toute la colonne. Pour la version mobile, j'imagine qu'on va devoir permettre un scroll horizontal sur la QPage, j'ai donc pris la moitié de l'ecran pour afficher correctement les cellules

COM-1308-modal add proper display for modal and card's cell

---

src/modules/vendor/components/programs/ProfileInfo.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue

- Cas d'usage : Création / édition d'étapes et activités

COM-1360 - rename title to name

---

src/core/mixins/sideMenuMixin.js
src/modules/client/components/auxiliary/ProfileInfo.vue
src/modules/client/layouts/Layout.vue
src/modules/client/mixins/menuItemsMixin.js
src/modules/vendor/components/trainers/ProfileInfo.vue
src/modules/vendor/layouts/Layout.vue
src/modules/vendor/pages/ni/users/trainers/TrainerProfile.vue

ETQ rof, je peux changer le prénom d'un formateur
ETQ formateur, je peux changer mon prénom sur ma page administration et ça le change dans le footer

COM-1365 - fix trainer footer label

---

quasar.conf.js
src/modules/vendor/components/programs/CardContainer.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue

- Cas d'usage : ajout du scroll pour la partie gauche

Com 1308 scroll

---

src/modules/vendor/mixins/menuItemsMixin.js
src/modules/vendor/router/routes.js

- Périmetre roles : !! trainer !!
- Cas d'usage : fix,, le reload des infos perso renvoyait vers un 404

Com 1365 reload

---

src/css/header.styl
src/modules/vendor/components/programs/CardContainer.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue

- Cas d'usage : Ajouter l'icone pour media et arranger les tailles pour afficher plus de cartes

Com 1329 fix

---

package-lock.json
package.json

Quasar upgrade and npm audit

---

src/modules/vendor/pages/ni/config/ProgramsDirectory.vue

- Cas d'usage : catalogue programme renomme e-learning en eLearning

COm-1354 from e-learning to eLearning

---

src/modules/vendor/pages/trainers/administrative/Info.vue
src/modules/vendor/router/routes.js

- Cas d'usage : refacto page info personnel

COM-1388 refacto personnal info page for trainers

---

src/core/api/ressources/alenviAxios.js
src/core/helpers/alenvi.js
src/modules/client/router/routes.js
src/modules/vendor/router/routes.js
src/router/index.js
src/store/main.js

- Périmetre roles : Toutes
- Cas d'usage : Plusieurs auxiliaires m'ont remontés qu'ils devaient souvent se reconnecter à compani. J'avoue que je ne suis pas sur de la solution mais je pense que ca peut deja un peu aider :) si vous avez une autre idée, je suis preneuse

COM-1389 - prevent users from being often disconnected

---

src/modules/client/router/routes.js
src/modules/vendor/router/routes.js

- Périmetre interface : -np
- Périmetre roles : -np
- Cas d'usage : attente du retour de canNavigate

COm-1389 add awaits

---

src/css/drawer.styl

fix separator

---

src/core/components/form/CustomImg.vue
src/core/components/form/MultipleFilesUploader.vue
src/modules/client/components/auxiliary/ProfileInfo.vue

- Cas d'usage : Le thumbnail ne se rafraichit pas quand on passe d'une carte titre texte media a une autre carte titre texte media

Com-1309 - fix thumbnail refresh

---

src/core/data/constants.js
src/modules/vendor/pages/ni/config/ActivityProfile.vue

- Cas d'usage : creation d'une carte titre/texte

Com 1372 - prochain  sprint

---

src/core/mixins/logInMixin.js

COM-1398 not using cookies when just set

---

src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
src/modules/client/pages/ni/auxiliaries/Directory.vue
src/modules/client/pages/ni/customers/CustomersDirectory.vue
src/modules/vendor/pages/ni/config/ProgramsDirectory.vue
src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Périmetre interface : les deux
- Cas d'usage : ajout d'une fct pour echaper tous les caracteres interpretables par la regex, typiquement les {[( qui font buger la page

COM-1367-escape-regex

---

src/modules/vendor/components/programs/CardEdition.vue
src/modules/vendor/components/programs/templates/TitleText.vue
src/modules/vendor/helpers/cardValidation.js
src/modules/vendor/mixins/templateMixin.js

- Cas d'usage : edition des carte titre/texte

Com 1372 edit

---

src/modules/client/components/planning/ChipAuxiliaryIndicator.vue
src/modules/client/components/planning/EventCreationModal.vue
src/modules/client/components/planning/EventEditionModal.vue
src/modules/client/components/planning/Planning.vue
src/modules/client/mixins/planningActionMixin.js
src/modules/client/mixins/planningModalMixin.js
src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue
src/modules/client/pages/ni/planning/CustomerPlanning.vue

Com 1276 rename

---

src/modules/client/components/auxiliary/ProfileContracts.vue
src/modules/client/components/contracts/ContractsCell.vue
src/modules/client/mixins/contractMixin.js
src/modules/client/pages/ni/config/RhConfig.vue

Suppression des templates de contrats/avenants mandataires
Telechargement des contrats prestataires (renommage dess champs)

Com 1276 template

---

src/modules/vendor/components/programs/CardEdition.vue
src/modules/vendor/components/programs/templates/TextMedia.vue
src/modules/vendor/components/programs/templates/TitleTextMedia.vue
src/modules/vendor/helpers/cardValidation.js
src/modules/vendor/mixins/templateMixin.js

- Cas d'usage : edition d'une carte text/media, j'ai mis tout le code propre au media  dans le mixin templateMixin

add text-media edition

---

src/modules/client/components/auxiliary/ProfileContracts.vue
src/modules/client/mixins/contractMixin.js

- Périmetre roles : Admin / coach / auxiliaires
Fin de contrat
Signature en ligne du contrat
Upload des contrats signés a la main
Paie
STC

Com 1276 signature

---

src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue

- Cas d'usage : ajout du tri selon le nbr de formations suivis. Par defaut decroissant

COM-1367-order add sort on followingCourse

---

src/core/api/Cards.js
src/modules/vendor/components/programs/CardEdition.vue
src/modules/vendor/components/programs/templates/Flashcard.vue
src/modules/vendor/helpers/cardValidation.js
src/modules/vendor/mixins/templateMixin.js

- Cas d'usage : Edition des cartes flashcard

COM-1377 edition for flashcard

---

src/modules/client/components/customers/CustomerProfileHeader.vue
src/modules/client/mixins/menuItemsMixin.js

changement de la condition deletionDisabled dans customerProfileHeader
suppression de la fonction hasContract dans menuItemsMixin

Com 1276 fix

---

src/modules/vendor/components/programs/ProfileInfo.vue

COM-1422 remove q-card border-radius

---

src/modules/client/mixins/menuItemsMixin.js
src/modules/client/pages/customers/Billing.vue
src/modules/client/pages/customers/Contact.vue
src/modules/client/pages/customers/CustomerAgenda.vue
src/modules/client/pages/customers/Subscriptions.vue
src/modules/client/router/routes.js

fix-helper

---

test/cypress/integration/auxiliary/planning/auxiliaryAgenda.spec.js
test/cypress/integration/ni/billing/toBill.spec.js

fix-to-bill

---

package.json

COM-1440 maj @quasar/extra

---

src/modules/vendor/components/programs/ProfileContent.vue
src/modules/vendor/components/programs/ProfileInfo.vue
src/modules/vendor/pages/ni/config/ProgramProfile.vue
src/modules/vendor/router/routes.js

- Cas d'usage : séparation du programProfile en deux tabs

COM-1404 split programProfile in two tabs

---

src/core/components/courses/CourseCell.vue
src/core/components/courses/ProfileFollowUp.vue
src/core/components/courses/ProfileOrganization.vue
src/core/components/courses/SlotContainer.vue
src/core/components/courses/Trello.vue
src/core/data/constants.js
src/core/helpers/utils.js
src/core/mixins/courseMixin.js
src/modules/client/components/auxiliary/ProfileInfo.vue
src/modules/vendor/components/programs/ProfileContent.vue
src/modules/vendor/components/programs/ProfileInfo.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue

- Cas d'usage : affichage du type et du nmb de carte d'une activité dans le tableau de programProfile

COM-1413 add activity type

---

src/core/api/Activities.js
src/core/api/Programs.js
src/core/api/Steps.js
src/core/api/SubPrograms.js
src/modules/vendor/components/programs/ProfileContent.vue
src/modules/vendor/pages/ni/config/ProgramsDirectory.vue

- Cas d'usage : creation de sous programme, affichage des etapes activités, edition du nom

COM-1404-sub-program add subProgram creation, display and name edition

---

.eslintrc.js
src/core/api/Programs.js
src/core/api/SubPrograms.js
src/core/components/PictureUploader.vue
src/core/components/ProfileTabs.vue
src/core/components/form/FileUploader.vue
src/core/components/form/MultipleFilesUploader.vue
src/modules/client/components/customers/infos/FundingCreationModal.vue
src/modules/client/components/customers/infos/FundingDetailsModal.vue
src/modules/client/components/customers/infos/FundingEditionModal.vue
src/modules/client/components/customers/infos/FundingHistoryModal.vue
src/modules/client/components/customers/infos/HelperCreationModal.vue
src/modules/client/components/customers/infos/HelperEditionModal.vue
src/modules/client/components/customers/infos/ProfileInfo.vue
src/modules/client/components/customers/infos/SubscriptionCreationModal.vue
src/modules/client/components/customers/infos/SubscriptionEditionModal.vue
src/modules/client/components/customers/infos/SubscriptionHistoryModal.vue
src/modules/client/components/pay/PaySurchargeDetailsModal.vue
src/modules/client/components/planning/Planning.vue
src/modules/client/components/planning/PlanningEvent.vue
src/modules/client/mixins/helperMixin.js
src/modules/client/mixins/subscriptionMixin.js
src/modules/vendor/components/programs/ActivityCreationModal.vue
src/modules/vendor/components/programs/ActivityEditionModal.vue
src/modules/vendor/components/programs/ProfileContent.vue
src/modules/vendor/components/programs/StepCreationModal.vue
src/modules/vendor/components/programs/StepEditionModal.vue
src/modules/vendor/components/programs/SubProgramCreationModal.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue
src/modules/vendor/router/routes.js

- Périmetre roles : vendeur
- Cas d'usage : j'ai refacto les modals de customer/profileInfo aussi

Com 1404 final

---

src/modules/client/pages/ni/customers/CustomersDirectory.vue

- Périmetre roles : Admin / Coach
- Cas d'usage : Fix du repertoire beenficiaire

Com 1418 fix

---

src/core/components/courses/SlotContainer.vue
src/core/components/courses/SlotCreationModal.vue
src/core/components/courses/SlotEditionModal.vue

- Périmetre roles : ROF / Admin
- Cas d'usage : L'etapes est obligatoire au niveau des créneaux

COM-1405 - step is required

---

src/core/components/courses/SlotContainer.vue
src/core/mixins/validationMixin.js
src/core/pages/AccountInfo.vue
src/modules/client/components/auxiliary/ProfileInfo.vue
src/modules/client/components/customers/ProfileFollowUp.vue
src/modules/client/components/customers/infos/ProfileInfo.vue
src/modules/client/components/documents/DocumentUpload.vue
src/modules/client/components/planning/DeleteEventsModal.vue
src/modules/client/mixins/planningActionMixin.js
src/modules/client/pages/ni/auxiliaries/Directory.vue
src/modules/client/pages/ni/config/CompanyConfig.vue
src/modules/client/pages/ni/config/CustomersConfig.vue
src/modules/client/pages/ni/config/RhConfig.vue
src/modules/client/pages/ni/customers/CustomersDirectory.vue
src/modules/vendor/components/learners/ProfileInfo.vue
src/modules/vendor/components/trainers/ProfileInfo.vue

- Cas d'usage : Fix sur la validation des creneaux qui doit etre asynchrone a cause de l'adresse

COM-1405 - run validations

---

src/core/helpers/vuelidateCustomVal.js
src/modules/vendor/components/programs/cards/CardEdition.vue
src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
src/modules/vendor/helpers/cardValidation.js
src/modules/vendor/mixins/templateMixin.js

- [] J'ai verifié la fonctionnalite sur mobile  np
- Cas d'usage : edition de 'mettre dans l'ordre'

COM-1412 add orderTheSequence edition

---

src/modules/vendor/components/programs/ActivityCreationModal.vue
src/modules/vendor/components/programs/ActivityEditionModal.vue
src/modules/vendor/components/programs/StepCreationModal.vue
src/modules/vendor/components/programs/StepEditionModal.vue
src/modules/vendor/components/programs/SubProgramCreationModal.vue

- Cas d'usage : sur la page des sous programmes je peux editer plusieurs fois une etape ou une activite
Merci @CorentinMartinot d'avoir trouvé d'où venait le bug !

COM-1446 add @input in modals

---

src/modules/client/components/auxiliary/ProfileContracts.vue

- Cas d'usage : bandeau d'avertissement a la creation des contrats

COM-1447 - fix warning

---

src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
src/modules/client/pages/ni/billing/CreditNotes.vue

- Cas d'usage : refacto modales des avoirs

COM-1429 mode creditNote modals in separate components

---

src/core/api/SubPrograms.js
src/modules/vendor/components/programs/ProfileContent.vue

- Cas d'usage : Je peux detacher une etape d'un sous programme

COM-1426 can detach steps from subprogram

---

src/core/data/constants.js
src/modules/vendor/components/programs/cards/CardContainer.vue
src/modules/vendor/components/programs/cards/CardCreationModal.vue

- Cas d'usage : je peux creer des cartes questionnaires (question ouverte et sondage)

COM-1438 add questionnaire templates creation

---

src/modules/vendor/components/programs/ActivityReuseModal.vue
src/modules/vendor/components/programs/ProfileContent.vue

- Cas d'usage : je peux reutiliser/dupliquer une activité

Com 1429 reuse

---

package-lock.json
package.json
src/modules/client/components/planning/Planning.vue
src/modules/client/components/planning/PlanningEvent.vue
src/modules/client/pages/ni/pay/ToPay.vue
src/modules/vendor/components/programs/ProfileContent.vue

- Cas d'usage : Drag / drop d'etape

COM-1428 - allow reodering

---

src/modules/vendor/components/programs/ActivityReuseModal.vue
src/modules/vendor/components/programs/ProfileContent.vue

- Cas d'usage : les activités de l'etape selectionné n'apparaissent pas des la modale de réutilisation/duplication

Com 1429 same step

---

src/core/helpers/vuelidateCustomVal.js
src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue

QCM edit 
-> si pas de label sur premier champ alors changement possible sur les autres champs avec simple warning
-> si pas label sur 2ème mais sur 3ème (plus 3ème correct) alors les réponses remontent

Com 1410 - Fix Warnings for exceptionnal cases

---

src/modules/vendor/components/programs/ProfileContent.vue

- Cas d'usage : ajout de l'index dans l'affichage des étapes du catalogue

COM-1441 add step index

---

src/modules/vendor/components/programs/cards/CardEdition.vue
src/modules/vendor/components/programs/cards/templates/OpenQuestion.vue
src/modules/vendor/helpers/cardValidation.js

- Cas d'usage : Modification des cartes questions ouvertes

COM-1439 add open question template

---

src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
src/modules/vendor/helpers/cardValidation.js

- [] J'ai verifié la fonctionnalite sur mobile np
- Cas d'usage : refacto du nom du champs 'text' en 'gappedText'

COM-1474 change fillTheGaps field name 'text' to 'gappedText'

---

src/modules/vendor/components/programs/cards/CardEdition.vue
src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue

- Cas d'usage : refacto : chargement des templates de cartes + immediate watcher

COM-1473 refacto card template registration + immediate watcher

---

src/modules/vendor/components/programs/cards/CardContainer.vue

- Cas d'usage : ajout du titre dans la barre latérale d'une activité pour les cartes quizz et questionnaire

COM-1472 add title for quiz and survey

---

src/core/components/form/Select.vue
src/core/pages/AccountInfo.vue
src/modules/vendor/components/programs/ProfileContent.vue

Ne pas afficher la petite fleche du select quand il y a une icône spéciale (comme dans la modal d'édition d'un évènement)
Ajuster la hauteur des cartes activité dans la liste des sous programmes

Fix design

---

src/modules/client/components/planning/EventCreationModal.vue
src/modules/client/components/planning/EventEditionModal.vue

- Périmetre roles : auxiliary
- Cas d'usage : fix toggle de l'adresse d'un evenemetn

COM-1484 fix event toggle address

---

src/modules/vendor/components/programs/ProfileContent.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue
src/modules/vendor/store/program.js

Lorsque je sors de la page de modification d'une activité (par le bouton retour), je vois le step que j'avais ouvert toujours ouvert. De plus, un scroll automatique se fait jusqu'à lui.

Com 1420 - Open step when user go back from activity

---

src/core/data/constants.js
src/core/helpers/alenvi.js
src/core/mixins/logInMixin.js
src/core/pages/signin/Authenticate.vue
src/router/redirect.js
test/cypress/integration/authenticate.spec.js
test/cypress/support/commands.js

- Cas d'usage : Avoir deux messages d'erreur lors de l'authentification : un pour les identifiants invalides et un autres pour les autres erreurss

COM-1496 - fix error message on authentification

---

src/modules/vendor/components/programs/ProfileContent.vue
src/modules/vendor/components/programs/cards/CardContainer.vue

- Cas d'usage : pas de d&d si edition bloquée, pas d'action si le d&d ne change pas l'odre

Com 1459 fix

---

src/core/components/form/FileUploader.vue

- Périmetre interface : venderu
- Cas d'usage : blocage de la suppression

Com 1469 fix

---

src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
src/modules/vendor/helpers/cardValidation.js

- Cas d'usage : falsyAnswers separé en qcuFalsyAnswers et falsyGapAnswers

COM-1505 refacto falsy answers

---

src/core/components/PictureUploader.vue
src/core/components/form/FileUploader.vue

- Cas d'usage : enlever les diacritiques des lettres (ex: 'ç' => 'c', 'é' => 'e')

COM-1539 remove diacritics in titles

---

src/core/api/InternalHours.js

- Cas d'usage : fix du cochage de checkbox sur la page config RH / Heure internes

COM-1543 fix

---

src/core/pages/AccountInfo.vue
src/core/pages/NewPasswordModal.vue
src/modules/vendor/components/programs/ActivityCreationModal.vue

- Périmetre interface : all
- Périmetre roles : all
- Cas d'usage : refacto de NewPasswordModal en composant

COM-1542 refacto newPassword modal

---

test/cypress/integration/authenticate.spec.js

- Cas d'usage : FIX des test e2e

COM-1511-e2e fix e2e test

---

src/modules/client/components/auxiliary/ProfileContracts.vue
src/modules/client/components/contracts/ContractCreationModal.vue
src/modules/client/components/contracts/ContractEndingModal.vue
src/modules/client/components/contracts/VersionCreationModal.vue

- Cas d'usage : refact modales

COM-1542-contract move modals

---

src/core/data/constants.js
src/modules/vendor/components/programs/cards/CardCreationModal.vue

- Cas d'usage : nouveau bouton pour créer une carte Q&A

COM-1499 added Q&A to cardCreation modal

---

src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue

- Périmètre interface : client
- Périmètre rôles : auxiliaire
- Cas d'usage : ajout du nom du secteur dans le répertoire des auxiliaires

COM-1512 added sector name

---

src/core/mixins/companyMixin.js
src/core/mixins/establishmentMixin.js
src/modules/client/pages/ni/config/CompanyConfig.vue
src/modules/client/pages/ni/config/EstablishmentCreationModal.vue

- Cas d'usage : nouveau composant _EstablishmentCreationModal_
(situé dans le même répertoire que le composant parent)

COM-1571 refacto EstablishmentCreationModal

---

src/modules/vendor/components/programs/ProfileContent.vue

Si mon step à des activités incomplètes -> pastille jaune
s'il est publié -> pastille verte + publié

COM-1528 - Add step status dot

---

src/modules/client/pages/ni/config/CompanyConfig.vue
src/modules/client/pages/ni/config/EstablishmentEditionModal.vue

- Cas d'usage : refacto EstablishmentEditionModal

COM-1571 refacto EstablishmentEditionModal

---

src/core/components/courses/CourseInfoLink.vue
src/css/app.styl
src/css/chip.styl
src/css/planning.styl
src/modules/client/components/planning/AuxiliaryIndicators.vue
src/modules/client/components/planning/ChipCustomerIndicator.vue
src/modules/client/components/planning/Planning.vue
src/modules/client/layouts/Layout.vue
src/modules/vendor/layouts/Layout.vue

- Périmetre interface : VENDOR & CLIENT
Le menu est accessible même lorsque je change la taille de mon écran

COM-1566 - Change max-width and min-width and fix menu access

---

src/modules/client/pages/ni/pay/ToPay.vue

- Périmetre interface : CLIENT
Le filtre 'trier par' dans la page paie mensuelle fonctionne (le premier filtre ne fonctionnait pas)

Com 1549 Fix - Fix sort by option

---

src/modules/client/pages/customers/Subscriptions.vue

- Périmetre roles : aidant/coach
- Cas d'usage : Verifier que la validation des souscriptions fonctionne toujours bien. (la validation des souscriptions passe maintenant par l'id de la subscription)

COM-1572 add subscriptonId in payload when validate subscription

---

src/core/data/constants.js
src/modules/vendor/components/programs/ProfileContent.vue
src/modules/vendor/components/programs/PublishedDot.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue

Ajout du dot publié sur ActivityProfile (la page qui détaille les cartes des activités)
cf commentaire de Romain sous le ticket

COM-1527 - Add published dot to ActivityProfile after Romain's review

---

src/core/api/Courses.js
src/core/components/courses/HorizontalBarChart.vue
src/core/components/courses/ProfileTraineeFollowUp.vue
src/core/components/courses/SurveyChart.vue
src/core/pages/courses/BlendedCourseProfile.vue
src/modules/vendor/components/programs/ProfileContent.vue

- Cas d'usage : affichage d'un graphe de statistique des réponses aux sondages

Com 1516 surveys

---

src/modules/client/components/customers/infos/ProfileInfo.vue

si j'edite une souscription qui a des 0, le cout hebdomadaire est 0 et pas Nan

COM-1572 fix Nan on subscription edition

---

src/modules/client/components/config/ThirdPartyPayerCreationModal.vue
src/modules/client/pages/ni/config/CustomersConfig.vue

- Cas d'usage : j'ajoute la validation mail cote front

COM-1595 modal refacto

---

src/modules/client/components/config/ServiceEditionModal.vue
src/modules/client/components/config/ThirdPartyPayerEditionModal.vue
src/modules/client/pages/ni/config/CustomersConfig.vue

- Cas d'usage : ThirdPartyPayerEditionModal

Com 1595 ThirdPartyPayerEditionModal

---

src/modules/client/components/config/AdministrativeDocumentCreationModal.vue
src/modules/client/components/config/InternalHourCreationModal.vue
src/modules/client/components/config/NewInternalHourModal.vue
src/modules/client/components/config/SectorCreationModal.vue
src/modules/client/components/config/SectorEditionModal.vue
src/modules/client/pages/ni/config/RhConfig.vue

- Périmetre roles : RH / admin
Refacto des modals : NewInternalHourModal, AdministrativeDocumentCreationModal, SectorCreationModal et SectorEditionModal.

Com 1597 - Refacto Rh Config Modals

---

src/modules/vendor/components/programs/cards/CardContainer.vue

- Cas d'usage : la barre de navigation des cartes est moins chargée

COM-1583 hide card type in cardContainer

---

src/core/components/Button.vue
src/core/pages/signin/Authenticate.vue

- Périmetre interface : ALL
- Périmetre roles : ALL
- Cas d'usage : le bouton première connexion sur la page d'accueil a été ajouté.

COM-1593 added firstLogin link on landing page

---

src/modules/vendor/components/programs/ProfileContent.vue

- Cas d'usage : le bouton `publier` est a présent en bas de chaque sous-programme

Com 1588 move publish button

---

src/core/api/Cards.js
src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue

- Cas d'usage : edition des reponses possible des cartes QUESTION_REPONSES

Com 1596 edition

---

src/modules/client/pages/ni/customers/CustomersDirectory.vue

- Cas d'usage : Pas de warning orange sur le repertoire s'il y a toutes les infos

COM-1608 - fix validation if error is undefined

---

src/modules/client/components/customers/infos/ProfileInfo.vue

- Cas d'usage : Je ne peux pas creer ou editer une souscription avec un service archivé (cf point 2 du ticket)

COM-1587 cant edit or add sub with archived service

---

src/core/api/Courses.js
src/core/pages/courses/BlendedCourseProfile.vue
src/modules/client/components/customers/CustomerProfileHeader.vue
src/modules/vendor/components/ProfileHeader.vue

- Périmetre roles : Admin / rof
- Cas d'usage : Suppression des formations sans créneau ni stagiaire

COM-1582 - delete course

---

src/modules/vendor/components/programs/cards/CardCreationModal.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue

- Cas d'usage : je cree une carte en 2 clic souris

COM-1584 card-creation in two clicks

---

src/modules/vendor/components/learners/ProfileInfo.vue
src/modules/vendor/components/trainers/ProfileInfo.vue

- Cas d'usage : je peux voir et modifier le numero d'un formateur

COM-1590 added phone input

---

src/core/api/Cards.js
src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue

- Cas d'usage : je peux supprimer une reponse

Com 1596 deleteAnswer

---

src/core/pages/courses/BlendedCourseProfile.vue

- Cas d'usage : L'icone pour supprimer une formation reste toujours en haut a droite

COM-1582 fix delete icon position in course header

---

src/core/components/courses/SurveyChart.vue

- Périmetre roles : rof / admin
- Cas d'usage : affichage des sondages

COM-1606 using rounded divs instead of q-linear-progress

---

src/core/api/CourseHistories.js
src/core/components/courses/CourseHistory.vue
src/core/components/courses/CourseHistoryFeed.vue
src/core/components/courses/ProfileOrganization.vue
src/core/data/constants.js
src/css/app.styl
src/css/history.styl
src/modules/client/components/planning/EventHistory.vue
src/modules/client/components/planning/EventHistoryFeed.vue

[x] J'ai verifié la fonctionnalite sur mobile
Périmetre interface : Vendor
Périmetre roles : rof / admin / coach
Cas d'usage : Lorsque je clique sur le bouton Historique dans le profil d'une course (onglet organisation), je vois l'historique de la création de créneaux (uniquement pour la création). Je peux cliquer sur le bouton oeil pour avoir plus de détails
Ce qui n'est pas dans cette PR : le scroll infini

COM-1611 - Add CourseHistoryFeed

---

src/core/components/courses/CourseHistoryFeed.vue
src/core/components/courses/ProfileOrganization.vue

- Périmetre roles : rof / admin / coach
Ajout d'un infinite scroll sur l'historique des créneaux des formations.
Suite de la PR : https://github.com/sophiemoustard/alenvi-webapp/pull/769

COM-1611 - Add infinite scroll

---

src/core/api/Contracts.js
src/modules/client/components/contracts/ContractsCell.vue
src/modules/client/mixins/payMixin.js
src/modules/client/pages/ni/pay/ToPay.vue

- Périmetre roles : Coach / Admin
- Cas d'usage : En tant que coach / admin, je peux télécharger le contenant les informations d'identification d'un salarié pour le charger dans 123paie et faire la DPAE

COM-1605 - download txt file

---

src/core/components/courses/QuestionAnswerChart.vue

- Cas d'usage : fix apres retour de Romain, on arrondi le pourcentage a lunité

COM-1610 rounded percentage QuestionAnswer

---

src/core/components/courses/CourseHistory.vue
src/core/data/constants.js

- Périmetre roles : ROF / ADmin / Coach
Lorsque je supprime un créneau, il apparait dans l'historique des modifications de créneau.

COM-1612 - Create coursehistory on slot deletion

---

src/core/api/Users.js
src/core/helpers/rbac.js
src/core/helpers/utils.js
src/modules/client/mixins/menuItemsMixin.js
src/modules/client/pages/auxiliaries/customers/AuxiliaryCustomersDirectory.vue
src/modules/client/pages/ni/auxiliaries/Directory.vue
src/modules/client/pages/ni/courses/LearnersDirectory.vue
src/modules/client/pages/ni/customers/CustomersDirectory.vue
src/modules/client/router/routes.js
src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue

- Périmetre roles : client admin
- Cas d'usage : je vois la liste des apprenants dune structure

Com 1616 getLearnerList

---

src/core/components/courses/CourseHistory.vue
src/core/data/constants.js

- Cas d'usage : je vois lhistorique dune modif de jour
BUG: il ya une erreur si on supprime un créneau dont la date a été modifiée

COM-1618 view history action after course edition

---

src/core/components/courses/CourseHistory.vue
src/core/data/constants.js

- Périmetre roles : rof / coach / admin
Lorsque je supprime un apprenant, je le vois dans l'historique

COM-1614 - Add course history for trainee deletion

---

src/core/components/courses/CourseHistory.vue

- Périmetre interface : formations
- Cas d'usage : je sais si un créneau a changé d'horaire

COM-1619 add newHour in courseHistory switch

---

src/core/components/courses/SlotContainer.vue

- Périmetre roles : all
Refacto courseSlot.courseId en course

COM-1647 - Refacto courseSlot.courseId to course

---

src/core/components/courses/LearnerCreationModal.vue
src/core/components/courses/TraineeTable.vue

- Périmetre roles : formateur rof admin
- Cas d'usage : refacto ajout apprenant
dois-je renommer toutes les variables avec trainee vers learner dans ces deux fichiers?

Com 1631 refacto LearnerCreationModal

---

src/modules/vendor/components/programs/cards/templates/TextMedia.vue
src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
src/modules/vendor/mixins/templateMixin.js

- Périmetre roles : rof / admin
Autorise les uploads de video et d'audio maintenant que GCS est en place

Com 1628 - Allow audio and video upload

---

src/core/api/Cards.js
src/modules/vendor/mixins/templateMixin.js

- Cas d'usage : Suppression des medias des cartes

COM-1628 - add deletion route

---

src/core/helpers/rbac.js
src/modules/vendor/components/programs/cards/templates/TextMedia.vue
src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue
src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue
src/modules/vendor/router/routes.js

Lorsque je clique sur une formation eLearning dans la liste, je vois la page d'info sur cette formation contenant la liste des apprenants ainsi que leur progression.
PAS ENCORE FAIT :
- Le composant pour visualiser la progression
- Le sort() de la liste

Com 1633 - ELearningCourseProfile 

---

src/core/components/PictureUploader.vue

- Cas d'usage : ETQU, je peux charger ma photo de profil

COM-1667 - fix picture image upload

---

src/modules/vendor/components/programs/cards/templates/TextMedia.vue
src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
src/modules/vendor/mixins/templateMixin.js

- Cas d'usage : possibilité d'ajout des medias de type audio et video

COM-1629 add option group in TitleTextMedia

---

src/core/components/CourseProgress.vue
src/core/components/learners/ProfileCourses.vue

- Périmetre interface : vendeur et client
- Périmetre roles : vendor admin client admin
- Cas d'usage : affichage d'une jauge de progression
NOTE:
- la jauge nest pas encre précise ( 3 etats uniquement )
- l'affichage mobile nest pas géré

COM-1630 using CourseProgress

---

src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue

- Cas d'usage : je vois la progression de mes apprenants

COM-1633 add progress bar

---

src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue

- Cas d'usage : Je peux changer la bonne réponse d'un QCM sans avoir une erreur

COM-1670 - fix update good answer

---

src/core/data/constants.js

- Périmetre roles : Rof
- Cas d'usage : je peux exporter tous types d'audio

COM-1628 - fix audio extensions

---

src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue

- Périmetre roles : ROF - Admin
- Cas d'usage : Sur la page d'une formation elearning, quand je clique sur un apprenant, je suis redirigé vers sa page, onglet formations

COM-1633 - redirect to learner profile

---

src/core/data/constants.js
src/modules/client/pages/ni/pay/ToPay.vue

- Cas d'usage : Export du fichier des avenants pour 123paie

COM-1623 - add contract version in export

---

src/core/api/Courses.js
src/core/components/learners/ProfileCourses.vue
src/core/mixins/courseFollowUpMixin.js
src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue

- Cas d'usage : je vois ma progression sur mes formations

Com 1630 list user course

---

src/modules/vendor/components/programs/ProfileContent.vue

- [] J'ai verifié la fonctionnalite sur mobile - NP
Je ne peux pas publier de sous programme s'il n'est pas valid -> via le virtual areStepsValid

COM-1603 - Disable publishment button when subProgram is not valid

---

src/core/api/Users.js
src/modules/client/pages/ni/auxiliaries/Directory.vue

- Périmetre roles : Admin - Coach
- Cas d'usage : Creation des dossiers drive a la creation

Refacto create drive

---

src/modules/vendor/components/programs/ProfileContent.vue

- Cas d'usage : Quand la publication n'est pas possible, donner le warning avant de demander confirmation a l'utilisateur

COM-1603 - warning before confirm

---

src/core/api/Categories.js
src/core/helpers/rbac.js
src/modules/vendor/components/programs/CategoryCreationModal.vue
src/modules/vendor/mixins/menuItemsMixin.js
src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
src/modules/vendor/router/routes.js

Cas d'usage : je peux voir et ajouter des catégories dans l'onglet configuration

Com 1657 view and add categories

---

src/core/api/Categories.js
src/modules/vendor/components/programs/CategoryEditionModal.vue
src/modules/vendor/pages/ni/config/CategoriesDirectory.vue

- Cas d'usage : je peux modifier un nom

Com 1657 update (PUT ROUTE)

---

src/core/api/Categories.js
src/modules/vendor/pages/ni/config/CategoriesDirectory.vue

COM-1657 delete button

---

src/core/data/constants.js
src/core/helpers/alenvi.js
src/core/mixins/logInMixin.js

- Cas d'usage : changement de l'option expires des cookies.

COM-1668 change how we set the expires option in cookies

---

src/core/data/constants.js
src/core/helpers/alenvi.js
src/core/mixins/logInMixin.js

- Périmetre interface : client/vendeur/mobile
- Cas d'usage: 
- Verifier que l'on peut se connecter
- Verifier qu'en créant un utilisateur sans entreprise et sans role (formateur puis enlever le role a la main), l'utilisateur peut se connecter sur l'application mobile (a tester sur le branche master mobile), s'inscrire a une formation, faire une formation et modifier ses infos.

Com 1668 staging

---

src/core/api/InternalHours.js
src/core/components/courses/SlotContainer.vue
src/core/mixins/userMixin.js
src/core/pages/signin/Authenticate.vue
src/modules/client/components/customers/infos/ProfileInfo.vue
src/modules/client/components/planning/DeleteEventsModal.vue
src/modules/client/mixins/contractMixin.js
src/modules/client/mixins/planningActionMixin.js
src/modules/client/pages/ni/auxiliaries/Directory.vue
src/modules/client/pages/ni/config/RhConfig.vue
src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue
src/modules/vendor/pages/ni/users/trainers/TrainersDirectory.vue

- Cas d'usage : Creation / Liste / Suppression des heures internes + plus d'heure interne par defaut

Refacto internal hour

---

src/core/data/constants.js
src/css/planning.styl
src/modules/client/pages/ni/config/RhConfig.vue

Refacto internalHour en internal_hour

From camel case to kebab case

---

src/modules/vendor/components/programs/ProgramCreationModal.vue
src/modules/vendor/pages/ni/config/CategoriesDirectory.vue
src/modules/vendor/pages/ni/config/ProgramsDirectory.vue

- Cas d'usage : le champs de la categorie apparait lors de la creation d'un programme

COM-1658 add category select to program creation

---

src/core/api/Courses.js
src/modules/vendor/components/courses/AccessRuleCreationModal.vue
src/modules/vendor/components/courses/ProfileAccess.vue

Lorsque je clique sur le bouton ajouter un règle d'accès, une modale s'ouvre me permettant d'ajouter une règle d'accès à ma formation

Com 1655 - POST

---

src/core/components/courses/ProfileAdmin.vue
src/modules/vendor/components/programs/ProfileInfo.vue

- Cas d'usage : Edition du champ objectifs pedagogiques

COM-1660 - add learning goals

---

src/core/helpers/alenvi.js
src/core/mixins/logInMixin.js
src/router/redirect.js

- Cas d'usage : Verifier que l'on peut bien se connecter. 
J'ai un petit doute sur le changement: https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Set-Cookie/SameSite 
Cela donne plus d'acces au cookies et j'ai un doute par rapport a cette partie la : "[les cookies] seront envoyés lors de requêtes GET initialisées par des sites tiers".

COM-1668 set sameSite cookies to lax

---

src/core/components/BiColorButton.vue
src/core/components/courses/CourseInfoLink.vue
src/core/components/courses/ProfileAdmin.vue
src/core/components/courses/TraineeTable.vue

- [] J'ai verifié la fonctionnalite sur mobile - np
- Périmetre roles : admin / rof / coach
Refacto button admin avec bicolorbutton

COM-1662 - Refacto ProfileAdmin

---

src/core/data/constants.js
src/modules/client/mixins/payMixin.js
src/modules/client/pages/ni/pay/ContractEnds.vue
src/modules/client/pages/ni/pay/ToPay.vue

- Cas d'usage : Ajouter les fins de contrat dans les exports 123 paie

COM-1675 - add contracts end on 123paie exports

---

src/core/mixins/learnerDirectoryMixin.js
src/modules/client/pages/ni/courses/LearnersDirectory.vue
src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue

- Périmetre roles : rofs coachs
- Cas d'usage : affichage de deux colonnes pour les formations suivies coté vendeur

Com 1677 learnerDirectoryMixin

---

src/core/api/Courses.js
src/modules/vendor/components/courses/ProfileAccess.vue

Je peux supprimer une règle d'accès

COM-1655 - Add delete route

---

src/modules/vendor/components/courses/ProfileAccess.vue

COM-1655 - Fix

---

src/core/api/BillSlips.js
src/core/api/Bills.js
src/core/api/Courses.js
src/core/api/CreditNotes.js
src/core/api/TaxCertificates.js
src/core/components/courses/ProfileAdmin.vue
src/core/helpers/file.js
src/modules/client/components/contracts/ContractsCell.vue
src/modules/client/components/customers/billing/CustomerBillingTable.vue
src/modules/client/components/customers/billing/ProfileBilling.vue
src/modules/client/components/customers/infos/ProfileInfo.vue
src/modules/client/pages/ni/billing/TppBillSlips.vue

- Périmetre interface : Les deux
Interface client : 
- Téléchargement des templates vierges de contrat / avenant / mandat / devis 
- Téléchargement des bordereaux tiers payeurs
- Téléchargement des factures
- Téléchargement des avoirs
Interface vendeur
- Téléchargement des attestations de fin de formations
- Téléchargement des feuilles d'émargement

Com 1689 pdfs

---

src/modules/client/components/customers/ConflictModal.vue
src/modules/client/components/customers/EventConflictModal.vue
src/modules/client/components/planning/Agenda.vue
src/modules/client/components/planning/PlanningEvent.vue
src/modules/client/mixins/planningEventMixin.js
src/modules/client/pages/auxiliaries/planning/AuxiliaryAgenda.vue
src/modules/client/pages/customers/CustomerAgenda.vue

- Périmetre interface : erp
- Périmetre roles : aidant
- Cas d'usage : je vois les éventements simultanés

Com 1699 planning

---

src/core/api/Users.js

Ajout de `origin` a la création d'un utilisateur
Interface client
- Création d'un auxiliaire
- Création d'un apprenant
- Création d'un aidant
- Création d'un coach
Interface vendeur
- Ajout d'un nouvel apprenant a une formation
- Création d'un formateur

COM-1710 - add origin in user creation

---

src/css/planning.styl

- Périmetre roles : Coach / auxiliaire
- Cas d'usage : qwuand le nom sur le planning esst trop long, il ne depasse pas du rectange evenement

COM-1699 - fix overflow

---

src/core/components/CourseProgress.vue
src/core/components/learners/ProfileCourses.vue
src/modules/vendor/components/courses/ProfileFollowUp.vue

- Cas d'usage : je peux voir la progression détaillée des apprenants

Com 1694 expandingTable

---

src/core/components/learners/ProfileCourses.vue
src/core/components/table/ExpandingTable.vue

- Cas d'usage : création d'une expanding table réutilisable a souhait :)

COM-1694 exported expanding table

---

src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
src/modules/vendor/mixins/templateMixin.js

Je peux ajouter une réponse aux qcm et qcu.

Com 1691 - post

---

src/core/components/courses/CourseInfoLink.vue
src/core/components/learners/ProfileCourses.vue
src/core/components/table/ExpandingTable.vue

- Périmetre interface : les 2 
- Périmetre roles : Coach / rof
- Cas d'usage : Changement de l'icone pour le telechargement des convocations + ajout du loader sur le expansibleTable

Com 1661 icon

---

src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue

- Périmetre interface : Vendor
- Cas d'usage : homogeneisation des classes

Com 1691 class

---

src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue

- Cas d'usage : je peux ajouter et supprimer des orderedAnswers

Com 1690 post delete orderedAnswers

---

src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue

Suppression et ajout de falsyGapAnswer via la route voulue

Com 1693 post delete

---

src/css/app.styl
src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue

- Cas d'usage : ajout du required pour QuestionAnswers et utilisation des constantes pour chaque template

COM-1693 using constants

---

src/modules/vendor/components/programs/ActivityCreationModal.vue
src/modules/vendor/components/programs/ActivityEditionModal.vue
src/modules/vendor/components/programs/CategoryCreationModal.vue
src/modules/vendor/components/programs/CategoryEditionModal.vue
src/modules/vendor/components/programs/ProfileContent.vue
src/modules/vendor/components/programs/StepCreationModal.vue
src/modules/vendor/components/programs/StepEditionModal.vue
src/modules/vendor/components/programs/SubProgramCreationModal.vue
src/modules/vendor/pages/ni/config/CategoriesDirectory.vue

- Cas d'usage : fix no mutating props

Com 1740 fix no mutating props chapter one

---

package-lock.json
package.json

- les méthodes ```axios.all()``` et ```axios.spread()``` sont dépréciées (non concernés!)
- n'hésitez pas à re-vérifier de votre côté différentes requêtes. J'ai testé pour ma part pas mal de requêtea GET, POST, PUT, DELETE, requêtes d'authentification, requêtes d'upload de média.
Nombreux ajouts, dont
- la possibilité de désactiver l'auto décompression (utile?)
- une vérification si une requête d’authentification contient des caractères ```non-Latin1```
- possibilité d'ajouter dans le ```request.config``` une constante `maxBodyLength` qui définit la taille max en bytes du body de la requête (je n'ai pas de connaissance en cybersécurité mais c'est peut-être une bonne pratique pour sécuriser l'accès à l'API, et ainsi préserver son accessibilité/éviter d'utiliser la webapp contre l'API dans …

COM-1732 update axios

---

package-lock.json
package.json

6 paquets mis à jour dans cette PR (+ axios ici #879), côté Quasar, une maj des Google Material fonts and SVGs (je crois qu'on utilise nos polices et nos SVGs maison)et côté ESLint 3 nouvelles règles pour vue mais aucune erreur déclarée
- [no-restricted-props](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-restricted-props.md)
- [new-line-between-multiline-property](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/new-line-between-multi-line-property.md)
- [no-restricted-custom-event](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-restricted-custom-event.md)
- fix(app): Electron error - "Extension server error: Object not found: <top>" (#8188) (#8240)</top>
- fix(app): do not call user supplied devServer.before twice and call it …

COM-1734 npm update

---

src/modules/client/components/planning/Agenda.vue
src/modules/client/pages/customers/CustomerAgenda.vue

- Périmetre roles : auxiliaires
- Cas d'usage : en tant qu'auxiliaire, mon agenda s'affiche bien

COM-1776 fix error on axuiliary agenda

---

src/core/components/courses/SlotContainer.vue
src/core/components/courses/SlotCreationModal.vue
src/core/components/courses/SlotEditionModal.vue
src/modules/vendor/components/companies/CompanyCreationModal.vue
src/modules/vendor/components/courses/CourseCreationModal.vue
src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
src/modules/vendor/pages/ni/users/companies/CompaniesDirectory.vue

- Périmetre roles : rof admin formateur
- Cas d'usage : fix no mutating props sur 5 modales

Com 1738 fix no-mutating prop

---

src/core/api/Authentication.js
src/core/api/Users.js
src/core/helpers/alenvi.js
src/core/mixins/logInMixin.js
src/core/pages/AccountInfo.vue
src/core/pages/signin/ForgotPassword.vue
src/core/pages/signin/ResetPassword.vue
src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
src/modules/client/pages/ni/auxiliaries/Directory.vue
src/router/redirect.js

Creation de fichier service / controlleur / route / tests pour l'authentification
Il faut tester :
connexion
refraichissement du token
tout le process de mot de passe oublie
maj du mot de passe sur la page mon compte
envoi du sms a un auxilaire ⚠️mettre son numero de telephone

COM-1689 - create authentication files

---

public/favicon_metadata/browserconfig.xml
public/favicon_metadata/site.webmanifest
src/core/components/menu/SideMenuFooter.vue
src/core/data/constants.js
src/core/mixins/sideMenuMixin.js
src/index.template.html

- Périmetre interface : Toute
- Cas d'usage : MAJ des liens cloudinary vers GCS

COM-1736 - move link from cloudinary to GCS

---

src/modules/client/components/auxiliary/ProfilePay.vue

- Cas d'usage : Je peux charger un document de pay pour l'auxiliaire

COM-1717 - refaco pay document upload

---

src/core/api/Authentication.js
src/modules/client/layouts/Layout.vue

- Périmetre interface : Toute
- Cas d'usage : Faire en sorte qu'avec la nouvelle méthode de connexion, tout le monde ne soit pas deconnecté

Fix deconnection

---

src/core/components/courses/SmsDetailsModal.vue
src/modules/client/components/customers/infos/FundingEditionModal.vue
src/modules/client/pages/customers/Subscriptions.vue

FIx sur : 
- edition des fincancements
- header d'une fiche auxiliaire
- date de signature du mandat

COM-1553 - fix moment

---

src/modules/client/pages/customers/Subscriptions.vue

Fix date de signature du mandat

COM-1553 - fix

---

src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue

COM-1553 - fix staging

---

src/modules/client/components/planning/EventCreationModal.vue
src/modules/client/mixins/planningActionMixin.js
src/modules/client/pages/ni/planning/AuxiliaryPlanning.vue

- Périmetre roles : coach / admin / vendor
Je peux créer un absence sur le planning auxiliaire qui est le prolongement d'une absence existante

Com 1744 - add extension for absence

---

src/core/api/AttendanceSheets.js
src/core/components/courses/AttendanceSheetAdditionModal.vue
src/core/components/courses/ProfileTraineeFollowUp.vue
src/modules/client/components/documents/DocumentUpload.vue
src/modules/vendor/pages/ni/config/CategoriesDirectory.vue

- Cas d'usage : je peux uploader mes feuilles d'émargement

Com 1751 upload attendanceSheets

---

src/core/components/courses/TraineeTable.vue
src/core/data/constants.js
src/modules/client/pages/ni/courses/LearnersDirectory.vue

- Périmetre roles : coach / admin / rof
Lorsque j'ajoute un apprenant (via l'interface client ou vendeur), celui ci reçoit un mail de bienvenue. Sur ce mail, il a les logos Google Play et App Store

COM-1770 - Add welcome email for trainee

---

src/core/components/courses/SurveyChart.vue

COM-1737 fix chart color fill

---

src/modules/client/components/planning/EventCreationModal.vue
src/modules/client/components/planning/EventEditionModal.vue
src/modules/client/mixins/planningActionMixin.js

- Périmetre roles : coach / admin / auxiliaire
Sur la modale d'édition d'une absence, si celle ci est le prolongement d'une autre absence, je vois des infos la concernant
Ce qu'il manque : l'export

Com 1744 edition

---

src/modules/client/mixins/menuItemsMixin.js
src/modules/vendor/mixins/menuItemsMixin.js

- Périmetre roles : coach rof
- Cas d'usage : from `Mes Formations` to `Formations mixtes`

COM-1752 rename

---

src/core/components/courses/ProfileTraineeFollowUp.vue
src/modules/vendor/components/courses/ProfileFollowUp.vue
src/modules/vendor/router/routes.js

- Cas d'usage : je vois la progression dans le suivi des apprenants

COM-1750 followUp for blendedCourses

---

src/core/api/AttendanceSheets.js
src/core/components/courses/ProfileTraineeFollowUp.vue

- Cas d'usage : je peux supp des feuilles

COM-1751 delete attendanceSheet

---

src/core/components/courses/ProfileTraineeFollowUp.vue
src/modules/vendor/components/courses/ProfileFollowUp.vue

- Cas d'usage : vu avec Romain, on harmonise le titre de l'encadré à` Progression des apprenants`

Com 1750 rename

---

src/core/mixins/eLearningCourseDirectoryMixin.js
src/modules/client/pages/ni/courses/ELearningCoursesDirectory.vue
src/modules/vendor/pages/ni/management/ELearningCoursesDirectory.vue

- Cas d'usage : je vois les apprenants de ma structure inscrits aux formations eLearning
BUG: je n'arrive pas a afficher 0 quand il n'y a pas d'apprenant inscrit

COM-1753 add traineesCount

---

src/modules/client/mixins/payMixin.js

FIX
Je n'avais pas pris la diff en compte dans le calcul

[FIX] COM-1748

---

src/modules/client/components/customers/billing/CustomerBillingTable.vue

- Périmetre roles : Coach / Aidant
- Cas d'usage : Quand je sélectionne une grande période pour la facturation, je vois toutes les lignes dans le tableau

COM-1835 - display all lines of table

---

src/store/main.js

- Cas d'usage : Sur ipad en vue horizontal (largeur de 1024px), je vois le menu

COM-1836 - use screen width to display menu burger

---

src/modules/client/pages/ni/courses/Dashboard.vue

- Cas d'usage : centrer les apprenants actifs

COM-1799 center active trainees count

---

src/modules/client/components/config/EstablishmentEditionModal.vue
src/modules/client/components/config/SectorCreationModal.vue
src/modules/client/components/config/SectorEditionModal.vue
src/modules/client/pages/ni/config/CompanyConfig.vue
src/modules/client/pages/ni/config/RhConfig.vue

- Cas d'usage : edition d'etablissement, creation et edition de secteurs

Com 1782 2

---

src/modules/client/pages/ni/courses/Dashboard.vue

- Cas d'usage : Sur le tableau de bord, j'ai le bon nombre d'apprenants actif dans le classement des formations

COM-1799 - fix trainee count

---

src/core/components/ProfileTabs.vue
src/core/components/courses/CourseInfoLink.vue
src/core/components/courses/SlotContainer.vue
src/core/components/learners/ProfileCourses.vue
src/core/pages/signin/Authenticate.vue
src/css/app.styl
src/css/chip.styl
src/css/history.styl
src/css/planning.styl
src/css/table.styl
src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
src/modules/client/components/planning/AuxiliaryIndicators.vue
src/modules/client/components/planning/ChipCustomerIndicator.vue
src/modules/client/components/planning/Planning.vue
src/modules/client/layouts/Layout.vue
src/modules/client/pages/ni/billing/ToBill.vue
src/modules/vendor/components/programs/cards/CardCreationModal.vue
src/modules/vendor/components/programs/cards/templates/TextMedia.vue
src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
src/modules/vendor/layouts/Layout.vue

- Périmetre interface : all
- Périmetre roles : all
- Cas d'usage : responsive design géré en constantes
NOTE: les breakpoints `767/768px` sont passés à `599/600px`
les quelques breakpoints `420/421px` présents sont aussi migrés vers `599/600px`
Pour les couleurs de `Gauge`, aucun moyen trouvé pour récupérer des variables stylus en javascript..

Com 1786 design system

---

src/core/components/courses/ProfileFollowUp.vue
src/core/components/courses/ProfileTraineeFollowUp.vue
src/core/components/courses/TraineeFollowUpTable.vue
src/core/mixins/traineeFollowUpTableMixin.js

- Périmetre roles : rof coach
- Cas d'usage : je vois le rapport d'utilisation des formations eLearning

COM-1755 learner stats

---

src/core/helpers/utils.js
src/modules/client/mixins/payMixin.js
src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue

Export for Simon

---

src/modules/client/pages/ni/auxiliaries/Directory.vue

- Cas d'usage : quand je rattache un compte existant au role auxiliaire, le sms n'est pas envoyé

COM-1876 - fix sms

---

src/modules/vendor/components/programs/cards/templates/OpenQuestion.vue
src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
src/modules/vendor/components/programs/cards/templates/Survey.vue

- Périmetre interface : vendeur 
- Cas d'usage :  je peux indiquer à l'aide d'une checkbox si la réponse à une carte de type questionnaire est obligatoire ou non

COM-1848: add mandatory checkbox for questionnaires

---

src/core/components/courses/ProfileTraineeFollowUp.vue
src/core/components/courses/TraineeFollowUpTable.vue
src/core/components/table/AttendanceTable.vue
src/core/components/table/ExpandingTable.vue

- Cas d'usage : first step of the digitalisation de l'émargement
NOTE: j'ai aussi un commit local pour le vertical q-separator du header mais c'est pas optimum, est-ce vraiment nécessaire? avez-vous d'autres idées d'implémentations qu'un vertical q-separator?

Com 1851 attendanceTable

---

src/core/api/Attendances.js
src/core/components/table/AttendanceTable.vue

- Cas d'usage : je peux modifier les emargements

COM-1851 add and view attendances

---

src/core/api/Attendances.js
src/core/components/table/AttendanceTable.vue

- Cas d'usage : je peux supprimer un émargement

COM-1851 remove attendance

---

src/core/components/courses/ProfileFollowUp.vue
src/core/components/courses/ProfileTraineeFollowUp.vue
src/core/mixins/traineeFollowUpTableMixin.js

- Périmetre interface : vendeur / client
- Périmetre roles : ROF / coach
- Cas d'usage : si un mois je n'ai pas de données, le graphe n'est pas faussé

COM-1843: fix bug if no data in a month

---

src/modules/client/pages/ni/billing/ClientsBalances.vue

- Périmetre roles : ?
- Cas d'usage : je peux exporter un csv avec toutes les données de la balance client
je n'ai pas mis les fonctions dans computed pour mutualiser comme écrit dans le ticket car les traitements effectués étaient assez marginaux et que ça ne me semblait pas nécessaire d'écrire des fonctions pour si peu, vous en pensez quoi ?

COM-1864: export data in csv

---

src/modules/client/pages/ni/billing/ClientsBalances.vue
src/modules/client/pages/ni/customers/CustomersFundingsMonitoring.vue

- Périmetre roles : ?
- Cas d'usage : bouton de télécharement désactivé sur suivi d'aide et balance client si les données ne sont pas chargées

COM-1864: disable download button if data not loaded

---

src/core/components/table/Pagination.vue
src/core/components/table/SimpleTable.vue
src/modules/client/pages/auxiliaries/teams/TeamsDirectory.vue
src/modules/client/pages/ni/billing/TppBillSlips.vue

- Périmetre interface : all
- Périmetre roles : all
- Cas d'usage : fix no-mutating prop sur la pagination des SimpleTables

Com 1855 vu no-mutating prop

---

src/modules/client/pages/ni/courses/Dashboard.vue
src/modules/vendor/pages/ni/config/ActivityProfile.vue

Si je re-utilise une activite et que je supprimer une etape ou elle est utilisée:
- je peux deverouiller l'activite
- je n'ai pas d'erreur sur le tableau de bord
- SUR MOBILE: je n'ai pas d'erreur si je finis cette activite
Interrogation: Si une activite est utilisee dans une etape liee a aucun sous-programme, faut-il verouiller l'activite ? 
Vu lors du developpement de ce ticket: Si on supprimer une etape d'un sous programme utilise dans une formation mixte, l'application mobile casse. --> creation d'un ticket de bug

COM-1908 dont take step.subprogram or granted

---

src/core/components/table/AttendanceTable.vue

- Cas d'usage : le nom ne s'affiche que sur une ligne

COM-1909 fix only one line

---

src/core/mixins/companyMixin.js
src/modules/client/mixins/configMixin.js
src/modules/client/pages/ni/config/CompanyConfig.vue

- Périmètre interface : Client
- Périmètre rôles : Admin
- Cas d'usage : dans la configuration, je peux enregistrer une adresse pour une structure qui n'en a pas
NB : la correction de l'erreur correspond au retrait de cette ligne `get(this.$v.company, path).$touch();`. le reste c'est du boyscoot ;)

COM-1903 - fix address validation

---

src/core/components/table/AttendanceTable.vue

- Périmetre roles : rof / admin
Les nom sur le tableau de présence des apprenants (formation mixte > suivi des stagiaires) est désormais centré (suite au retour de Romain)

COM-1909 - Fix Romain's review

---

src/core/data/user.js
src/core/mixins/companyMixin.js
src/modules/client/mixins/configMixin.js
src/modules/client/pages/ni/config/CompanyConfig.vue

je peux ajouter une adresse
si je l'enleve j'ai une erreur du front

COM-1903 - initialize address

---

src/modules/client/components/planning/Planning.vue

- Périmetre roles : aidant/auxiliaire/coach
- Cas d'usage : Lorsqu'une auxiliaire appartient a deux secteur sur une meme semaine, je peux afficher le planning.

COM-1920 handle when an auxiliary is in two sector for one week

---

src/modules/client/components/planning/Planning.vue

COM-1920 staging

---

src/modules/client/components/config/SectorCreationModal.vue
src/modules/client/components/config/SectorEditionModal.vue

- ~~[ ] J'ai verifié la fonctionnalite sur mobile~~
- Périmetre roles : coach / admin
trim du nom de l'équipe dans sector creation modal

COM-1878 - trim name in sector creation modal

---

src/core/components/table/CoachList.vue
src/core/data/user.js
src/core/mixins/companyMixin.js
src/modules/client/mixins/configMixin.js
src/modules/client/pages/ni/config/CoachConfig.vue
src/modules/client/pages/ni/config/CompanyConfig.vue
src/modules/client/pages/ni/config/CustomersConfig.vue
src/modules/client/pages/ni/config/RhConfig.vue

- Cas d'usage : Je peux renseigner les informations de ma structure dans Configuration generale (tester pour une structure avec/sans erp)
EDIT: il faut a present tester toutes les configs (generales, rh, beneficiaires et coach)

COM-1919 fix bug on companyconfig

---

src/statics/cguCompani.html

- Périmetre interface : vendeur / client
- Cas d'usage : ajout téléphone (facultatif) dans CGU

COM-1899: add phone (optional)

---

.eslintrc.js
src/modules/client/pages/ni/courses/Dashboard.vue

Remove console lint error in dev environment

---

src/core/components/courses/ProfileFollowUp.vue
src/core/mixins/chartMixin.js
src/modules/client/pages/ni/courses/Dashboard.vue

- Périmetre roles : coach/admin/ROF
- Cas d'usage : sur la page apprenant, dans l'onglet "formation", j'ai un encadré avec un graphe du nombre d'activités réalisées par mois

COM-1845: chart for actities by month

---

src/core/data/user.js
src/modules/client/mixins/configMixin.js
src/modules/client/pages/ni/config/RhConfig.vue

- J'ai ajouté une variable d'environnement : np
- Cas d'usage : En tant que formateur (sans entreprise) je peux me connecter + verifier les modifications de config cote client
Le bug venait du fait que user.company etait defini pour tous les utilisateurs, y compris ceux qui n'en avait pas car on l'initialisait dans le model user. Cela posait probleme dans ability

COM-1945 fix connection for trainers

---

src/core/data/user.js
src/modules/client/mixins/configMixin.js
src/modules/client/pages/ni/config/RhConfig.vue

MES intermédiaire 
(connexion formateurs)

MES intermédiaire

---

src/core/components/learners/ProfileCourses.vue
src/core/helpers/date.js
src/modules/client/pages/ni/courses/Dashboard.vue

- Périmetre interface : client / vendeur
- Périmetre roles : coach / admin / rof
- Cas d'usage : sur la page apprenant, dans l'onglet "formation", j'ai un encadré avec un graphe du nombre d'activités réalisées par mois

COM-1897: add graph in learner

---

src/core/data/constants.js
src/modules/client/components/customers/billing/CustomerBillingTable.vue
src/modules/client/components/customers/billing/ProfileBilling.vue

- Périmetre roles : admin / coach
- Cas d'usage : dans la page bénéficiaire, onglet facturation, je peux ajouter une règlement de type espèce

COM-1924: add cash as a payment method

---

src/modules/vendor/components/programs/ProfileContent.vue

- Périmetre roles : trainer / admin
Je ne peux pas supprimer une étape lié à un créneau

COM-1910 - Prevent step deletion if step is linked to courseSlot

---

src/core/components/courses/ConnectedDot.vue
src/core/components/courses/TraineeFollowUpTable.vue
src/core/mixins/traineeFollowUpTableMixin.js

- Périmetre roles : rof / coach / admin / formateur
- Cas d'usage : sur le tableau de suivi des apprenants d'une formation mixte, je sais qui s'est connecté à l'app

COM-1894: add is connected column

---

src/modules/client/mixins/contractMixin.js

- Périmetre roles : Admin / coach
- Cas d'usage : modification du message d'erreur lors de l'édition du contrat

COM-1949 - update error message

---

src/core/api/Authentication.js

- Périmetre interface : webapp
- Périmetre roles : role
- Cas d'usage : Modification du message de retour de la route logout + on ne supprime plus les cookies qui sont deja expirés (alenvi_token et user_id)
J'ai teste que la connexion fonctionnait bien pour les roles: 
- client_admin + vendor_admin
- coach
- formateur
- auxiliaire
- aidant
sur les navigateurs: chrome, firefox, safari

COM-1929 remove cookie remove for expired cookies

---

src/core/components/courses/ProfileTraineeFollowUp.vue
src/core/components/courses/TraineeFollowUpTable.vue
src/core/components/learners/ProfileCourses.vue
src/core/components/table/ExpandingTable.vue

- ~~J'ai ajouté une variable d'environnement ~~:
- Périmetre roles : rof/coach/admin/formateur
- Cas d'usage : colonne "connecté à l'app" seulement pour les formations blended

COM-1894: fix column display

---

src/modules/client/components/auxiliary/ProfileContracts.vue
src/modules/client/components/contracts/ContractCreationModal.vue
src/modules/client/components/contracts/ContractsCell.vue
src/modules/client/components/contracts/VersionCreationModal.vue
src/modules/client/components/contracts/VersionEditionModal.vue
src/modules/client/mixins/contractMixin.js
src/modules/client/pages/ni/pay/ContractMonitoring.vue

- Cas d'usage : Dans l'edition d'une version de contrat, quand je modifie la date de debut, si elle est anterieure a la date de debut de la version precedente, j'ai un message d'erreur explicite

COM-1949 - update error message on version startDate

---

src/core/api/Authentication.js
src/core/helpers/alenvi.js
src/router/index.js
src/store/main.js

- Cas d'usage : Retirer l'user_id des cookies

COM-1965 - remove user_id from cookies

---

src/modules/vendor/components/programs/SubProgramPublicationModal.vue

- Périmetre roles : Rof
- Cas d'usage : Lors de la publication d'un sous programme, quand je selectionne "Choisir une structrue" j'ai un message d'attention si je valide sans avoir selectionné une structure

Validations accessrules

---

src/core/components/courses/AttendanceSheetAdditionModal.vue
src/core/helpers/utils.js
src/core/mixins/chartMixin.js
src/modules/client/components/auxiliary/ProfilePay.vue
src/modules/client/components/contracts/ContractsCell.vue
src/modules/client/components/customers/infos/ProfileInfo.vue
src/modules/client/mixins/helperMixin.js
src/modules/client/pages/customers/Subscriptions.vue

- Périmetre roles : Aidant / Coach
Sur la page d'un auxiliaire,  cote **coach** et **auxiliaire** : 
- onglet paie : date de document de paie
- onglet contrat : date de debut et de fin des contrats et avenants
Sur la page info bénéficiaire cote **coach** et **aidant** :
- La date de validation des souscriptions
- Date de téléchargement des mandats
- Date de téléchargement des devis
_NB : deux futures améliorations pour cette méthode :_
_- la déplacer dans le service `date.js`_
_- passer en deuxième paramètre le format pour mutualiser encore d'autres endroits_

Boy scoot date 2

---

src/core/helpers/date.js
src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
src/modules/client/pages/ni/billing/CreditNotes.vue

- Périmetre roles : admin ROF
- Cas d'usage : refacto des avoirs

COM-1946: refacto creditNote

---

src/core/api/Users.js
src/core/components/courses/ProfileTraineeFollowUp.vue
src/core/components/table/AttendanceTable.vue
src/core/helpers/ability.js
src/modules/client/pages/ni/courses/BlendedCourseProfile.vue

- Périmetre roles : coach / client admin / vendor / rof
J'ai accès à l'onglet 'Suivi des stagiaires' dans la page profil d'une formation mixte intra dans l'interface client.
En tant que coach / client admin, je ne peux pas modifier le tableau de présence ni ajouter/supprimer une fiche de présence.

Com 1925 2

---

src/core/components/courses/SmsSendingModal.vue
src/modules/client/components/customers/billing/CreditNoteEditionModal.vue
src/modules/client/pages/ni/billing/CreditNotes.vue

- Cas d'usage : vue no mutating props pour la modification d'un avoir
Fix dans la modale d'envoie de sms: possibilite de changer de convocation à rappel

Com 1946 edition

---

src/core/api/Courses.js
src/modules/vendor/components/courses/ProfileQuestionnaires.vue
src/modules/vendor/pages/ni/management/ELearningCourseProfile.vue

- Cas d'usage : Possibilite de voir les reponses aux questionnaires d'une formation elearning
- Tester aussi la recuperation des statistiques sur la page d'une formation elearning et sur la page d'un apprenant (cf changment dans le service sur api)

COM-1955 add questionnaire page in elearning formation

---

.eslintrc.js
src/core/helpers/vuelidateCustomVal.js
src/modules/client/components/auxiliary/ProfileContracts.vue
src/modules/client/components/customers/billing/CreditNoteCreationModal.vue
src/modules/client/mixins/contractMixin.js
src/modules/client/pages/ni/billing/CreditNotes.vue

- Cas d'usage : vue no mutating props poru la creation d'avoirs
Tester les pages utilisant dateRange et dateTimeRange :
- planning
- contrat/version
- export
- ajout de creneau dans une formation
- facturation
- page facturation beneficiaire (cote beneficiaire egalement)
- tableau de bord formation
- page suivi contrat
- page suivi absence
- profil beneficiaire : modale financement - fix sur le fait que la date de fin n'est pas obligatoire

Com 1946 creation

---

src/core/helpers/rbac.js
src/modules/vendor/mixins/menuItemsMixin.js
src/modules/vendor/pages/ni/pedagogy/CategoriesDirectory.vue
src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue
src/modules/vendor/router/routes.js

- Périmetre roles : ROF/admin
- Cas d'usage : dans le menu Pédagogie, j'ai accès à une page "questionnaires"

COM-1973: add questionnaire section to menu

---

src/core/api/Questionnaires.js
src/core/components/courses/QuestionnaireCell.vue
src/core/data/constants.js
src/modules/vendor/components/programs/QuestionnaireCreationModal.vue
src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue

- Périmetre roles :  admin/ROF
- Cas d'usage : je peux créer et récupérer des questionnaires

COM-1974: i can create questionnaire

---

src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue

- Périmetre roles : admin/ROF
- Cas d'usage : je ne peux pas créer un questionnaire d'un type donné s'il en existe déjà un en brouillon

COM-1974: can't create a questionnaire if already one in draft

---

src/core/components/courses/ProfileOrganization.vue
src/core/mixins/courseMixin.js
src/store/course.js

- Périmetre interface : Trainer 
- Périmetre roles : trainer
ETQ trainer, je vois le select du référent compani sur la page profile d'une formation blended. Je ne peux pas le modifier.

COM-1980 - Fix for trainer

---

src/core/components/courses/ProfileOrganization.vue
src/core/components/courses/TraineeTable.vue

- Périmetre interface : Tous
ETQ formateur je n'ai plus de 403 quand j'arrive sur la page d'une formation
-- Se connecter en tant que formateur
Sur une formation INTRA, je peux ajouter un stagiaire de la structure
Sur une formation INTER_B2B, je ne peux pas ajouter un stagiaire
-- Se connecter en tant que ROF
Sur une formation INTRA, je peux ajouter un stagiaire
Sur une formation INTER_B2B, je peux ajouter un stagiaire avec une structure
Sur une formation INTER_B2B, je peux ajouter un stagiaire sans structure
-- Se connecter en tant que coach client
Sur une formation INTRA, je peux ajouter un stagiaire de ma structure
Sur une formation INTER_B2B, je ne peux pas ajouter un stagiaire
Tester également …

COM-2010 - fix trainee addition on inter b2b course profile

---

src/modules/vendor/components/programs/cards/CardContainer.vue
src/modules/vendor/components/programs/cards/CardEdition.vue
src/modules/vendor/components/programs/cards/templates/FillTheGaps.vue
src/modules/vendor/components/programs/cards/templates/MultipleChoiceQuestion.vue
src/modules/vendor/components/programs/cards/templates/OrderTheSequence.vue
src/modules/vendor/components/programs/cards/templates/QuestionAnswer.vue
src/modules/vendor/components/programs/cards/templates/SingleChoiceQuestion.vue
src/modules/vendor/components/programs/cards/templates/TextMedia.vue
src/modules/vendor/components/programs/cards/templates/TitleTextMedia.vue
src/modules/vendor/mixins/templateMixin.js
src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
src/modules/vendor/store/card.js
src/modules/vendor/store/program.js
src/store/index.js

- Cas d'usage :  adaptation de la gestion des cartes pour en extraire la notion d’activité

COM-1988: refacto card container

---

src/core/api/PartnerOrganizations.js
src/modules/client/pages/ni/customers/PartnerOrganizationsDirectory.vue

- Périmetre roles : coach / admin
Sur le répertoire des structures partenaires (dans Bénéficiaires), j'ai accès au tableau des  structures partenaires de ma structure (company).

Com 1977 list

---

src/core/components/courses/QuestionnaireCell.vue

- Cas d'usage : quand le titre d'un questionnaire est trop long il passe sur 2 lignes puis se cache avec ...

COM-1974 - add ellispis on 2 lines

---

src/core/api/Activities.js
src/core/api/Cards.js
src/core/api/Questionnaires.js
src/core/components/ProfileTabs.vue
src/core/components/courses/QuestionnaireCell.vue
src/core/mixins/cardMixin.js
src/modules/vendor/components/programs/cards/CardEdition.vue
src/modules/vendor/components/questionnaires/ProfileEdition.vue
src/modules/vendor/mixins/templateMixin.js
src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue

- Cas d'usage : je peux éditer le questionnaire de recueil des besoins
je n'ai pas mis createCard dans la mixin, j'avais peur que la méthode fasse un peu usine à gaz avec pleins de conditionnelles, vous en pensez quoi ?

COM-1988: edit questionnaire cards

---

src/core/components/courses/QuestionnaireCell.vue
src/core/components/learners/ProfileInfo.vue
src/modules/vendor/components/questionnaires/ProfileEdition.vue
src/modules/vendor/pages/ni/pedagogy/ActivityProfile.vue
src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue

- Cas d'usage : je peux publier un questionnaire

COM-1976: can publish questionnaire

---

src/core/components/learners/ProfileCourses.vue
src/core/mixins/chartMixin.js

- Périmetre interface : Client et Vendeur
- Périmetre roles : ROF et coach
- Cas d'usage : Sur l'onglet formation de la page apprenants, le nombre d'activités eLearning réalisées comptabilise le formations mixtes

COM-2008 - count all eLearning activities not only those from eLearning steps

---

src/core/mixins/courseFiltersMixin.js

- Périmetre interface : vendeur / client
- Périmetre roles : coach / client_admin / trainer / vendor_admin
Bug constaté :
- la liste des intervenants n'est pas la bonne.
- la liste des référents compani semble trop courte
Bug corrigé :
- la liste des intervenants est désormais complète
- la liste des référent compani est bonne, je préviens Alison des conditions pour être référent compani

COM-2031 - Fix trainerFilterOptions

---

src/core/components/courses/TraineeEditionModal.vue
src/core/components/courses/TraineeTable.vue

- Périmetre roles : rof:admin
- Cas d'usage : ajout de validations front sur le nom et le numéro de téléphone sur la modale d'édition d'un stagiaire

COM-1989: name and phone required on trainee edition modal

---

src/core/components/courses/QuestionnaireCell.vue
src/modules/vendor/components/programs/QuestionnaireCreationModal.vue
src/modules/vendor/components/questionnaires/ProfileEdition.vue
src/modules/vendor/mixins/templateMixin.js
src/modules/vendor/pages/ni/pedagogy/QuestionnaireProfile.vue
src/modules/vendor/pages/ni/pedagogy/QuestionnairesDirectory.vue

- Cas d'usage :  dans le modèle Questionnaire, le champ title est renommé name

COM-2027: change title in name

---

src/modules/client/pages/ni/pay/ToPay.vue

- Cas d'usage : Sur la page paie mensuelle, je peux telecharger le fichier des heures pour 123 paie

COM-1960 - add 123paie pay file

---

src/modules/client/components/customers/PartnerCreationModal.vue
src/modules/client/pages/ni/customers/PartnerOrganizationProfile.vue

- Cas d'usage : je peux créer un partenaire sans prénom et prénom est le premier champ de la modale de création de partenaire

COM-2004: firstname is optional and the first field

---

src/core/api/CustomerPartners.js
src/core/api/Partners.js
src/modules/client/components/customers/ProfileFollowUp.vue
src/modules/client/components/customers/infos/CustomerPartnerCreationModal.vue

~~- J'ai ajouté une variable d'environnement :~~
- Cas d'usage :  
- créer des partenaires dans Structures Partenaires s'il n'y en a pas déjà
- ajouter un partenaire à un bénéficiaire
- on ne peut pas ajouter deux fois un partenaire
dans le ticket il était écrit d'afficher la mention "Pas de partenaire renseigné" s'il n'y a pas de partenaire mais il me semble que sur les responsive tables on ne le précise jamais quand elles sont vides du coup je ne l'ai pas mis non plus

COM-2005: create and add customer partner

---

src/core/data/constants.js

- Cas d'usage : ajout de directeur dans les fonctions possibles pour les partenaires

COM-2004: add director in job options

---

src/core/api/Questionnaires.js
src/core/components/courses/OpenQuestionChart.vue
src/core/components/courses/ProfileTraineeFollowUp.vue
src/core/helpers/rbac.js
src/core/mixins/questionnaireAnswersMixin.js
src/core/pages/DocumentSigned.vue
src/modules/vendor/components/courses/ProfileQuestionnaires.vue
src/modules/vendor/pages/ni/management/QuestionnaireAnswersProfile.vue
src/modules/vendor/router/routes.js

- Périmetre roles : ROF/admin/formateur
- Cas d'usage : je peux consulter les réponses au questionnaire de recueil des attentes
Pour tester : créer un questionnaire avec des cartes SURVEY, QUESTION_ANSWERS, OPEN_QUESTION et répondre pour 2-3 utilisateurs

COM-2036: display questionnaire answers

---

src/modules/vendor/pages/ni/management/QuestionnaireAnswersProfile.vue

- Périmetre roles : formateur/admin
- Cas d'usage : bug dû à l'abscence de company pour les formations inter
Tester : réponse d'un questionnaire de début et de fin de formation sur une formation inter et intra

COM-2039: minor bug

---

src/css/app.styl
src/modules/client/components/auxiliary/AuxiliaryProfileHeader.vue
src/modules/client/components/customers/CustomerProfileHeader.vue
src/modules/client/pages/ni/auxiliaries/AuxiliaryProfile.vue
src/modules/client/pages/ni/customers/CustomerProfile.vue

- Cas d'usage : Sur la fiche auxiliaire et la fiche bénéficiaire, quand on modifie le nom, il se modifie en temps réel dans le titre

COM-1994: update title auxiliary and customer profile

---

src/core/components/DirectoryHeader.vue
src/modules/client/components/customers/CustomerProfileHeader.vue
src/modules/client/pages/ni/customers/CustomersDirectory.vue
src/modules/vendor/pages/ni/management/BlendedCourseProfile.vue

- Sur le répertoire : 
- Je ne vois plus la colonne "Client"
- Je ne vois plus le toggle en haut a droit
- Sur la fiche bénéficiaire :  je ne vois plus le statut dans l'en-tête

COM-2065: remove client/prospect notion

---

src/core/api/CustomerPartners.js
src/modules/client/components/customers/ProfileFollowUp.vue
src/modules/client/mixins/helperMixin.js

- Périmetre roles : auxiliaire/coach/admin
- Cas d'usage : je peux retirer un partenaire sur la fiche bénéficiaire +boyscout rajout d'un point sur la suppresion d'un aidant

COM-2070: remove customer partner

---

src/core/components/courses/TraineeTable.vue

- Périmetre roles : admin/formateur
- Cas d'usage : quand j'ajoute un apprenant déjà existant à une formation il ne reçoit plus de mail de bienvenue + passage de la logique d'envoi d'email dans le back

COM-2072: send email only to new trainee
